import assert from "node:assert/strict";
import {NOTIFICATION_LEASE_MS,NOTIFICATION_INACTIVE_RETENTION_MS,mayDeliverTo,shouldPruneInactive} from "./notification-lease-policy.mjs";
const now=1_900_000_000_000,token="x".repeat(80);
const record={ownerUid:"A",installationId:"device-1",fcmToken:token,generation:3,enabled:true,leaseUntilMs:now+NOTIFICATION_LEASE_MS};
assert.equal(mayDeliverTo({recipientUid:"A",registration:record,owner:record,nowMs:now}),true);
assert.equal(mayDeliverTo({recipientUid:"B",registration:record,owner:record,nowMs:now}),false);
assert.equal(mayDeliverTo({recipientUid:"A",registration:record,owner:{...record,ownerUid:"B"},nowMs:now}),false);
assert.equal(mayDeliverTo({recipientUid:"A",registration:record,owner:{...record,generation:4},nowMs:now}),false);
assert.equal(mayDeliverTo({recipientUid:"A",registration:record,owner:record,nowMs:now+NOTIFICATION_LEASE_MS}),false);
assert.equal(mayDeliverTo({recipientUid:"A",registration:{...record,enabled:false},owner:record,nowMs:now}),false);
assert.equal(shouldPruneInactive({lastSeenMs:now-NOTIFICATION_INACTIVE_RETENTION_MS,leaseUntilMs:now-1,nowMs:now}),true);
assert.equal(shouldPruneInactive({lastSeenMs:now-1000,leaseUntilMs:now-1,nowMs:now}),false);
assert.equal(shouldPruneInactive({lastSeenMs:now-NOTIFICATION_INACTIVE_RETENTION_MS,leaseUntilMs:now+1,nowMs:now}),false);
console.log("PASS: lease expires, single current owner, generation fencing, inactive cleanup");
