from pathlib import Path
stamp='''\n## 0.9.7.5–0.9.7.9 attachment phase closeout — repository validated\n\nRuntime 0.9.7.9 completes the allocated attachment phase: integrity-checked receive/decrypt with explicit object-URL lifecycle; UID-scoped offline/cache recovery policy; message-level receipt authority; trace-free disappearing-attachment purge planning and serialized storage/local-before-source execution; and the permanent attachment closeout matrix. Firebase Storage download remains solely in `firebase.js`. Client Storage deletion remains denied; server purge dependencies are injected into the dedicated purge executor and no live Firebase deployment occurred. Full Rebuild Baseline Security Gate `34064314857` SUCCESS. Next allocated build is 0.9.8.0 invitation deterministic-owner rebuild; rejected 0.9.4.12-.15 invite/install logic remains forbidden.\n'''
for fn in ['README.md','hermes-memory.txt','CURRENT-REBUILD.md','RUNTIME-AUTHORITY-MAP.md','architecture-ownership.txt','ACCOUNT-E2EE-FIRESTORE-AUTHORITY.md','DISAPPEARING-PURGE-AUTHORITY.md','ATTACHMENT-AUTHORITY.md']:
 p=Path(fn);p.write_text(p.read_text()+stamp)
p=Path('FIDUNIO-BUILD-CHECKLIST.md');s=p.read_text();s=s.replace('- 0.9.7.5 and later allocated builds: **0.0 earned so far**.\n- **Current total: 80.0 / 100.0, reported as 80%.**','- 0.9.7.5 attachment receive/decrypt/display/play is repository-validated: **+1.0 earned**.\n- 0.9.7.6 attachment offline retention/account isolation is repository-validated: **+1.0 earned**.\n- 0.9.7.7 attachment receipt/lifecycle authority is repository-validated: **+1.0 earned**.\n- 0.9.7.8 disappearing attachment trace-free purge is repository-validated: **+1.0 earned**.\n- 0.9.7.9 attachment phase security closeout is repository-validated: **+1.0 earned**.\n- 0.9.8.0 and later allocated builds: **0.0 earned so far**.\n- **Current total: 85.0 / 100.0, reported as 85%.**').replace('This 80.0-point ledger is authoritative','This 85.0-point ledger is authoritative')
for n in range(5,10):
 import re
 s=re.sub(rf'(\| \*\*0\.9\.7\.{n}\*\* \|.*?\| )(?:CURRENT|PLANNED)( \|)',rf'\1REPOSITORY-VALIDATED\2',s)
s=s.replace('**CURRENT — Attachment receive/decrypt/display/play.**','**Attachment receive/decrypt/display/play.**').replace('| **0.9.8.0** | **Invitation deterministic-owner rebuild.**','| **0.9.8.0** | **CURRENT — Invitation deterministic-owner rebuild.**').replace('| **0.9.8.0** | **CURRENT — Invitation deterministic-owner rebuild.** Re-audit current invitation code and establish one serialized invitation owner/write path; do not adapt rejected 0.9.4.12-.15 invite-install logic. | Architecture/rules tests green before changing install behavior. | PLANNED |','| **0.9.8.0** | **CURRENT — Invitation deterministic-owner rebuild.** Re-audit current invitation code and establish one serialized invitation owner/write path; do not adapt rejected 0.9.4.12-.15 invite-install logic. | Architecture/rules tests green before changing install behavior. | CURRENT |')
s=s.replace('| Attachment receive/decrypt/display/play | NOT DONE | Must work in direct and group conversations. |','| Attachment receive/decrypt/display/play | DONE | 0.9.7.5 integrity-checked receive and object lifecycle; baseline 34064314857 green. |').replace('| Attachment retention/history/offline | NOT DONE | Must follow Firestore-authoritative/cache/Outbox ownership. |','| Attachment retention/history/offline | DONE | 0.9.7.6 UID-scoped Outbox/cache authority; baseline green. |').replace('| Attachment receipts/lifecycle | NOT DONE | Must integrate with message status model. |','| Attachment receipts/lifecycle | DONE | 0.9.7.7 message-level receipt authority; baseline green. |').replace('| Disappearing attachments | NOT DONE | Purge attachment metadata, encrypted chunks/blobs, thumbnails/previews, local decrypted object URLs/cache, message references, and attachment-specific receipts together. |','| Disappearing attachments | DONE | 0.9.7.8 enumerated physical traces + serialized storage/local-before-source purge executor; no tombstones/client Storage delete. |')
s+=stamp;p.write_text(s)
