from pathlib import Path
GATE='34060880885'
HEAD='593c078727b6e5fc062a0b20e9d3cf88b2bc1797'

def append(path,text):
    p=Path(path); s=p.read_text();
    if text.strip() not in s: p.write_text(s.rstrip()+"\n\n"+text.strip()+"\n")

p=Path('FIDUNIO-BUILD-CHECKLIST.md'); s=p.read_text()
s=s.replace('| **0.9.6.25** | **CURRENT — Restart/reconnect stale-client anti-resurrection proof.** Persisted history + encrypted Outbox survive ordinary offline restart, but an already-authoritatively-purged disappearing ID is removed before reconnect flush/projection. Prove stale cache cannot re-upload or re-project expired material. | Cold-start, offline->online, stale snapshot and duplicate retry tests green; no `location.reload()`/timer rescue. | CURRENT |','| **0.9.6.25** | **Restart/reconnect stale-client anti-resurrection proof.** Persisted history + encrypted Outbox survive ordinary offline restart. A durable local `sendAttempted` marker is written before each cloud write; authoritative absence after an attempted send fails closed and is never auto-replayed, closing the post-commit/pre-observation crash ambiguity without server tombstones or accepted-ID registries. | Focused replay-barrier test covers accepted, purged, never-attempted queued, missing-authority and ambiguous-crash cases; full gate `34060880885` SUCCESS. | REPOSITORY-VALIDATED |')
s=s.replace('| **0.9.6.26** | **Multi-device expiry convergence foundation.** Define and test same-UID device behavior after server purge; each device independently converges local traces to authoritative absence without installation-local lifetime authority. | Repository multi-device simulation proves both devices converge and neither can resurrect source/Outbox/history. | PLANNED |','| **0.9.6.26** | **CURRENT — Multi-device expiry convergence foundation.** Define and test same-UID device behavior after server purge; each device independently converges local traces to authoritative absence without installation-local lifetime authority. | Repository multi-device simulation proves both devices converge and neither can resurrect source/Outbox/history. | CURRENT |')
s=s.replace('Current earned total: **69.5 / 100.0 = 69.5%** (normal status report: **70%**).','Current earned total: **70.0 / 100.0 = 70.0%** (normal status report: **70%**).')
p.write_text(s)

append('CURRENT-REBUILD.md',f'''### 0.9.6.25 fail-closed restart/reconnect closeout — REPOSITORY-VALIDATED
User approved the conservative fail-closed resolution for the post-commit/pre-observation crash boundary. The encrypted IndexedDB Outbox now records `sendAttempted:true` durably before direct or group cloud transmission. Reconnect performs an authoritative server read first. Server-present IDs are accepted and their stale Outbox record is removed; prior-server-backed disappearing IDs that are authoritatively absent are physically purged; never-attempted and never-server-backed work may replay; but an attempted ID that is authoritatively absent is marked failed and **never automatically replayed** because FIDUNIO cannot distinguish a definite pre-commit failure from accepted-then-expired content after a crash. The sender can deliberately send a new message instead. No server tombstone, accepted-ID registry, client clock authority, reload or timer-rescue architecture was introduced.

Focused materialization test passed and full baseline security gate `{GATE}` is SUCCESS on `{HEAD}`. Build 0.9.6.25 earns its allocated 0.5 point, making the weighted ledger **70.0/100 (70%)**. Next allocated build is **0.9.6.26 multi-device expiry convergence foundation**. Live Firebase and `htest` remain untouched.''')
append('hermes-memory.txt',f'''### 0.9.6.25 FAIL-CLOSED REPLAY DECISION — USER APPROVED
User explicitly approved fail-closed handling for the rare Firestore-accepted/browser-crash-before-observation ambiguity. Persist a local Outbox `sendAttempted` marker before the cloud write. After restart, authoritative absence of an attempted row must never auto-replay; show/retain it as failed so the sender may deliberately create a new message. Never solve this with a per-message server tombstone or accepted-ID registry. Never let client time authorize the decision. Full gate `{GATE}` passed. 0.9.6.25 is REPOSITORY-VALIDATED; weighted completion 70.0/100; next build 0.9.6.26.''')
append('DISAPPEARING-PURGE-AUTHORITY.md','''### Fail-closed replay boundary (0.9.6.25)
Before any direct/group cloud send, the existing local Outbox owner durably marks the record `sendAttempted:true`. This is local pending-send state, not a deletion tombstone. On reconnect, an attempted ID absent from an authoritative server read is not eligible for automatic replay, because it may have been accepted and subsequently physically purged while the device was away. This closes resurrection without retaining a server accepted-ID/deletion registry. A deliberate user resend creates a new message ID.''')
append('architecture-ownership.txt','''0.9.6.25 replay ownership: app.js remains the sole IndexedDB/Outbox mutation owner and writes the local send-attempt marker before cloud transmission. disappearing-reconnect-recovery.js remains a pure decision owner. firebase.js remains the sole client server-read/write owner. Ambiguous attempted+authoritatively-absent work fails closed; no new persistence owner or server tombstone exists.''')
append('RUNTIME-AUTHORITY-MAP.md','''### 0.9.6.25 reconnect fail-closed authority
Outbox attempt state is owned and mutated only by `app.js`; authoritative source presence/absence is read only through `firebase.js`; `disappearing-reconnect-recovery.js` only plans accepted/purge/replay/blocked IDs. Automatic replay requires both authoritative server absence and `sendAttempted !== true` plus no prior server-backed observation. Attempted+absent is blocked/failed, never replayed automatically.''')
append('README.md',f'''### 0.9.6.25 fail-closed reconnect checkpoint
The restart/reconnect anti-resurrection slice is repository-validated. FIDUNIO now persists a local Outbox send-attempt marker before direct/group cloud transmission and refuses automatic replay when an attempted ID is later absent from authoritative Firestore, preventing the rare crash/expiry sequence from resurrecting disappearing content without retaining server tombstones. Full baseline gate `{GATE}` passed. Weighted first-rebuild completion is **70%**; next allocated build is 0.9.6.26 multi-device expiry convergence. Live Firebase and `htest` were not changed.''')
