from pathlib import Path
RUN='34067021824'; SHA='31dac2c0b551429a5a4ba7cf7c967e6316e9a9e6'
p=Path('FIDUNIO-BUILD-CHECKLIST.md');s=p.read_text().replace('- 0.9.9.6 and later allocated builds: **0.0 earned so far**.\n- **Current total: 95.5 / 100.0, reported as 96%.**\n\nThis 95.5-point ledger is authoritative until another allocated build earns points or a validated item regresses.','- 0.9.9.6 atomic deployment to `htest` is validated: **+0.5 earned**.\n- 0.9.9.7 and later allocated builds: **0.0 earned so far**.\n- **Current total: 96.0 / 100.0, reported as 96%.**\n\nThis 96.0-point ledger is authoritative until another allocated build earns points or a validated item regresses.')
s=s.replace('| **0.9.9.6** | **CURRENT — Atomic deployment to `htest`.** Deploy only the coherent 1.0 release candidate, not incremental slices. | htest source/version exactly matches gated candidate. | CURRENT |',f'| **0.9.9.6** | **Atomic deployment to `htest`.** Coherent candidate commit `{SHA}` was gated and deployed atomically as the `htest` branch. | Full gate `{RUN}` SUCCESS; `htest` points exactly to `{SHA}` with runtime 0.9.9.6. | REPOSITORY-VALIDATED |')
s=s.replace('| **0.9.9.7** | **User-device acceptance pass.** iPhone + iPad + two-account/two-device + offline/reconnect + disappearing + attachments + invitation/install + recovery proof. Fire HD constraints verified where applicable. | User/device acceptance recorded; recovery item can leave `BLOCKED — USER DEVICE PROOF`. | PLANNED |','| **0.9.9.7** | **CURRENT — User-device acceptance pass.** iPhone + iPad + two-account/two-device + offline/reconnect + disappearing + attachments + invitation/install + recovery proof. Fire HD constraints verified where applicable. | User/device acceptance recorded; recovery item can leave `BLOCKED — USER DEVICE PROOF`. | BLOCKED — USER DEVICE PROOF |')
p.write_text(s)
p=Path('README.md');s=p.read_text().replace('- Current checkpoint version: **0.9.9.5**','- Current checkpoint version: **0.9.9.6**').replace('Exactly **95.5 / 100.0 weighted product points (reported as 96%)**','Exactly **96.0 / 100.0 weighted product points (reported as 96%)**');s+=f'''\n\n### 0.9.9.6 — atomic `htest` candidate deployment\n\nRuntime version advanced 0.9.9.5 -> 0.9.9.6 solely to materialize the deployment candidate. Full Rebuild Baseline Security Gate **{RUN}** completed SUCCESS on commit `{SHA}`. The `htest` branch was then created directly at that exact commit, so the deployed test source and version are identical to the gated candidate. No live Firebase configuration, rules, Functions, App Check enforcement or production branch was changed.\n\nThe next checkpoint is 0.9.9.7 and is intentionally **BLOCKED — USER DEVICE PROOF** until real iPhone/iPad/two-account/offline/disappearing/attachment/invitation/install/recovery acceptance is performed.\n''';p.write_text(s)
append=f'''\n\n## 0.9.9.6 htest deployment checkpoint — 2026-09-06\nFull gate {RUN} SUCCESS on exact candidate {SHA}; htest branch created at that exact SHA with runtime 0.9.9.6. Weighted ledger 96.0/100. 0.9.9.7 is now CURRENT but BLOCKED — USER DEVICE PROOF. Do not award 0.9.9.7, run 0.9.9.8 stabilization, or claim 0.9.9.9 promotion readiness without actual device acceptance evidence. Live Firebase remains untouched.\n'''
for fn in ['hermes-memory.txt','CURRENT-REBUILD.md','hermes-setup.txt','BUG-LIST.md']:
 p=Path(fn);p.write_text(p.read_text()+append)
