from pathlib import Path
import json
p=Path('firebase.js');s=p.read_text()
s=s.replace("import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-functions.js`)]).then(([appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk])=>({appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk}))", "import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-functions.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-storage.js`)]).then(([appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk,storageSdk])=>({appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk,storageSdk}))")
s=s.replace("const {appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk}=await loadSdk();", "const {appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk,storageSdk}=await loadSdk();")
s=s.replace("const auth=authSdk.getAuth(app),db=fsSdk.getFirestore(app),functions=functionsSdk.getFunctions(app,\"us-central1\");services={app,appCheck,auth,db,functions,authSdk,fsSdk,functionsSdk};", "const auth=authSdk.getAuth(app),db=fsSdk.getFirestore(app),functions=functionsSdk.getFunctions(app,\"us-central1\"),storage=storageSdk.getStorage(app);services={app,appCheck,auth,db,functions,storage,authSdk,fsSdk,functionsSdk,storageSdk};")
s += '''\nexport async function uploadEncryptedAttachment({paths,manifest,chunks}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");if(!paths?.manifest||!Array.isArray(paths.chunks)||paths.chunks.length!==chunks?.length)throw new Error("Invalid attachment upload plan.");const enc=new TextEncoder();await s.storageSdk.uploadBytes(s.storageSdk.ref(s.storage,paths.manifest),enc.encode(JSON.stringify(manifest)),{contentType:"application/json",customMetadata:{fidunioFormat:"attachment-v1"}});for(let i=0;i<chunks.length;i++)await s.storageSdk.uploadBytes(s.storageSdk.ref(s.storage,paths.chunks[i]),enc.encode(JSON.stringify(chunks[i])),{contentType:"application/octet-stream",customMetadata:{fidunioFormat:"attachment-v1-ciphertext"}});return true;}\n'''
p.write_text(s)

p=Path('app.js');s=p.read_text()
s=s.replace('  readCloudGroupMessageIdsFromServer\n} from "./firebase.js";', '  readCloudGroupMessageIdsFromServer,\n  uploadEncryptedAttachment\n} from "./firebase.js";')
s=s.replace('import { DISAPPEARING_COMPOSE_PRESETS, composeDisappearLabel, stampOutgoingDisappearSelection } from "./disappearing-compose-policy.js";', 'import { DISAPPEARING_COMPOSE_PRESETS, composeDisappearLabel, stampOutgoingDisappearSelection } from "./disappearing-compose-policy.js";\nimport { createAttachmentSendService } from "./attachment-send-service.js";')
s=s.replace('${toolButton("photo","Photo")}${toolButton("file","File")}\n          ${toolButton("voice","Voice")}${toolButton("location","Location")}', '${toolButton("photo","Photo")}${toolButton("file","File")}\n          ${toolButton("voice","Audio")}${toolButton("video","Video")}')
s=s.replace('  document.querySelectorAll(".tool").forEach(btn=>btn.onclick=()=>alert(`${btn.textContent.trim()} is a UX placeholder in FIDUNIO ${FIDUNIO_VERSION}.`));', '''  document.querySelectorAll(".tool").forEach(btn=>btn.onclick=()=>{const label=btn.textContent.trim();const map={Photo:["photo","image/*",true],File:["file","*/*",false],Audio:["audio","audio/*",true],Video:["video","video/*",true]};if(map[label])return chooseAndSendAttachment(...map[label]);alert(`${label} is a UX placeholder in FIDUNIO ${FIDUNIO_VERSION}.`);});''')
anchor='async function sendCurrent(){'
helper='''async function chooseAndSendAttachment(kind,accept,capture){\n  const c=currentConversation();if(!firebaseUser||(!c?.cloud&&!c?.cloudGroup))return alert("Attachments require a signed-in cloud conversation.");\n  const input=document.createElement("input");input.type="file";input.accept=accept;if(capture)input.setAttribute("capture",kind==="audio"?"user":"environment");\n  input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const bytes=new Uint8Array(await file.arrayBuffer());const descriptor={kind,name:file.name||`${kind}-${Date.now()}`,type:file.type||"application/octet-stream",size:file.size,bytes,uid:firebaseUser.uid,conversationId:String(c.id),recipientUid:c.peerUid||null,groupId:c.cloudGroup?String(c.id):null,disappearAfterSeconds:state.settings.disappearingTextSeconds??null};let stagedMessage=null;const svc=createAttachmentSendService({stageEncryptedOutbox:async row=>{const text=JSON.stringify({fidunioAttachment:1,attachmentId:row.attachmentId,kind:row.attachmentKind,name:row.manifest.name,type:row.manifest.type,size:row.manifest.size,key:row.attachmentKey,storagePaths:row.storagePaths});stagedMessage=stampOutgoingDisappearSelection({id:row.messageId,mine:true,text,time:nowTime(),state:"sending",cloud:true,attachment:{kind:row.attachmentKind,name:row.manifest.name,type:row.manifest.type,size:row.manifest.size}},row.disappearAfterSeconds);if(!state.messages[c.id])state.messages[c.id]=[];state.messages[c.id].push(stagedMessage);if(c.cloudGroup)await queueGroupTextForApp({groupId:c.id,messageId:row.messageId,text,time:stagedMessage.time,disappearAfterSeconds:row.disappearAfterSeconds,persistEncryptedOutbox:persistGroupOutboxPayload});else await queueOutboxMessage(c.id,stagedMessage);await persistState();render();},uploadEncryptedAttachment,commitAttachmentMessage:async()=>{await flushQueuedAfterAuthoritativeReconcile();},removeEncryptedOutbox:async()=>{}});await svc.send(descriptor);}catch(err){alert("Attachment could not be sent: "+(err?.message||err));}};input.click();\n}\n\n'''
if anchor not in s: raise SystemExit('sendCurrent anchor missing')
s=s.replace(anchor,helper+anchor)
p.write_text(s)

pkg=json.loads(Path('package.json').read_text());pkg['scripts']['test:attachment-send-service']='node attachment-send-service.test.mjs';pkg['scripts']['test:attachment-ui-wiring']='node attachment-ui-wiring.test.mjs';Path('package.json').write_text(json.dumps(pkg,separators=(',',':'))+'\n')
Path('attachment-ui-wiring.test.mjs').write_text('''import fs from "node:fs";const s=fs.readFileSync("app.js","utf8"),f=fs.readFileSync("firebase.js","utf8"),r=fs.readFileSync("storage.rules","utf8");let bad=0;const ok=(n,v)=>{console.log(v?"PASS":"FAIL",n);if(!v)bad++};for(const [k,label] of [["photo","Photo"],["file","File"],["audio","Audio"],["video","Video"]])ok(label+" picker wired",s.includes(`["${k}"`)||s.includes(`"${k}",`));ok("single Firebase Storage owner",f.includes("firebase-storage.js")&&f.includes("uploadEncryptedAttachment"));ok("Storage denies client delete",r.includes("allow delete: if false"));ok("app sends through encrypted attachment owner",s.includes("createAttachmentSendService"));if(bad)process.exitCode=1;\n''')
Path('version.js').write_text('globalThis.FIDUNIO_RELEASE = Object.freeze({ version: "0.9.7.4" });\n')
