from pathlib import Path

def read(path): return Path(path).read_text()
def write(path,s): Path(path).write_text(s)
def replace_once(path,old,new):
    s=read(path)
    if old not in s: raise SystemExit(f"Missing expected anchor in {path}: {old[:220]!r}")
    write(path,s.replace(old,new,1))

replace_once('firebase.js',
'export async function writeCloudGroupHistoryGrantCopies({groupId,grantId,copies}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),id=String(grantId||"").trim(),rows=Array.isArray(copies)?copies:[];if(!gid||!id||!rows.length)throw new Error("History grant copies are required.");if(rows.length>100)throw new Error("History grant copy chunk exceeds 100 records.");const [groupSnap,grantSnap]=await Promise.all([s.fsSdk.getDoc(s.fsSdk.doc(s.db,"groups",gid)),s.fsSdk.getDoc(s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id))]);if(!groupSnap.exists()||!grantSnap.exists())throw new Error("History grant authority is unavailable.");const g=groupSnap.data(),grant=grantSnap.data();if(!Array.isArray(g.adminUids)||!g.adminUids.includes(authUser.uid)||grant.grantorUid!==authUser.uid||grant.status!=="building"||!Array.isArray(g.memberUids)||!g.memberUids.includes(grant.targetUid))throw new Error("History grant is no longer writable.");const batch=s.fsSdk.writeBatch(s.db);let writes=0;for(const row of rows){const sourceId=String(row?.sourceMessageId||"").trim();if(!sourceId)throw new Error("History source message ID is required.");const ref=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id,"messages",sourceId),snap=await s.fsSdk.getDoc(ref);if(snap.exists())continue;batch.set(ref,{...row,createdAt:s.fsSdk.serverTimestamp()});writes++;}if(writes)await batch.commit();return{written:writes};}',
'export async function writeCloudGroupHistoryGrantCopies({groupId,grantId,copies}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),id=String(grantId||"").trim(),rows=Array.isArray(copies)?copies:[];if(!gid||!id||!rows.length)throw new Error("History grant copies are required.");if(rows.length>100)throw new Error("History grant copy chunk exceeds 100 records.");const groupRef=s.fsSdk.doc(s.db,"groups",gid),grantRef=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id);const [groupSnap,grantSnap]=await Promise.all([s.fsSdk.getDoc(groupRef),s.fsSdk.getDoc(grantRef)]);if(!groupSnap.exists()||!grantSnap.exists())throw new Error("History grant authority is unavailable.");const g=groupSnap.data(),grant=grantSnap.data();if(!Array.isArray(g.adminUids)||!g.adminUids.includes(authUser.uid)||grant.grantorUid!==authUser.uid||grant.status!=="building"||!Array.isArray(g.memberUids)||!g.memberUids.includes(grant.targetUid))throw new Error("History grant is no longer writable.");const batch=s.fsSdk.writeBatch(s.db);let writes=0;const now=s.fsSdk.serverTimestamp();for(const row of rows){const sourceId=String(row?.sourceMessageId||"").trim();if(!sourceId)throw new Error("History source message ID is required.");const ref=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id,"messages",sourceId),snap=await s.fsSdk.getDoc(ref);if(snap.exists())continue;batch.set(ref,{...row,createdAt:now});writes++;}if(writes){batch.update(groupRef,{updatedAt:now});await batch.commit();}return{written:writes};}')

replace_once('firestore.rules',
'        match /messages/{messageId}{allow get,list: if isGroupMember(groupId)&&(isGroupAdmin(groupId)||(historyGrant(groupId,grantId).data.targetUid==request.auth.uid&&historyGrant(groupId,grantId).data.status=="active"));allow create: if isGroupAdmin(groupId)&&validHistoryGrantCopy(groupId,grantId,messageId,request.resource.data);allow update,delete: if false;}',
'        match /messages/{messageId}{allow get,list: if isGroupMember(groupId)&&(isGroupAdmin(groupId)||(historyGrant(groupId,grantId).data.targetUid==request.auth.uid&&historyGrant(groupId,grantId).data.status=="active"));allow create: if isGroupAdmin(groupId)&&validHistoryGrantCopy(groupId,grantId,messageId,request.resource.data)&&historyGrantBarrier(groupId);allow update,delete: if false;}')

replace_once('firestore-group-e2ee-v1.rules.test.mjs',
'await test("27 admin writes bounded history copy while building",()=>assertSucceeds(setDoc(doc(dbA,"groups","g1","historyGrants","hg1","messages","m1"),grantCopy())));',
'await test("27a standalone history copy without basis-visible group touch denied",()=>assertFails(setDoc(doc(dbA,"groups","g1","historyGrants","hg1","messages","m1"),grantCopy())));\nawait test("27 admin writes bounded history copy with group barrier while building",async()=>{const b=writeBatch(dbA);b.update(doc(dbA,"groups","g1"),{updatedAt:serverTimestamp()});b.set(doc(dbA,"groups","g1","historyGrants","hg1","messages","m1"),grantCopy());return assertSucceeds(b.commit());});')

print('0.9.6.18 history-copy purge barrier materialized')
