from pathlib import Path
import json
# auth gate routes invitation operations through one owner
p=Path('auth-ui-clean.js');s=p.read_text();s=s.replace('  validateInvitation,\n  redeemFidunioInvitation,\n','');needle='import {markSuccessfulAuthBypass} from "./local-security.js";';s=s.replace(needle,'import {validateFidunioInvitation,redeemInvitationForEnrollment} from "./invitation-owner.js";\n'+needle);s=s.replace('await validateInvitation(token)','await validateFidunioInvitation(token)').replace('await redeemFidunioInvitation(token,','await redeemInvitationForEnrollment(token,');p.write_text(s)
# settings invitation mutations/reads route through same owner; install gets its own predefined host
p=Path('settings-lifecycle.js');s=p.read_text();s=s.replace('  createFidunioInvitation,\n','').replace('  listPendingFidunioInvitations,\n  revokeFidunioInvitation\n','');needle='import { getAccountE2EELifecycleState';s=s.replace(needle,'import {createInvitationForEnrollment,listPendingInvitationsForAdmin,revokeInvitationForAdmin} from "./invitation-owner.js";\nimport {mountInstallGuidance} from "./install-guidance.js";\n'+needle);s=s.replace('return listPendingFidunioInvitations();','return listPendingInvitationsForAdmin();').replace('return revokeFidunioInvitation(id);','return revokeInvitationForAdmin(id);').replace('()=>createFidunioInvitation(','()=>createInvitationForEnrollment(')
s=s.replace('{id:"invites",label:"Invitations",icon:"✉︎",subtitle:"Create and manage FIDUNIO invitations."},','{id:"invites",label:"Invitations",icon:"✉︎",subtitle:"Create and manage FIDUNIO invitations."},\n  {id:"install",label:"Install",icon:"▣",subtitle:"Optional browser and Home Screen installation guidance."},')
s=s.replace('const PANEL_ORDER=["profile","general","privacy","encryption","users","invites","data","about"];','const PANEL_ORDER=["profile","general","privacy","encryption","users","invites","install","data","about"];')
s=s.replace('  placeBaseCards(settings,shell);\n  hydrateAccountPanels(g,shell);','  placeBaseCards(settings,shell);\n  mountInstallGuidance(host(shell,"install"));\n  hydrateAccountPanels(g,shell);');p.write_text(s)
# client policy is shared with repository invite primitives without moving Firebase ownership
p=Path('firebase.js');s=p.read_text();s=s.replace('import { normalizeDisappearSelection } from "./disappearing-content-policy.js";','import { normalizeDisappearSelection } from "./disappearing-content-policy.js";\nimport {assertInvitationUsable,normalizeInvitationRole,canIssueInvitation} from "./invitation-policy.js";');s=s.replace('if(data.status!=="pending")throw new Error(data.status==="accepted"?"This invitation has already been used.":"This invitation is no longer active.");if(expires&&expires.getTime()<=Date.now())throw new Error("This invitation has expired.");','assertInvitationUsable({status:data.status,expiresAt:expires,now:Date.now()});');s=s.replace('if(!["owner","admin"].includes(access.role))throw new Error("Only a FIDUNIO Owner or Admin can issue invitations.");if(!["user","admin"].includes(role))throw new Error("Invitation role must be User or Admin.");','if(!canIssueInvitation(access.role))throw new Error("Only a FIDUNIO Owner or Admin can issue invitations.");role=normalizeInvitationRole(role);');p.write_text(s)
# package gates
p=Path('package.json');pkg=json.loads(p.read_text());pkg['scripts'].update({'test:invitation-policy':'node invitation-policy.test.mjs','emulator:test:invitation-rules':'firebase emulators:exec --only firestore --project demo-fidunio-invitation-rules "node firestore-invitation.rules.test.mjs"','test:invitation-install-closeout':'node invitation-install-closeout.test.mjs'});p.write_text(json.dumps(pkg,separators=(',',':'))+'\n')
Path('version.js').write_text('globalThis.FIDUNIO_RELEASE = Object.freeze({ version: "0.9.8.5" });\n')
