from pathlib import Path
GATE='34061730677'
HEAD='b3086fb894b2e9d904264300b60c04a68668f3dc'
def rep(path,old,new):
 p=Path(path);s=p.read_text()
 if old not in s: raise SystemExit('missing doc anchor '+path+' '+old[:80])
 p.write_text(s.replace(old,new,1))
def append(path,text):
 p=Path(path);s=p.read_text();t=text.strip()
 if t not in s:p.write_text(s.rstrip()+'\n\n'+t+'\n')

rep('FIDUNIO-BUILD-CHECKLIST.md','- 0.9.6.25 is materialized and its full repository gate is green, but its crash-window exit criterion is unresolved: **0.0 / 0.5 earned**.\n- 0.9.6.26 and later allocated builds: **0.0 earned so far**.\n- **Current total: 69.5 / 100.0, reported as 70%.**\n\nThis 69.5-point ledger (70% normal status) is authoritative until another allocated build earns points or a validated item regresses.','- 0.9.6.25 is repository-validated after the user-approved fail-closed replay resolution: **+0.5 earned**.\n- 0.9.6.26 multi-device expiry convergence is repository-validated: **+1.0 earned**.\n- 0.9.6.27 disappearing-text settings/UI wiring is repository-validated: **+1.0 earned**.\n- 0.9.6.28 and later allocated builds: **0.0 earned so far**.\n- **Current total: 72.0 / 100.0, reported as 72%.**\n\nThis 72.0-point ledger is authoritative until another allocated build earns points or a validated item regresses.')
old='| **0.9.6.25** | **Restart/reconnect stale-client anti-resurrection proof.** Cloud/group Outbox replay now performs explicit Firestore server reads first. Server-present IDs are treated as accepted and their stale Outbox row is removed; prior-server-backed disappearing IDs that are authoritatively absent are physically purged before retry; only never-server-backed absent work may replay. **Unresolved:** a crash after Firestore accepts a send but before local/server-observation state is durably recorded is indistinguishable after later server purge from truly never-sent work without some durable anti-replay authority. | Planner/integration gate plus full baseline `34060082292` SUCCESS for the implemented replay barrier. Build exit remains incomplete until the post-commit/pre-observation crash window is resolved without violating trace-free purge/no-tombstone requirements. | IN PROGRESS |'
new='| **0.9.6.25** | **Restart/reconnect stale-client anti-resurrection proof.** Local Outbox records are durably marked `sendAttempted:true` before direct/group cloud transmission. Authoritative absence of an attempted row fails closed and never auto-replays; sender may deliberately create a new message. No server tombstone/accepted-ID registry. | Focused replay barrier + full baseline `34060880885` SUCCESS; post-commit/pre-observation ambiguity closed conservatively. | REPOSITORY-VALIDATED |'
rep('FIDUNIO-BUILD-CHECKLIST.md',old,new)
rep('FIDUNIO-BUILD-CHECKLIST.md','| **0.9.6.26** | **CURRENT — Multi-device expiry convergence foundation.** Define and test same-UID device behavior after server purge; each device independently converges local traces to authoritative absence without installation-local lifetime authority. | Repository multi-device simulation proves both devices converge and neither can resurrect source/Outbox/history. | CURRENT |','| **0.9.6.26** | **Multi-device expiry convergence foundation.** Same-UID installations independently converge server-backed disappearing message state, encrypted history and Outbox traces after authoritative source absence. Cache-only/local absence remains non-authoritative. | Permanent multi-device simulation proves both devices independently purge source/history/Outbox and neither can replay; full gate `'+GATE+'` SUCCESS. | REPOSITORY-VALIDATED |')
rep('FIDUNIO-BUILD-CHECKLIST.md','| **0.9.6.27** | **Disappearing text settings/UI wiring.** Expose user-selected duration for direct/group text messages using existing immutable outer `disappearAfterSeconds`; show effective policy before send; do not redesign established chat layout. | UI/controller tests prove selected duration reaches direct/group send paths and already-sent message duration remains immutable. | PLANNED |','| **0.9.6.27** | **Disappearing text settings/UI wiring.** Composer exposes Off / 5 minutes / 1 hour / 1 day / 7 days through one persisted preference. Each new direct/group message snapshots the selected immutable outer `disappearAfterSeconds`; later preference changes cannot alter sent rows. | Pure compose-policy + app source wiring gate proves direct/group propagation and immutable prior-message metadata; full gate `'+GATE+'` SUCCESS. | REPOSITORY-VALIDATED |')
rep('FIDUNIO-BUILD-CHECKLIST.md','| **0.9.6.28** | **Disappearing text end-to-end security closeout.**','| **0.9.6.28** | **CURRENT — Disappearing text end-to-end security closeout.**')

rep('README.md','- Current checkpoint version: **0.9.6.22**\n- Current weighted FIDUNIO 1.0 completion: **68%**','- Current checkpoint version: **0.9.6.27**\n- Current weighted FIDUNIO 1.0 completion: **72%**')
append('README.md',f'''### 0.9.6.26 + 0.9.6.27 combined build pass
Per user instruction these two pre-allocated checkpoints were built in one continuous pass while retaining separate exit criteria. 0.9.6.26 adds permanent same-UID multi-device disappearance convergence proof: independent installations converge source/history/Outbox traces only from authoritative server absence, and stale attempted Outbox work cannot resurrect a purged source. 0.9.6.27 adds the user-facing disappearing-text selection (Off, 5 minutes, 1 hour, 1 day, 7 days) directly at the composer and snapshots that choice into each new direct/group message's immutable `disappearAfterSeconds`. Changing the preference later does not alter already-sent messages. Runtime version advanced 0.9.6.25 -> 0.9.6.27 because both allocated builds completed together. Full Rebuild Baseline Security Gate `{GATE}` passed on `{HEAD}`. Both are REPOSITORY-VALIDATED; weighted completion is **72%**. No live Firebase or `htest` change.''')
append('CURRENT-REBUILD.md',f'''### Combined 0.9.6.26 / 0.9.6.27 pass — REPOSITORY-VALIDATED
0.9.6.26 proves same-UID installations independently converge a server-backed disappearing message after authoritative source purge: live projection, encrypted history and matching encrypted Outbox traces are removed on each device, while cache-only absence cannot authorize purge and attempted stale Outbox work cannot replay. 0.9.6.27 adds one persisted future-message duration preference and compact composer control. The pure compose owner normalizes Off/5m/1h/1d/7d; `app.js` snapshots the selection into a newly created message and propagates it through both direct and group encrypted Outbox/send paths. Already-sent message metadata is not rewritten when the preference changes. Full gate `{GATE}` SUCCESS on `{HEAD}`. Runtime 0.9.6.27. Weighted completion **72.0/100**. Next allocated build: **0.9.6.28 disappearing text end-to-end security closeout**. Live Firebase and `htest` untouched.''')
append('hermes-memory.txt',f'''### 0.9.6.26 + 0.9.6.27 COMBINED PASS — REPOSITORY-VALIDATED
User authorized building the two separately allocated checkpoints in one pass. 0.9.6.26 permanently gates same-UID independent-device expiry convergence and anti-replay. 0.9.6.27 exposes a compact composer duration selector (Off/5m/1h/1d/7d) and snapshots the normalized choice into each new direct/group message's immutable outer `disappearAfterSeconds`; preference changes affect only future messages. Full gate `{GATE}` passed. Runtime 0.9.6.27; weighted completion 72%; next 0.9.6.28. No live Firebase/htest.''')
append('DISAPPEARING-PURGE-AUTHORITY.md','''### 0.9.6.26 multi-device convergence
Same-UID installations do not share a device-local expiry authority. Each independently treats authoritative server source absence plus its own prior server-backed observation as the convergence signal, then physically removes its local projection/history/Outbox traces through the existing local owner. Cache-only absence cannot purge and attempted stale Outbox state cannot resurrect the source.''')
append('RUNTIME-AUTHORITY-MAP.md','''### 0.9.6.27 disappearing compose selection
`disappearing-compose-policy.js` is pure normalization/presentation policy only. `app.js` owns the persisted user selection and snapshots it when constructing a new outgoing row. Existing direct/group Outbox and message owners carry the immutable `disappearAfterSeconds`; no UI preference becomes expiry or purge authority.''')
append('architecture-ownership.txt','''0.9.6.26-27: multi-device convergence introduces no cross-device local owner; each installation converges only from server-backed authority through existing projection/purge owners. `disappearing-compose-policy.js` owns only pure compose selection normalization/labels. `app.js` owns the persisted future-message preference and stamps new rows; message/Outbox/Firebase owners remain unchanged.''')
