from pathlib import Path
p=Path('FIDUNIO-BUILD-CHECKLIST.md');s=p.read_text()
s=s.replace('- 0.9.6.24 and later allocated builds: **0.0 earned so far**.\n- **Current total: 69.0 / 100.0 = 69%.**\n\nThis 69% is the authoritative 1.0 completion figure until another allocated build earns points or a validated item regresses.','- 0.9.6.24 is repository-validated: **+0.5 earned**.\n- 0.9.6.25 and later allocated builds: **0.0 earned so far**.\n- **Current total: 69.5 / 100.0, reported as 70%.**\n\nThis 69.5-point ledger (70% normal status) is authoritative until another allocated build earns points or a validated item regresses.')
s=s.replace('| **0.9.6.24** | **CURRENT — bounded group-purge transaction write limit.** Close the known 0.9.6.20 omission before further anti-resurrection work: compute every receipt delete, source-linked history-copy delete, empty-grant delete, retained-grant update and final source delete before scheduling transaction writes; fail closed above one conservative repository maximum with `PURGE_TRACE_TOO_LARGE`. No chunked source-first deletion, tombstone, or client delete authority. | Exact-boundary commit succeeds; boundary+1 throws `PURGE_TRACE_TOO_LARGE` before any transaction write is scheduled; unrelated traces remain untouched; full baseline gate green. | CURRENT |','| **0.9.6.24** | **Bounded group-purge transaction write limit.** The server repository computes every receipt delete, source-linked history-copy delete, empty-grant delete, retained-grant update and final source delete before scheduling writes; a conservative maximum of 400 writes fails closed with `PURGE_TRACE_TOO_LARGE`. No chunked source-first deletion, tombstone, or client delete authority. | Exact 400-write boundary succeeds; 401 writes throws `PURGE_TRACE_TOO_LARGE` before any transaction write is scheduled; full gate `34059468538` SUCCESS. | REPOSITORY-VALIDATED |')
s=s.replace('| **0.9.6.25** | **Restart/reconnect stale-client anti-resurrection proof.**','| **0.9.6.25** | **CURRENT — Restart/reconnect stale-client anti-resurrection proof.**')
s=s.replace('| Cold-start, offline->online, stale snapshot and duplicate retry tests green; no `location.reload()`/timer rescue. | PLANNED |','| Cold-start, offline->online, stale snapshot and duplicate retry tests green; no `location.reload()`/timer rescue. | CURRENT |',1)
p.write_text(s)
note='''\n\n### 0.9.6.24 bounded group-purge transaction writes\nThe known 0.9.6.20 write-limit omission is closed. `disappearing-purge-firestore-admin-adapter.mjs` now computes the complete group purge transaction write count before scheduling any mutation and caps it at 400. Exactly 400 writes are accepted; 401 fails closed with `PURGE_TRACE_TOO_LARGE` and zero scheduled writes. Oversized traces remain intact for a future safe lease/chunk design; there is no source-first chunking, tombstone, browser delete permission, or live Firebase change. Full baseline security gate `34059468538` passed. Runtime version is 0.9.6.24. Weighted ledger is 69.5/100, reported as **70%**. Next allocated build is 0.9.6.25 restart/reconnect stale-client anti-resurrection proof.\n'''
for name in ['README.md','hermes-memory.txt','CURRENT-REBUILD.md','DISAPPEARING-PURGE-AUTHORITY.md']:
 q=Path(name);t=q.read_text();marker='### 0.9.6.24 bounded group-purge transaction writes'
 if marker not in t:q.write_text(t.rstrip()+note+'\n')
print('0.9.6.24 docs closed')
