from pathlib import Path

def rep(path,old,new):
 p=Path(path);s=p.read_text()
 if old not in s: raise SystemExit('missing anchor '+path+' '+old[:60])
 p.write_text(s.replace(old,new,1))

rep('app.js','import { planReconnectOutboxConvergence } from "./disappearing-reconnect-recovery.js";','import { planReconnectOutboxConvergence } from "./disappearing-reconnect-recovery.js";\nimport { DISAPPEARING_COMPOSE_PRESETS, composeDisappearLabel, stampOutgoingDisappearSelection } from "./disappearing-compose-policy.js";')
rep('app.js','settings:{previews:false,autoLock:true,textSize:"normal",wifiAttachments:true,appearance:"auto"},','settings:{previews:false,autoLock:true,textSize:"normal",wifiAttachments:true,appearance:"auto",disappearingTextSeconds:null},')
rep('app.js','''        <div class="quick-row">${state.quickPhrases.map(q=>`<button class="quick-chip" data-quick="${esc(q)}">${esc(q)}</button>`).join("")}</div>\n        <div class="compose-line">''','''        <div class="quick-row">${state.quickPhrases.map(q=>`<button class="quick-chip" data-quick="${esc(q)}">${esc(q)}</button>`).join("")}</div>\n        <div class="small-note" style="display:flex;align-items:center;gap:8px;margin:0 4px 6px"><label for="disappearSelect">Disappearing:</label><select id="disappearSelect" aria-label="Disappearing message duration">${DISAPPEARING_COMPOSE_PRESETS.map(p=>`<option value="${p.value??"off"}" ${(state.settings.disappearingTextSeconds??null)===p.value?"selected":""}>${esc(p.label)}</option>`).join("")}</select><span>${esc(composeDisappearLabel(state.settings.disappearingTextSeconds))}</span></div>\n        <div class="compose-line">''')
rep('app.js','''  document.querySelector("#moreBtn").onclick=()=>{state.toolsOpen=!state.toolsOpen;render()};''','''  document.querySelector("#moreBtn").onclick=()=>{state.toolsOpen=!state.toolsOpen;render()};\n  const disappearSelect=document.querySelector("#disappearSelect");\n  if(disappearSelect)disappearSelect.onchange=()=>{state.settings.disappearingTextSeconds=disappearSelect.value==="off"?null:Number(disappearSelect.value);persistSoon();render();};''')
rep('app.js','''  const m={\n    id:crypto.randomUUID(),\n    mine:true,\n    text,\n    time:nowTime(),\n    state:(state.online && (!cloud || firebaseUser))?"sending":"queued",\n    cloud\n  };''','''  const m=stampOutgoingDisappearSelection({\n    id:crypto.randomUUID(),\n    mine:true,\n    text,\n    time:nowTime(),\n    state:(state.online && (!cloud || firebaseUser))?"sending":"queued",\n    cloud\n  },state.settings.disappearingTextSeconds);''')
rep('app.js','''await queueGroupTextForApp({groupId:conversationId,messageId:m.id,text,time:m.time,persistEncryptedOutbox:persistGroupOutboxPayload});''','''await queueGroupTextForApp({groupId:conversationId,messageId:m.id,text,time:m.time,disappearAfterSeconds:m.disappearAfterSeconds??null,persistEncryptedOutbox:persistGroupOutboxPayload});''')
Path('version.js').write_text('globalThis.FIDUNIO_RELEASE = Object.freeze({version: "0.9.6.27"});\n')
print('materialized 0.9.6.26 + 0.9.6.27')
