from pathlib import Path
RUN='34066875377'
# checklist
p=Path('FIDUNIO-BUILD-CHECKLIST.md');s=p.read_text()
s=s.replace('- 0.9.9.0 and later allocated builds: **0.0 earned so far**.\n- **Current total: 91.0 / 100.0, reported as 91%.**\n\nThis 91.0-point ledger is authoritative until another allocated build earns points or a validated item regresses.','- 0.9.9.0 Group Info completion is repository-validated: **+1.0 earned**.\n- 0.9.9.1 Direct Chat Info completion is repository-validated: **+0.5 earned**.\n- 0.9.9.2 prototype/simulation cleanup is repository-validated: **+0.5 earned**.\n- 0.9.9.3 responsive/lifecycle regression hardening is repository-validated: **+1.0 earned**.\n- 0.9.9.4 complete 1.0 repository candidate gate is repository-validated: **+1.0 earned**.\n- 0.9.9.5 final docs/setup/package reconciliation is repository-validated: **+0.5 earned**.\n- 0.9.9.6 and later allocated builds: **0.0 earned so far**.\n- **Current total: 95.5 / 100.0, reported as 96%.**\n\nThis 95.5-point ledger is authoritative until another allocated build earns points or a validated item regresses.')
repls={
'| **0.9.9.0** | **CURRENT — Group Info completion.** Integrate earlier-history controls from 0.9.6.29, remove obsolete placeholders, and finish tablet landscape layout without redesigning established two-pane behavior. | Group Info functional + responsive tests green. | CURRENT |':f'| **0.9.9.0** | **Group Info completion.** Earlier-history controls retained; unsupported placeholders removed; landscape tablet workspace completed without changing the established pane owner. | Candidate UI/lifecycle gate + full baseline `{RUN}` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.9.1** | **Direct Chat Info completion.** Replace remaining placeholder behavior with supported real actions or remove unsupported controls deliberately. | No Direct Chat Info placeholder actions remain. | PLANNED |':f'| **0.9.9.1** | **Direct Chat Info completion.** Real cloud direct-chat security info retained; unsupported local-only placeholder action removed. | Candidate UI/lifecycle gate + full baseline `{RUN}` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.9.2** | **Prototype/simulation cleanup.** Remove remaining test banners, simulated local message-state timers and tool-button alert placeholders only after their real replacements exist. | Search/runtime gates prove no forbidden simulation owner remains. | PLANNED |':f'| **0.9.9.2** | **Prototype/simulation cleanup.** Test banner, simulated local Sent/Delivered/Read timers, and unsupported tool placeholders removed; legacy local-only transport fails closed. | Candidate UI/lifecycle gate + full baseline `{RUN}` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.9.3** | **Responsive/lifecycle regression hardening.** Verify iPhone single-pane + prominent Back/wrap, iPad/tablet/desktop two-pane, Group Info landscape, Settings lifecycle, rotation/resize and live receipts. | Repository UI/lifecycle gates green with no observer/timer/reload rescue architecture. | PLANNED |':f'| **0.9.9.3** | **Responsive/lifecycle regression hardening.** Group Info joins the established responsive route owner; protected phone/tablet structures and deliberate receipt recovery remain intact. | Candidate UI/lifecycle, runtime-authority and receipt gates + full baseline `{RUN}` SUCCESS. Real-device acceptance remains 0.9.9.7. | REPOSITORY-VALIDATED |',
'| **0.9.9.4** | **Complete 1.0 repository candidate gate.** Run all rules, E2EE, recovery, groups, disappearing content, attachments, invitations/install, offline and runtime authority tests as one coherent candidate. | Every required 1.0 repository gate green. FCM 1.1 and App Check enforcement 1.2 excluded. | PLANNED |':f'| **0.9.9.4** | **Complete 1.0 repository candidate gate.** All required repository rules/E2EE/recovery/group/disappearing/attachment/invitation/offline/runtime/UI gates run together. | Full Rebuild Baseline Security Gate `{RUN}` SUCCESS. FCM 1.1 and App Check enforcement 1.2 excluded. | REPOSITORY-VALIDATED |',
'| **0.9.9.5** | **Final documentation/setup/package reconciliation.** Update cumulative README/memory/checklist/setup, remove temporary one-shot files/workflows, verify protected config exclusion, prepare one coherent candidate package/checkpoint. | Docs match executable source; no temporary materializers; protected configs untouched. | PLANNED |':f'| **0.9.9.5** | **Final documentation/setup/package reconciliation.** Cumulative recovery docs reconciled to candidate; one-shot implementation helpers removed; protected configs remain excluded from release authority. | Docs/source reconcile against full gate `{RUN}` SUCCESS; coherent candidate checkpoint ready for `htest`. | REPOSITORY-VALIDATED |',
'| **0.9.9.6** | **Atomic deployment to `htest`.** Deploy only the coherent 1.0 release candidate, not incremental slices. | htest source/version exactly matches gated candidate. | PLANNED |':'| **0.9.9.6** | **CURRENT — Atomic deployment to `htest`.** Deploy only the coherent 1.0 release candidate, not incremental slices. | htest source/version exactly matches gated candidate. | CURRENT |'}
for a,b in repls.items():
 if a not in s: raise SystemExit('checklist anchor missing '+a[:30])
 s=s.replace(a,b)
p.write_text(s)

# README
p=Path('README.md');s=p.read_text().replace('- Current checkpoint version: **0.9.8.5**','- Current checkpoint version: **0.9.9.5**').replace('- Current weighted FIDUNIO 1.0 completion: **91%**','- Current weighted FIDUNIO 1.0 completion: **96%**').replace('Exactly **91.0 / 100.0 weighted product points (reported as 91%)**','Exactly **95.5 / 100.0 weighted product points (reported as 96%)**')
s += f'''\n\n### 0.9.9.0-0.9.9.5 — repository release-candidate closeout\n\nGroup Info now uses the established tablet-responsive secondary-screen owner, including the previously deferred landscape treatment, while retaining the validated earlier-history grant controls. Direct Chat Info exposes only real cloud security information; unsupported local-only placeholder behavior was removed. Prototype test banners, fake local receipt timers, and unsupported Contact/Checklist/Schedule/Saved tool alerts were retired; legacy local-only transport now fails closed instead of manufacturing delivery states.\n\nThe permanent `release-candidate-ui.test.mjs` gate protects these decisions alongside the existing runtime, receipt, Settings, attachment, invitation, disappearing-content, group, recovery and E2EE gates. Full Rebuild Baseline Security Gate **{RUN}** completed SUCCESS on the clean candidate source. 0.9.9.5 reconciles cumulative documentation and prepares the coherent candidate for one atomic `htest` deployment. Live Firebase remains untouched; real iPhone/iPad acceptance remains a separate 0.9.9.7 requirement.\n'''
p.write_text(s)

append=f'''\n\n## 0.9.9.0-0.9.9.5 repository candidate checkpoint — 2026-09-06\nGroup Info landscape/responsive completion, real Direct Chat Info-only behavior, prototype/simulation retirement and responsive/lifecycle hardening are repository-validated. Permanent candidate UI/lifecycle coverage is in the normal baseline. Full gate {RUN} SUCCESS. Runtime checkpoint 0.9.9.5. Weighted ledger 95.5/100 (reported 96%). Next: 0.9.9.6 atomic htest deployment. Do not claim 0.9.9.7 device acceptance until the user actually tests iPhone/iPad/two-account/offline/disappearing/attachments/invitation/install/recovery. Live Firebase is still not to be changed.\n'''
for fn in ['hermes-memory.txt','CURRENT-REBUILD.md','DETERMINISTIC-UI-LIFECYCLE.md','RUNTIME-AUTHORITY-MAP.md','architecture-ownership.txt','BUG-LIST.md','hermes-setup.txt']:
 p=Path(fn);p.write_text(p.read_text()+append)
