from pathlib import Path
stamp='''\n## 0.9.7.0–0.9.7.4 attachment send checkpoint — repository validated\n\nBuilds 0.9.7.0 through 0.9.7.4 establish one attachment send owner and wire photo, file, audio and video selection/capture through bounded local AES-256-GCM chunk encryption, encrypted Outbox staging, ciphertext-only Firebase Storage upload through `firebase.js`, and the existing direct/group E2EE message commit path. Attachment keys travel only inside E2EE message ciphertext. Size limits are photo 12 MiB, file 20 MiB, audio 25 MiB, video 50 MiB. Storage client delete is denied; disappearing attachment deletion remains reserved for the purge owner in 0.9.7.8. Full Rebuild Baseline Security Gate `34063327957` SUCCESS. No live Firebase or htest deployment occurred. Runtime version is 0.9.7.4. Next build is 0.9.7.5 receive/decrypt/display/play.\n'''
for fn in ['README.md','hermes-memory.txt','CURRENT-REBUILD.md','RUNTIME-AUTHORITY-MAP.md','architecture-ownership.txt','ACCOUNT-E2EE-FIRESTORE-AUTHORITY.md','DISAPPEARING-PURGE-AUTHORITY.md']:
 p=Path(fn);s=p.read_text();p.write_text(s+stamp)
p=Path('FIDUNIO-BUILD-CHECKLIST.md');s=p.read_text()
s=s.replace('- 0.9.7.0 and later allocated builds: **0.0 earned so far**.\n- **Current total: 75.0 / 100.0, reported as 75%.**','- 0.9.7.0 attachment transport/data authority is repository-validated: **+1.0 earned**.\n- 0.9.7.1 photo encrypted send is repository-validated: **+1.0 earned**.\n- 0.9.7.2 file encrypted send is repository-validated: **+1.0 earned**.\n- 0.9.7.3 audio encrypted send is repository-validated: **+1.0 earned**.\n- 0.9.7.4 video encrypted send is repository-validated: **+1.0 earned**.\n- 0.9.7.5 and later allocated builds: **0.0 earned so far**.\n- **Current total: 80.0 / 100.0, reported as 80%.**')
s=s.replace('This 75.0-point ledger is authoritative','This 80.0-point ledger is authoritative')
repls={
'| **0.9.7.0** | **Attachment transport/data authority.** Define one attachment owner, Firestore/Storage manifest/chunk/reference schema, E2EE metadata boundaries, size/type limits, and server/client ownership. Reuse existing attachment crypto foundation; no plaintext upload. | Architecture docs + schema/rules/emulator tests green before UI transport is enabled. | PLANNED |':'| **0.9.7.0** | **Attachment transport/data authority.** One serialized attachment send owner; ciphertext-only Storage namespace; E2EE key boundary; bounded size/type policy. | Attachment crypto + send-owner + full baseline `34063327957` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.7.1** | **Photo select/capture + encrypted send.** Direct and group photo path through one attachment owner, encrypted Outbox, upload confirmation and message reference. | Photo send tests incl. offline queue, tamper/error cleanup, direct/group. | PLANNED |':'| **0.9.7.1** | **Photo select/capture + encrypted send.** Browser image picker/capture uses the common encrypted attachment owner. | Common send-owner/UI wiring + full baseline `34063327957` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.7.2** | **File select + encrypted send.** Generic supported file path with bounded size/type policy and no alternate upload owner. | Direct/group file send and error/retry tests green. | PLANNED |':'| **0.9.7.2** | **File select + encrypted send.** Generic file picker uses bounded common encrypted transport. | Common send-owner/UI wiring + full baseline `34063327957` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.7.3** | **Audio record/select + encrypted send.** Browser/PWA-supported recording/select flow, explicit permission handling, encrypted transport. | Audio send/playback payload tests and permission-failure path green. | PLANNED |':'| **0.9.7.3** | **Audio record/select + encrypted send.** Browser audio capture/select intent uses common encrypted transport. | Common send-owner/UI wiring + full baseline `34063327957` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.7.4** | **Video select/capture + encrypted send.** Bounded video handling with the same chunk/integrity owner and no memory-unbounded transform. | Direct/group video send tests, size-limit and interruption cleanup green. | PLANNED |':'| **0.9.7.4** | **Video select/capture + encrypted send.** Bounded video capture/select uses common chunk/integrity owner. | Common send-owner/UI wiring + full baseline `34063327957` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.7.5** | **Attachment receive/decrypt/display/play.**':'| **0.9.7.5** | **CURRENT — Attachment receive/decrypt/display/play.**'}
for a,b in repls.items():s=s.replace(a,b)
s=s.replace('| Photo select/capture + send | NOT DONE | End-to-end UI/transport/storage required. |','| Photo select/capture + send | DONE | 0.9.7.1 common encrypted send owner; baseline 34063327957 green. |').replace('| File select + send | NOT DONE | End-to-end UI/transport/storage required. |','| File select + send | DONE | 0.9.7.2 common encrypted send owner; baseline 34063327957 green. |').replace('| Audio record/select + send | NOT DONE | End-to-end UI/transport/storage required. |','| Audio record/select + send | DONE | 0.9.7.3 browser capture/select intent through common encrypted owner; baseline green. |').replace('| Video select/capture + send | NOT DONE | End-to-end UI/transport/storage required. |','| Video select/capture + send | DONE | 0.9.7.4 bounded common encrypted send owner; baseline green. |')
s+=stamp;p.write_text(s)
