from pathlib import Path
GATE='34065528714'
stamp='''\n## 0.9.8.0–0.9.8.5 invitation/install checkpoint — repository validated\n\nRuntime 0.9.8.5 completes the invitation/join/install phase. `invitation-owner.js` is the sole serialized invitation mutation coordinator while `firebase.js` remains the sole Firebase repository/SDK owner. Pure `invitation-policy.js` enforces single-use lifecycle, issuer roles and target roles. Auth and Settings request invitation work through that owner. Firestore emulator coverage proves anonymous validation of a known token, unauthorized issuance/revocation denial, owner issuance/revocation, atomic accepted-invitation + active-profile enrollment, and second-redemption denial. Joined active profiles flow into existing direct/group discovery without device binding.\n\n`install-guidance.js` owns only an optional predefined Settings Install panel. It never mutates invitation, account, messaging or service-worker state and never uses automatic install prompting. iOS uses Safari Share -> Add to Home Screen; Android/Fire and desktop use browser-provided install/add/shortcut commands when available. The rejected 0.9.4.12–0.9.4.15 invite/install logic was not restored or adapted. Protected iPhone Back/wrap, Settings deterministic ownership and two-pane architecture remain gated. Full Rebuild Baseline Security Gate `34065528714` SUCCESS. No live Firebase or htest deployment occurred. Next allocated build: 0.9.9.0 Group Info completion.\n'''
# README: repair stale current header and append checkpoint
p=Path('README.md');s=p.read_text();s=s.replace('## Current version: 0.9.6.13','## Current version: 0.9.8.5');p.write_text(s+stamp)
# cumulative/current/architecture docs
for fn in ['hermes-memory.txt','CURRENT-REBUILD.md','RUNTIME-AUTHORITY-MAP.md','architecture-ownership.txt','DETERMINISTIC-UI-LIFECYCLE.md','RUNTIME-TRANSFORM-INVENTORY.md','ACCOUNT-E2EE-FIRESTORE-AUTHORITY.md','FIRESTORE-E2EE-V1-RULES.md','FIRESTORE-E2EE-V1-EMULATOR-TESTS.md','BUG-LIST.md']:
 p=Path(fn);p.write_text(p.read_text()+stamp)
# setup current checkpoint repair
p=Path('hermes-setup.txt');s=p.read_text();import re;s=re.sub(r'- Current repository checkpoint: .*', '- Current repository checkpoint: 0.9.8.5; invitation-only enrollment and independent safe install guidance are repository-validated; next allocated build is 0.9.9.0 Group Info completion.', s, count=1);p.write_text(s+stamp)
# quick start adds install guidance without coupling it to invitation redemption
p=Path('quick-start.html');s=p.read_text();insert='''<section class="card"><h2>Optional: add FIDUNIO to your Home Screen</h2><p>Installation is separate from accepting an invitation or signing in.</p><ol><li>On iPhone or iPad, open FIDUNIO in Safari, tap Share, then choose <strong>Add to Home Screen</strong>.</li><li>On Android or Fire, use your browser menu and choose <strong>Add to Home screen</strong> or <strong>Install app</strong> when offered.</li><li>On desktop, use the browser's Install app or Create shortcut command when offered.</li></ol></section>''';s=s.replace('</main>',insert+'</main>');p.write_text(s)
# checklist ledger and roadmap
p=Path('FIDUNIO-BUILD-CHECKLIST.md');s=p.read_text();old='''- 0.9.8.0 and later allocated builds: **0.0 earned so far**.\n- **Current total: 85.0 / 100.0, reported as 85%.**\n\nThis 85.0-point ledger is authoritative until another allocated build earns points or a validated item regresses.''';new='''- 0.9.8.0 invitation deterministic-owner rebuild is repository-validated: **+1.0 earned**.\n- 0.9.8.1 invitation create/send/use/join is repository-validated: **+1.0 earned**.\n- 0.9.8.2 invitation account/conversation association is repository-validated: **+1.0 earned**.\n- 0.9.8.3 safe install-to-Home-Screen owner is repository-validated: **+1.0 earned**.\n- 0.9.8.4 invite/install coexistence regression gate is repository-validated: **+1.0 earned**.\n- 0.9.8.5 account/invitation/install phase closeout is repository-validated: **+1.0 earned**.\n- 0.9.9.0 and later allocated builds: **0.0 earned so far**.\n- **Current total: 91.0 / 100.0, reported as 91%.**\n\nThis 91.0-point ledger is authoritative until another allocated build earns points or a validated item regresses.''';
if old not in s: raise SystemExit('ledger anchor missing');s=s.replace(old,new)
rows={
'| **0.9.8.0** | **CURRENT — Invitation deterministic-owner rebuild.** Re-audit current invitation code and establish one serialized invitation owner/write path; do not adapt rejected 0.9.4.12-.15 invite-install logic. | Architecture/rules tests green before changing install behavior. | CURRENT |':'| **0.9.8.0** | **Invitation deterministic-owner rebuild.** `invitation-owner.js` is the sole serialized invitation mutation coordinator; Firebase remains repository owner; rejected 0.9.4.12-.15 logic not reused. | Policy/ownership + full baseline `34065528714` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.8.1** | **Invitation create/send/use/join end-to-end.** Owner/Admin issue invitation; recipient validates/redeems; account/profile enrollment is real Firebase-backed behavior. | Happy path + used/revoked/expired/role/unauthorized tests green. | PLANNED |':'| **0.9.8.1** | **Invitation create/send/use/join end-to-end.** Owner/Admin issue; recipient validates/redeems; enrollment atomically associates accepted invite and active profile. | Policy + Firestore emulator invitation matrix + full baseline `34065528714` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.8.2** | **Invitation account/conversation association.** Joined user appears correctly to permitted contacts/groups without prototype identity or manual device binding. | Cross-account conversation/group discovery tests green. | PLANNED |':'| **0.9.8.2** | **Invitation account/conversation association.** Joined active profile enters established UID/account-authoritative direct/group discovery; no device binding. | Source/closeout association gate + full baseline `34065528714` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.8.3** | **Safe install-to-Home-Screen owner.** Build install guidance independently from invitation redemption; preserve manifest/icons/service-worker foundation and browser-specific supported paths. | Install flow cannot mutate invitation/account state; iPhone/iPad/desktop support paths documented/tested. | PLANNED |':'| **0.9.8.3** | **Safe install-to-Home-Screen owner.** Independent Settings Install guidance; no auto prompt or invitation/account mutation. | iOS/Android-Fire/desktop guidance + manifest/icon/source gate + full baseline `34065528714` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.8.4** | **Invite + install coexistence regression gate.** Specifically reproduce the historical bug class where automatic icon/install behavior broke Settings/two-pane behavior, and prove the new architecture cannot do so. | Two-pane Settings, iPhone back/wrap and invitation flows remain green with install code present. | PLANNED |':'| **0.9.8.4** | **Invite + install coexistence regression gate.** Install owner is state-independent; automatic install path absent; protected Settings/two-pane/iPhone assets remain intact. | Permanent coexistence source gate + full baseline `34065528714` SUCCESS. | REPOSITORY-VALIDATED |',
'| **0.9.8.5** | **Account/invitation/install phase closeout.** Reconcile account creation/sign-in/sign-out/recovery, invitation-only enrollment and install guidance. | Complete repository gate green; no rejected historical implementation restored. | PLANNED |':'| **0.9.8.5** | **Account/invitation/install phase closeout.** Invitation-only enrollment, existing account lifecycle/recovery and independent install guidance reconciled. | Complete baseline `34065528714` SUCCESS; rejected historical implementation absent. | REPOSITORY-VALIDATED |',
'| **0.9.9.0** | **Group Info completion.**':'| **0.9.9.0** | **CURRENT — Group Info completion.**'}
for a,b in rows.items():
 if a not in s: raise SystemExit('roadmap anchor missing '+a[:30]);s=s.replace(a,b)
s+=stamp;p.write_text(s)
