import fs from "node:fs";
import assert from "node:assert/strict";
const firebase=fs.readFileSync("firebase.js","utf8");
const settings=fs.readFileSync("settings-lifecycle.js","utf8");
const rules=fs.readFileSync("firestore.rules","utf8");
const service=fs.readFileSync("account-deletion-service.js","utf8");
const finalizer=fs.readFileSync("account-deletion-finalize-client.js","utf8");
const functions=fs.readFileSync("functions/index.mjs","utf8");
const accountStorage=fs.readFileSync("account-storage.js","utf8");
const localSecurity=fs.readFileSync("local-security.js","utf8");
for(const name of ["requestFidunioAccountDeletion","getFidunioAccountDeletionRequest","cancelFidunioAccountDeletionRequest","listFidunioAccountDeletionRequestsForAdmin","markFidunioAccountDeletionCleanupComplete","listMyCloudGroupsForAccountDeletion","listMyCloudConversationsForAccountDeletion"])assert.match(firebase,new RegExp(name));
assert.match(settings,/Delete My Account/);
assert.match(settings,/within 7 days/);
assert.match(settings,/verifyLocalPin/);
assert.match(settings,/Current password/);
assert.match(settings,/Account Deletion Requests/);
assert.match(settings,/prepareSelfAccountDeletion/);
assert.match(service,/ACCOUNT_OWNS_GROUPS/);
assert.match(service,/deleteCloudMyMessagesForEveryone/);
assert.match(service,/leaveAccountGroup/);
assert.match(service,/markFidunioAccountDeletionCleanupComplete/);
assert.match(service,/deletesOwnedGroupsAutomatically:false/);
assert.match(service,/rekeysGroupsOnLeave:true/);
assert.match(rules,/match \/accountDeletionRequests\/\{uid\}/);
assert.match(rules,/validAccountDeletionRequestCreate/);
assert.match(rules,/resource\.data\.cleanupStatus=="required".*status=="cancelled"/);
assert.match(finalizer,/completeMyAccountDeletionV1/);
assert.match(finalizer,/eraseAccountStorageForDeletion/);
assert.match(finalizer,/clearLocalSecurityForAccountDeletion/);
assert.match(accountStorage,/eraseAccountStorageForDeletion/);
assert.match(localSecurity,/clearLocalSecurityForAccountDeletion/);
assert.match(functions,/completeMyAccountDeletionV1/);
assert.match(functions,/createAccountDeletionCore/);
console.log("PASS: self-service account deletion is wired end-to-end with reauthentication, irreversible cleanup barrier, server deletion, Auth deletion and local purge");
