import {getFirebaseUser,getCloudUserDevices,deactivateOtherCloudE2EEDevices} from "./firebase.js";

const LIVE_DB="fidunio-local";
const KEEP_META=new Set(["local-key","local-security-v1","e2ee-device-keypair-v1","e2ee-device-identity-v1"]);
const OBSOLETE_VAULTS=["fidunio-account-vault","fidunio-account-vault-v2","fidunio-account-vault-v3"];
function req(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error("Transaction aborted"));});}
function openExisting(name){return new Promise((resolve,reject)=>{const r=indexedDB.open(name);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function existingDbNames(){if(typeof indexedDB.databases!=="function")throw new Error("This cleanup requires browser database enumeration so it cannot accidentally create a missing database.");return new Set((await indexedDB.databases()).map(x=>x.name).filter(Boolean));}
async function readCurrentIdentity(){const names=await existingDbNames();if(!names.has(LIVE_DB))throw new Error("FIDUNIO live database was not found.");const db=await openExisting(LIVE_DB);try{if(!db.objectStoreNames.contains("meta"))throw new Error("FIDUNIO meta store was not found.");const tx=db.transaction("meta","readonly"),store=tx.objectStore("meta");const [identity,keypair]=await Promise.all([req(store.get("e2ee-device-identity-v1")),req(store.get("e2ee-device-keypair-v1"))]);await txDone(tx);if(!identity?.deviceId||!keypair?.privateKey||!keypair?.publicKey)throw new Error("Current E2EE identity is incomplete. Cleanup stopped without changing anything.");return identity;}finally{db.close();}}
async function cleanLiveTestData(){const db=await openExisting(LIVE_DB);try{const stores=[...db.objectStoreNames];const writable=stores.filter(n=>n==="meta"||n==="outbox"||n==="history");if(!writable.length)return;const tx=db.transaction(writable,"readwrite");for(const name of writable){const store=tx.objectStore(name);if(name!=="meta"){store.clear();continue;}const keys=await req(store.getAllKeys());for(const key of keys){if(!KEEP_META.has(String(key)))store.delete(key);}}await txDone(tx);}finally{db.close();}}
function deleteDb(name){return new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(name);r.onsuccess=resolve;r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error(`Close other FIDUNIO tabs, then retry cleanup: ${name} is open.`));});}
export async function inspectBaselineCleanup(){const user=getFirebaseUser();if(!user)throw new Error("Sign in to FIDUNIO first.");const identity=await readCurrentIdentity();const devices=await getCloudUserDevices(user.uid);const names=await existingDbNames();return{uid:user.uid,deviceId:identity.deviceId,staleActiveDevices:devices.filter(d=>d.active!==false&&d.deviceId!==identity.deviceId).length,vaults:OBSOLETE_VAULTS.filter(n=>names.has(n))};}
export async function executeBaselineCleanup(expectedDeviceId){const user=getFirebaseUser();if(!user)throw new Error("Sign in to FIDUNIO first.");const identity=await readCurrentIdentity();if(identity.deviceId!==expectedDeviceId)throw new Error("Device identity changed since inspection. Cleanup cancelled.");const cloud=await deactivateOtherCloudE2EEDevices(user.uid,identity.deviceId);await cleanLiveTestData();const names=await existingDbNames();for(const name of OBSOLETE_VAULTS){if(names.has(name))await deleteDb(name);}return{deviceId:identity.deviceId,deactivated:cloud.deactivated};}
