import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {disappearingPurgeVersionForOutgoing,stampOutgoingDisappearSelection} from "./disappearing-compose-policy.js";
const descriptor=JSON.stringify({fidunioAttachment:1,attachmentId:"a1",kind:"photo"});
const stamped=stampOutgoingDisappearSelection({id:"m1",text:descriptor},300);
assert.equal(stamped.disappearAfterSeconds,300);
assert.equal(stamped.disappearingPurgeVersion,1);
assert.equal(disappearingPurgeVersionForOutgoing({text:descriptor,value:300}),1);
const app=readFileSync("app.js","utf8"),adapter=readFileSync("disappearing-purge-firestore-admin-adapter.mjs","utf8"),fn=readFileSync("functions/index.mjs","utf8"),handoff=readFileSync("att.txt","utf8"),sw=readFileSync("service-worker.js","utf8");
assert.match(app,/Disappearing:/);
assert.match(app,/releaseAttachmentResult\(runtime\.result\)/);
assert.match(app,/attachmentRuntime\.delete\(key\)/);
assert.match(adapter,/sameBasis\(current\.basis,expected\).*deleteAttachmentStorageTraces/s);
assert.match(adapter,/bucket\.deleteFiles\(\{prefix,force:true\}\)/);
assert.match(adapter,/storageBeforeSource:true/);
assert.match(fn,/const attachmentBucket=getStorage\(\)\.bucket\(ATTACHMENT_BUCKET\)/);
assert.match(fn,/createDisappearingPurgeFirestoreAdminRepository\(\{db,bucket:attachmentBucket,requireStorage:true\}\)/);
assert.match(handoff,/CODEBASE="recovery"/);
assert.match(handoff,/FUNCTION="purgeDisappearingMessagesV1"/);
assert.match(handoff,/firebase deploy --project "\$PROJECT" --only "functions:\$CODEBASE:\$FUNCTION" --non-interactive/);
assert.match(handoff,/roles\/storage\.objectAdmin/);
assert.match(sw,/SHELL_REVISION="0\.9\.9\.19-disappearing-attachments"/);
console.log("Disappearing attachment activation wiring gate passed");
