import assert from "node:assert/strict";
import {createDisappearingPurgeFirestoreAdminRepository,MAX_GROUP_PURGE_TRANSACTION_WRITES,DISAPPEARING_PURGE_FIRESTORE_V1} from "./disappearing-purge-firestore-admin-adapter.mjs";
function version(n){return{seconds:n,nanoseconds:0};}
class Snap{constructor(ref,data,ver){this.ref=ref;this._data=data;this.exists=data!==undefined;this.updateTime=this.exists?version(ver):null;}data(){return this._data;}}
class Ref{constructor(db,path){this.db=db;this.path=path;}async get(){return this.db.snap(this.path);}collection(name){return new Collection(this.db,`${this.path}/${name}`);}}
class Collection{constructor(db,path){this.db=db;this.path=path;}async get(){return this.db.query(this.path);}}
class FakeDb{constructor(seed){this.rows=new Map();this.versions=new Map();this.scheduledWrites=0;this.committedWrites=0;for(const [p,d,v] of seed){this.rows.set(p,d);this.versions.set(p,v);}}doc(p){return new Ref(this,p);}snap(p){return new Snap(this.doc(p),this.rows.get(p),this.versions.get(p)||0);}query(path){const prefix=`${path}/`,docs=[];for(const [p] of this.rows)if(p.startsWith(prefix)&&!p.slice(prefix.length).includes("/"))docs.push(this.snap(p));return{docs};}async runTransaction(work){const writes=[];const tx={get:t=>Promise.resolve(t instanceof Collection?this.query(t.path):this.snap(t.path)),delete:r=>{this.scheduledWrites++;writes.push(["delete",r]);},update:(r,p)=>{this.scheduledWrites++;writes.push(["update",r,p]);}};const result=await work(tx);this.committedWrites=writes.length;return result;}}
function seed(receipts){const rows=[["groups/g",{memberUids:["a","b"],keyEpoch:1},1],["groups/g/messages/m",{senderUid:"a",keyEpoch:1,disappearAfterSeconds:60},2],["groups/g/epochs/1",{memberKeyIds:{a:"ka",b:"kb"}},3]];for(let i=0;i<receipts;i++)rows.push([`groups/g/messages/m/receipts/u${i}`,{uid:`u${i}`,state:"read"},10+i]);return rows;}
async function stateAndRepo(receipts){const db=new FakeDb(seed(receipts)),repo=createDisappearingPurgeFirestoreAdminRepository({db});const state=await repo.readGroupPurgeState({groupId:"g",messageId:"m"});return{db,repo,state};}
assert.equal(MAX_GROUP_PURGE_TRANSACTION_WRITES,400);
let x=await stateAndRepo(MAX_GROUP_PURGE_TRANSACTION_WRITES-1);let result=await x.repo.commitGroupPurge({groupId:"g",messageId:"m",expectedBasis:x.state.basis});assert.equal(result.traceCount,MAX_GROUP_PURGE_TRANSACTION_WRITES);assert.equal(x.db.committedWrites,MAX_GROUP_PURGE_TRANSACTION_WRITES);
x=await stateAndRepo(MAX_GROUP_PURGE_TRANSACTION_WRITES);await assert.rejects(()=>x.repo.commitGroupPurge({groupId:"g",messageId:"m",expectedBasis:x.state.basis}),e=>e?.code==="PURGE_TRACE_TOO_LARGE");assert.equal(x.db.scheduledWrites,0);assert.equal(x.db.committedWrites,0);
assert.equal(DISAPPEARING_PURGE_FIRESTORE_V1.maxGroupTransactionWrites,400);assert.equal(DISAPPEARING_PURGE_FIRESTORE_V1.oversizeErrorCode,"PURGE_TRACE_TOO_LARGE");
console.log("Group purge transaction write-bound gate passed");
