import { createRecoveryFirestoreAdminRepositories, RECOVERY_FIRESTORE_V1 } from "./e2ee-recovery-firestore-admin-adapter.mjs";

const rows=[];
async function test(name,fn){try{await fn();rows.push([name,true]);console.log("PASS",name);}catch(e){rows.push([name,false]);console.error("FAIL",name,e?.message||e);}}
async function expectFail(name,fn,code){await test(name,async()=>{try{await fn();throw new Error("unexpected success");}catch(e){if(e.message==="unexpected success")throw e;if(code&&e.code!==code)throw new Error(`expected ${code}, got ${e.code}`);}});}

function fakeFirestore(){
  const data=new Map();
  const snap=path=>({exists:data.has(path),data:()=>structuredClone(data.get(path))});
  const ref=path=>({path,async get(){return snap(path);}});
  const tx={
    async get(r){return snap(r.path);},
    set(r,value,options){if(options?.merge&&data.has(r.path))data.set(r.path,{...data.get(r.path),...structuredClone(value)});else data.set(r.path,structuredClone(value));},
    update(r,value){if(!data.has(r.path))throw new Error("missing");data.set(r.path,{...data.get(r.path),...structuredClone(value)});}
  };
  return{
    doc:path=>ref(path),
    async runTransaction(fn){return fn(tx);},
    seed(path,value){data.set(path,structuredClone(value));},
    read(path){return data.has(path)?structuredClone(data.get(path)):null;}
  };
}
const baseSession=()=>({sessionVersion:1,sessionId:"s1",uid:"u1",keyId:"k1",identityRevisionAtStart:3,status:"PENDING",createdAtMs:1000,expiresAtMs:601000,failedPinAttempts:0,failedSupplementalAttempts:0,authorizedAtMs:null,consumedAtMs:null});

await test("declares server-only recovery collections",()=>{if(RECOVERY_FIRESTORE_V1.sessionCollection!=="recoverySessions"||RECOVERY_FIRESTORE_V1.accountStateCollection!=="e2eeRecoveryState"||RECOVERY_FIRESTORE_V1.clientWritable!==false)throw new Error("bad collection contract");});
await test("identity repo reads durable account identity",async()=>{const db=fakeFirestore();db.seed("users/u1/e2ee/identity",{keyId:"k1",revision:3});const {identityRepo}=createRecoveryFirestoreAdminRepositories({db});const r=await identityRepo.readIdentity("u1");if(r.keyId!=="k1"||r.revision!==3)throw new Error("bad identity read");});
await test("missing account failure record reads zero",async()=>{const db=fakeFirestore();const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});if(await sessionRepo.readAccountFailureCount("u1")!==0)throw new Error("not zero");});
await test("createSession creates server-owned session once",async()=>{const db=fakeFirestore();const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.createSession(baseSession());if(db.read("recoverySessions/s1")?.uid!=="u1")throw new Error("not stored");});
await expectFail("duplicate session create denied",async()=>{const db=fakeFirestore();const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.createSession(baseSession());await sessionRepo.createSession(baseSession());},"SESSION_EXISTS");
await test("readSession returns stored session",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",baseSession());const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});if((await sessionRepo.readSession("s1")).keyId!=="k1")throw new Error("bad read");});
await test("failed PIN increments session and account atomically",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",baseSession());db.seed("e2eeRecoveryState/u1",{uid:"u1",consecutivePinFailures:2,hold:false});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});const next={...baseSession(),failedPinAttempts:1};await sessionRepo.saveFailedPinAttempt({session:next,accountConsecutivePinFailures:3,accountHold:false});if(db.read("recoverySessions/s1").failedPinAttempts!==1||db.read("e2eeRecoveryState/u1").consecutivePinFailures!==3)throw new Error("not atomic");});
await test("fifth failed PIN persists LOCKED",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",{...baseSession(),failedPinAttempts:4});db.seed("e2eeRecoveryState/u1",{uid:"u1",consecutivePinFailures:4,hold:false});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveFailedPinAttempt({session:{...baseSession(),failedPinAttempts:5,status:"LOCKED"},accountConsecutivePinFailures:5,accountHold:false});if(db.read("recoverySessions/s1").status!=="LOCKED")throw new Error("not locked");});
await test("tenth account failure persists hold",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",baseSession());db.seed("e2eeRecoveryState/u1",{uid:"u1",consecutivePinFailures:9,hold:false});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveFailedPinAttempt({session:{...baseSession(),failedPinAttempts:1},accountConsecutivePinFailures:10,accountHold:true});if(db.read("e2eeRecoveryState/u1").hold!==true)throw new Error("hold missing");});
await expectFail("stale session PIN counter update rejected",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",{...baseSession(),failedPinAttempts:2});db.seed("e2eeRecoveryState/u1",{uid:"u1",consecutivePinFailures:2});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveFailedPinAttempt({session:{...baseSession(),failedPinAttempts:1},accountConsecutivePinFailures:3,accountHold:false});},"SESSION_CONFLICT");
await expectFail("stale account PIN counter update rejected",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",baseSession());db.seed("e2eeRecoveryState/u1",{uid:"u1",consecutivePinFailures:5});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveFailedPinAttempt({session:{...baseSession(),failedPinAttempts:1},accountConsecutivePinFailures:3,accountHold:false});},"ACCOUNT_CONFLICT");
await expectFail("terminal session cannot record another PIN failure",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",{...baseSession(),status:"CONSUMED"});db.seed("e2eeRecoveryState/u1",{uid:"u1",consecutivePinFailures:0});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveFailedPinAttempt({session:{...baseSession(),status:"CONSUMED",failedPinAttempts:1},accountConsecutivePinFailures:1,accountHold:false});},"SESSION_CONFLICT");
await test("supplemental failure increments separate counter only",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",baseSession());const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveFailedSupplementalAttempt({...baseSession(),failedSupplementalAttempts:1});const s=db.read("recoverySessions/s1");if(s.failedSupplementalAttempts!==1||s.failedPinAttempts!==0)throw new Error("wrong counter");});
await expectFail("stale supplemental counter update rejected",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",{...baseSession(),failedSupplementalAttempts:1});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveFailedSupplementalAttempt({...baseSession(),failedSupplementalAttempts:1});},"SESSION_CONFLICT");
await test("authorization requires stored PENDING state",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",baseSession());const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveAuthorizedSession({...baseSession(),status:"AUTHORIZED",authorizedAtMs:2000});if(db.read("recoverySessions/s1").status!=="AUTHORIZED")throw new Error("not authorized");});
await expectFail("already authorized session cannot authorize twice",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",{...baseSession(),status:"AUTHORIZED",authorizedAtMs:2000});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveAuthorizedSession({...baseSession(),status:"AUTHORIZED",authorizedAtMs:3000});},"SESSION_CONFLICT");
await test("consume requires AUTHORIZED and resets account failures",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",{...baseSession(),status:"AUTHORIZED",authorizedAtMs:2000});db.seed("e2eeRecoveryState/u1",{uid:"u1",consecutivePinFailures:7,hold:false});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.consumeSession({session:{...baseSession(),status:"CONSUMED",authorizedAtMs:2000,consumedAtMs:3000},accountConsecutivePinFailures:0});if(db.read("recoverySessions/s1").status!=="CONSUMED"||db.read("e2eeRecoveryState/u1").consecutivePinFailures!==0)throw new Error("consume/reset failed");});
await expectFail("PENDING session cannot be consumed",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",baseSession());const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.consumeSession({session:{...baseSession(),status:"CONSUMED",consumedAtMs:3000},accountConsecutivePinFailures:0});},"SESSION_CONFLICT");
await expectFail("session immutable UID cannot change",async()=>{const db=fakeFirestore();db.seed("recoverySessions/s1",baseSession());db.seed("e2eeRecoveryState/u2",{uid:"u2",consecutivePinFailures:0});const {sessionRepo}=createRecoveryFirestoreAdminRepositories({db});await sessionRepo.saveFailedPinAttempt({session:{...baseSession(),uid:"u2",failedPinAttempts:1},accountConsecutivePinFailures:1,accountHold:false});},"SESSION_CONFLICT");

const failed=rows.filter(([,ok])=>!ok);console.log(`\n${rows.length-failed.length}/${rows.length} recovery Firestore persistence assertions passed.`);if(failed.length)process.exitCode=1;
