import { firebaseConfig } from "./firebase-config.js";

const SDK_VERSION="12.18.0";
export const FIDUNIO_RECAPTCHA_ENTERPRISE_SITE_KEY="6LfLaqstAAAAANNkEghVZ26a4vv8hXwC7KDI9rma";
let sdkPromise=null,services=null,authUser=null;
const messageStreams=new Map(),groupMessageStreams=new Map();
export function isFirebaseConfigured(){return firebaseConfig&&!String(firebaseConfig.apiKey||"").includes("PASTE_")&&!String(firebaseConfig.projectId||"").includes("PASTE_")&&!String(firebaseConfig.appId||"").includes("PASTE_");}
async function loadSdk(){if(sdkPromise)return sdkPromise;sdkPromise=Promise.all([import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-firestore.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-app-check.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-functions.js`)]).then(([appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk])=>({appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk}));return sdkPromise;}
async function ensureServices(){if(services)return services;if(!isFirebaseConfigured())throw new Error("Firebase is not configured yet.");const {appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk}=await loadSdk();const app=appSdk.initializeApp(firebaseConfig);const appCheck=appCheckSdk.initializeAppCheck(app,{provider:new appCheckSdk.ReCaptchaEnterpriseProvider(FIDUNIO_RECAPTCHA_ENTERPRISE_SITE_KEY),isTokenAutoRefreshEnabled:true});const auth=authSdk.getAuth(app),db=fsSdk.getFirestore(app),functions=functionsSdk.getFunctions(app,"us-central1");services={app,appCheck,auth,db,functions,authSdk,fsSdk,functionsSdk};return services;}
export async function initFirebase(onUserChanged){const s=await ensureServices();s.authSdk.onAuthStateChanged(s.auth,user=>{authUser=user||null;onUserChanged?.(authUser);});return s;}
export function getFirebaseUser(){return authUser;}
async function callRecoveryFunction(name,data={}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");return (await s.functionsSdk.httpsCallable(s.functions,name)(data)).data;}
export function enrollCloudE2EERecovery(data){return callRecoveryFunction("enrollRecoveryV1",data);}export function startCloudE2EERecovery(){return callRecoveryFunction("startE2EERecoveryV1",{});}export function completeCloudE2EERecovery(data){return callRecoveryFunction("completeE2EERecoveryV1",data);}
function normalizeInviteToken(token){return String(token||"").trim().replace(/\s+/g,"");}function bytesToUrlToken(bytes){let raw="";bytes.forEach(b=>raw+=String.fromCharCode(b));return btoa(raw).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}async function sha256Hex(text){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("");}async function inviteIdForToken(token){const clean=normalizeInviteToken(token);if(clean.length<20)throw new Error("Invitation code is incomplete.");return sha256Hex(clean);}function inviteLink(token){const url=new URL(globalThis.location?.href||"https://willyros01.github.io/hermes/");url.hash="";url.search="";url.searchParams.set("invite",token);return url.toString();}
export async function getFidunioAccessInfo(){const s=await ensureServices();if(!authUser)return{user:null,profile:null,system:null,role:null};const [p,y]=await Promise.all([s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",authUser.uid)),s.fsSdk.getDoc(s.fsSdk.doc(s.db,"system","access"))]);const profile=p.exists()?{uid:p.id,...p.data()}:null,system=y.exists()?y.data():null;return{user:authUser,profile,system,role:profile?.systemRole||null};}
export async function claimLegacyOwner(){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const pr=s.fsSdk.doc(s.db,"users",authUser.uid),sr=s.fsSdk.doc(s.db,"system","access"),p=await s.fsSdk.getDoc(pr);if(!p.exists())throw new Error("This account does not have an existing FIDUNIO profile.");if((await s.fsSdk.getDoc(sr)).exists())throw new Error("FIDUNIO already has an Owner.");const b=s.fsSdk.writeBatch(s.db);b.set(sr,{ownerUid:authUser.uid,createdByUid:authUser.uid,createdAt:s.fsSdk.serverTimestamp(),accessModel:"invite-only-v1"});b.update(pr,{systemRole:"owner"});await b.commit();return getFidunioAccessInfo();}
export async function validateInvitation(token){const s=await ensureServices(),clean=normalizeInviteToken(token),id=await inviteIdForToken(clean),snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"invitations",id));if(!snap.exists())throw new Error("This FIDUNIO invitation is not valid.");const d=snap.data(),expires=d.expiresAt?.toDate?.()||null;if(d.status!=="pending")throw new Error(d.status==="accepted"?"This invitation has already been used.":"This invitation is no longer active.");if(expires&&expires.getTime()<=Date.now())throw new Error("This invitation has expired.");return{id,token:clean,role:d.role||"user",invitedByUid:d.invitedByUid||"",invitedByName:d.invitedByName||"FIDUNIO administrator",expiresAt:expires,status:d.status};}
export async function createFidunioInvitation(role="user",days=7){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const a=await getFidunioAccessInfo();if(!["owner","admin"].includes(a.role))throw new Error("Only a FIDUNIO Owner or Admin can issue invitations.");const token=bytesToUrlToken(crypto.getRandomValues(new Uint8Array(24))),id=await inviteIdForToken(token),expires=new Date(Date.now()+Math.max(1,Math.min(30,Number(days)||7))*86400000);await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"invitations",id),{status:"pending",role,invitedByUid:authUser.uid,invitedByName:a.profile?.displayName||authUser.email||"FIDUNIO administrator",createdAt:s.fsSdk.serverTimestamp(),expiresAt:s.fsSdk.Timestamp.fromDate(expires),acceptedUid:null,acceptedAt:null,revokedAt:null});return{id,token,role,expiresAt:expires,link:inviteLink(token)};}
export async function redeemFidunioInvitation(token,email,password,displayName){const s=await ensureServices(),invite=await validateInvitation(token),name=String(displayName||"").trim(),mail=String(email||"").trim();if(!name||!mail)throw new Error("Display name and email are required.");let cred;try{cred=await s.authSdk.createUserWithEmailAndPassword(s.auth,mail,password);await s.authSdk.updateProfile(cred.user,{displayName:name});authUser=cred.user;const b=s.fsSdk.writeBatch(s.db);b.update(s.fsSdk.doc(s.db,"invitations",invite.id),{status:"accepted",acceptedUid:cred.user.uid,acceptedEmail:cred.user.email||mail,acceptedAt:s.fsSdk.serverTimestamp()});b.set(s.fsSdk.doc(s.db,"users",cred.user.uid),{displayName:name,email:cred.user.email||mail,systemRole:invite.role,joinedByInviteId:invite.id,invitedByUid:invite.invitedByUid,createdAt:s.fsSdk.serverTimestamp(),active:true});await b.commit();return cred.user;}catch(e){if(cred?.user)try{await s.authSdk.deleteUser(cred.user);}catch{}throw e;}}
export async function createFidunioAccount(){throw new Error("FIDUNIO account creation is invitation-only. Use a valid invitation link or code.");}export async function signInFidunio(email,password){const s=await ensureServices(),c=await s.authSdk.signInWithEmailAndPassword(s.auth,email,password),p=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",c.user.uid));if(!p.exists()){await s.authSdk.signOut(s.auth);throw new Error("This Firebase login is not enrolled in FIDUNIO. A valid invitation is required.");}authUser=c.user;return c.user;}export async function signOutFidunio(){const s=await ensureServices();await s.authSdk.signOut(s.auth);authUser=null;}export async function sendFidunioPasswordReset(email){const s=await ensureServices();await s.authSdk.sendPasswordResetEmail(s.auth,String(email||"").trim());}
export async function updateFidunioProfile(v={}){const s=await ensureServices(),u=s.auth.currentUser;if(!u)throw new Error("Sign in first.");const name=String(v.displayName||"").trim(),mail=String(v.email||"").trim();if(!name)throw new Error("Display name is required.");if(mail&&mail!==u.email){const c=s.authSdk.EmailAuthProvider.credential(u.email,v.currentPassword);await s.authSdk.reauthenticateWithCredential(u,c);await s.authSdk.updateEmail(u,mail);}await s.authSdk.updateProfile(u,{displayName:name,photoURL:String(v.photoURL||"").trim()||null});await s.fsSdk.updateDoc(s.fsSdk.doc(s.db,"users",u.uid),{displayName:name,email:u.email||mail,telephone:String(v.telephone||"").trim(),photoURL:String(v.photoURL||"").trim(),profileUpdatedAt:s.fsSdk.serverTimestamp()});return{uid:u.uid,displayName:u.displayName,email:u.email,photoURL:u.photoURL};}
export async function changeFidunioPassword(currentPassword,newPassword){const s=await ensureServices(),u=s.auth.currentUser;if(!u)throw new Error("Sign in first.");const c=s.authSdk.EmailAuthProvider.credential(u.email,currentPassword);await s.authSdk.reauthenticateWithCredential(u,c);await s.authSdk.updatePassword(u,newPassword);}export async function listFidunioUsersForAdmin(){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");return (await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"users"))).docs.map(d=>({uid:d.id,...d.data()}));}export async function updateFidunioUserLifecycle(uid,status,expiryDays){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const row={status,active:status==="active",adminUpdatedAt:s.fsSdk.serverTimestamp(),adminUpdatedByUid:authUser.uid};if(expiryDays!==undefined)row.expiresAt=expiryDays===null?null:s.fsSdk.Timestamp.fromDate(new Date(Date.now()+Number(expiryDays)*86400000));await s.fsSdk.updateDoc(s.fsSdk.doc(s.db,"users",uid),row);}export async function listPendingFidunioInvitations(){const s=await ensureServices();return (await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"invitations"))).docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.status==="pending");}export async function revokeFidunioInvitation(id){const s=await ensureServices();await s.fsSdk.updateDoc(s.fsSdk.doc(s.db,"invitations",id),{status:"revoked",revokedAt:s.fsSdk.serverTimestamp()});}
function dmId(a,b){return"dm_"+[a,b].sort().join("_");}export async function startDirectConversation(peerUid){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const p=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",peerUid));if(!p.exists())throw new Error("Recipient FIDUNIO ID was not found.");const id=dmId(authUser.uid,peerUid);await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"conversations",id),{type:"direct",members:[authUser.uid,peerUid],memberNames:{[authUser.uid]:authUser.displayName||"User",[peerUid]:p.data().displayName||"User"},updatedAt:s.fsSdk.serverTimestamp(),createdAt:s.fsSdk.serverTimestamp()},{merge:true});return{id,cloud:true,peerUid,name:p.data().displayName||"FIDUNIO contact"};}export async function getCloudUserProfile(uid){const s=await ensureServices(),x=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",uid));return x.exists()?{uid,...x.data()}:null;}export async function listCloudUsers(){const s=await ensureServices();return (await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"users"))).docs.map(d=>({uid:d.id,...d.data()})).filter(x=>x.uid!==authUser?.uid&&x.active!==false);}
export async function createCloudGroup(name,memberUids){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const members=[...new Set([authUser.uid,...memberUids])],ref=s.fsSdk.doc(s.fsSdk.collection(s.db,"groups")),b=s.fsSdk.writeBatch(s.db),now=s.fsSdk.serverTimestamp();b.set(ref,{type:"group",name:String(name).trim(),ownerUid:authUser.uid,memberUids:members,adminUids:[authUser.uid],createdAt:now,updatedAt:now,createdByUid:authUser.uid,historyPolicy:"fromJoin",groupVersion:1,keyEpoch:0});for(const uid of members){const p=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",uid));b.set(s.fsSdk.doc(s.db,"groups",ref.id,"members",uid),{uid,displayName:p.data()?.displayName||uid,role:uid===authUser.uid?"owner":"member",joinedAt:now,historyFrom:now,addedByUid:authUser.uid,active:true});}await b.commit();return{id:ref.id,cloudGroup:true,type:"group",name:String(name).trim(),ownerUid:authUser.uid,memberUids:members,preview:"Encrypted group ready"};}
export function subscribeMyGroups(uid,onRows,onError){let stop=()=>{};ensureServices().then(s=>{const q=s.fsSdk.query(s.fsSdk.collection(s.db,"groups"),s.fsSdk.where("memberUids","array-contains",uid));stop=s.fsSdk.onSnapshot(q,async snap=>{const rows=[];for(const d of snap.docs){const x=d.data(),ms=await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"groups",d.id,"members"));rows.push({id:d.id,cloudGroup:true,type:"group",name:x.name,ownerUid:x.ownerUid,memberUids:x.memberUids||[],keyEpoch:x.keyEpoch||0,members:ms.docs.map(m=>({id:m.id,...m.data()})),unread:0,preview:"Encrypted group",time:""});}onRows(rows);},onError);});return()=>stop();}
// Opaque group E2EE transport. firebase.js owns all Firestore SDK access; crypto remains outside.
export async function readCloudGroupAuthority(groupId){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const x=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"groups",groupId));if(!x.exists())throw new Error("Group was not found.");const d=x.data();return{groupId,memberUids:d.memberUids||[],adminUids:d.adminUids||[],keyEpoch:Number(d.keyEpoch||0),ownerUid:d.ownerUid};}
export async function createCloudGroupEpochRecord({groupId,expectedEpoch,newEpoch,record}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gr=s.fsSdk.doc(s.db,"groups",groupId),er=s.fsSdk.doc(s.db,"groups",groupId,"epochs",String(newEpoch));await s.fsSdk.runTransaction(s.db,async tx=>{const g=await tx.get(gr);if(!g.exists()||Number(g.data().keyEpoch||0)!==Number(expectedEpoch))throw new Error("Group epoch changed; retry from current authority.");const old=await tx.get(er);if(old.exists())throw new Error("Group epoch already exists.");tx.update(gr,{keyEpoch:newEpoch,updatedAt:s.fsSdk.serverTimestamp()});tx.set(er,{...record,createdAt:s.fsSdk.serverTimestamp()});});}
export async function readCloudGroupEpochRecord(groupId,keyEpoch){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const x=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"groups",groupId,"epochs",String(keyEpoch)));return x.exists()?x.data():null;}
export async function sendCloudEncryptedGroupMessage({groupId,messageId,envelope}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"groups",groupId,"messages",messageId),{...envelope,senderUid:authUser.uid,state:"sent",createdAt:s.fsSdk.serverTimestamp()});}
export function subscribeCloudGroupMessages(groupId,onRows,onError){let stop=()=>{};ensureServices().then(s=>{const q=s.fsSdk.query(s.fsSdk.collection(s.db,"groups",groupId,"messages"),s.fsSdk.orderBy("createdAt","asc"));stop=s.fsSdk.onSnapshot(q,x=>onRows(x.docs.map(d=>({id:d.id,...d.data()}))),onError);}).catch(onError);return()=>stop();}
export async function updateCloudGroupReceipt(groupId,messageId,state){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");if(!["delivered","read"].includes(state))throw new Error("Invalid group receipt state.");await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"groups",groupId,"messages",messageId,"receipts",authUser.uid),{uid:authUser.uid,state,updatedAt:s.fsSdk.serverTimestamp()},{merge:true});}
export function subscribeCloudGroupReceipts(groupId,messageId,onRows,onError){let stop=()=>{};ensureServices().then(s=>{stop=s.fsSdk.onSnapshot(s.fsSdk.collection(s.db,"groups",groupId,"messages",messageId,"receipts"),x=>onRows(x.docs.map(d=>({uid:d.id,...d.data()}))),onError);}).catch(onError);return()=>stop();}
export async function getCloudConversation(conversationId,myUid){const s=await ensureServices(),x=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"conversations",conversationId));if(!x.exists())return null;const d=x.data(),other=(d.members||[]).find(x=>x!==myUid);return{id:x.id,cloud:true,type:"direct",peerUid:other,name:d.memberNames?.[other]||"FIDUNIO contact"};}
export async function publishCloudE2EEPublicKey(uid,publicJwk){const s=await ensureServices();await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"users",uid),{e2eePublicJwk:publicJwk,e2eeVersion:1,e2eeUpdatedAt:s.fsSdk.serverTimestamp()},{merge:true});}export async function publishCloudE2EEDevice(uid,d){const s=await ensureServices();await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"users",uid,"devices",d.deviceId),{...d,uid,lastSeenAt:s.fsSdk.serverTimestamp(),active:true},{merge:true});}export async function getCloudUserDevices(uid){const s=await ensureServices();return (await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"users",uid,"devices"))).docs.map(d=>({id:d.id,...d.data()}));}export async function deactivateOtherCloudE2EEDevices(uid,keep){const s=await ensureServices(),x=await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"users",uid,"devices")),b=s.fsSdk.writeBatch(s.db);let n=0;for(const d of x.docs)if(d.id!==keep&&d.data().active!==false){b.set(d.ref,{active:false,revokedAt:s.fsSdk.serverTimestamp()},{merge:true});n++;}if(n)await b.commit();return{deactivated:n,keptDeviceId:keep};}
export async function sendCloudMessage(conversationId,m){const s=await ensureServices(),row={senderUid:authUser.uid,senderName:authUser.displayName||"User",timeLabel:m.timeLabel,state:m.state||"sent",createdAt:s.fsSdk.serverTimestamp()};if(m.e2ee)Object.assign(row,{e2ee:m.e2ee,ciphertext:m.ciphertext||"",iv:m.iv||"",text:"",kdfVersion:m.kdfVersion,senderKeyId:m.senderKeyId,recipientKeyId:m.recipientKeyId});else row.text=m.text||"";await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"conversations",conversationId,"messages",m.id),row);}
export async function updateCloudMessageState(c,id,state){const s=await ensureServices();await s.fsSdk.updateDoc(s.fsSdk.doc(s.db,"conversations",c,"messages",id),{state});}export async function markCloudConversationRead(c){const s=await ensureServices(),x=await s.fsSdk.getDocs(s.fsSdk.query(s.fsSdk.collection(s.db,"conversations",c,"messages"),s.fsSdk.orderBy("createdAt","asc")));await Promise.allSettled(x.docs.filter(d=>d.data().senderUid!==authUser.uid).map(d=>s.fsSdk.updateDoc(d.ref,{state:"read"})));}
export function subscribeMyConversations(uid,onRows,onError){let stop=()=>{};ensureServices().then(s=>{stop=s.fsSdk.onSnapshot(s.fsSdk.query(s.fsSdk.collection(s.db,"conversations"),s.fsSdk.where("members","array-contains",uid)),x=>onRows(x.docs.map(d=>{const r=d.data(),other=(r.members||[]).find(m=>m!==uid);return{id:d.id,cloud:true,type:"direct",peerUid:other,name:r.memberNames?.[other]||"FIDUNIO contact",preview:"Cloud conversation"};})),onError);});return()=>stop();}
export function subscribeConversationMessages(c,uid,onRows,onError){let stop=()=>{};ensureServices().then(s=>{stop=s.fsSdk.onSnapshot(s.fsSdk.query(s.fsSdk.collection(s.db,"conversations",c,"messages"),s.fsSdk.orderBy("createdAt","asc")),x=>onRows(x.docs.map(d=>({id:d.id,...d.data()}))),onError);});return()=>stop();}
export function subscribeUserDisplayNames(uids,onNames,onError){let stops=[],names={};ensureServices().then(s=>{for(const uid of [...new Set(uids)])stops.push(s.fsSdk.onSnapshot(s.fsSdk.doc(s.db,"users",uid),x=>{if(x.exists())names[uid]=x.data().displayName||x.data().email||uid;onNames({...names});},onError));});return()=>stops.forEach(x=>x());}
export async function readCloudAccountE2EEIdentity(uid){const s=await ensureServices(),x=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",uid,"e2ee","identity"));return x.exists()?x.data():null;}export async function createCloudAccountE2EEIdentity(uid,pub,pri){const s=await ensureServices(),a=s.fsSdk.doc(s.db,"users",uid,"e2ee","identity"),b=s.fsSdk.doc(s.db,"e2eePublicKeys",uid);return s.fsSdk.runTransaction(s.db,async tx=>{if((await tx.get(a)).exists()||(await tx.get(b)).exists())throw new Error("Durable E2EE identity already exists or is partially established; automatic replacement is forbidden.");const now=s.fsSdk.serverTimestamp();tx.set(a,{...pub,createdAt:now,updatedAt:now});tx.set(b,{...pri,createdAt:now,updatedAt:now});return{revision:1};});}export async function updateCloudAccountE2EENormalWrapper(uid,keyId,rev,normalWrapper){const s=await ensureServices(),r=s.fsSdk.doc(s.db,"users",uid,"e2ee","identity");return s.fsSdk.runTransaction(s.db,async tx=>{const x=await tx.get(r);if(!x.exists()||x.data().keyId!==keyId||x.data().revision!==rev)throw new Error("E2EE identity changed; reload before retrying.");tx.update(r,{normalWrapper,revision:rev+1,updatedAt:s.fsSdk.serverTimestamp()});return{revision:rev+1};});}export async function getCloudAccountE2EEPublicKey(uid){const s=await ensureServices(),x=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"e2eePublicKeys",uid));return x.exists()?{uid:x.id,...x.data()}:null;}
