import { firebaseConfig } from "./firebase-config.js";
import { normalizeDisappearSelection } from "./disappearing-content-policy.js";
import {assertInvitationUsable,normalizeInvitationRole,canIssueInvitation} from "./invitation-policy.js";
import {createDirectMessageDeliveryOwner} from "./direct-message-delivery-owner.js";

const SDK_VERSION="12.18.0";
// Public reCAPTCHA Enterprise site key registered for FIDUNIO Web / willyros01.github.io.
// This key is intentionally public and constrained by its Google Cloud configuration.
export const FIDUNIO_RECAPTCHA_ENTERPRISE_SITE_KEY="6LfLaqstAAAAANNkEghVZ26a4vv8hXwC7KDI9rma";
let sdkPromise=null;
let services=null;
let authUser=null;
const messageStreams=new Map();

export function isFirebaseConfigured(){return firebaseConfig&&!String(firebaseConfig.apiKey||"").includes("PASTE_")&&!String(firebaseConfig.projectId||"").includes("PASTE_")&&!String(firebaseConfig.appId||"").includes("PASTE_");}
async function loadSdk(){if(sdkPromise)return sdkPromise;sdkPromise=Promise.all([import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-firestore.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-app-check.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-functions.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-storage.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-messaging.js`)]).then(([appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk,storageSdk,messagingSdk])=>({appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk,storageSdk,messagingSdk}));return sdkPromise;}
async function ensureServices(){if(services)return services;if(!isFirebaseConfigured())throw new Error("Firebase is not configured yet.");const {appSdk,authSdk,fsSdk,appCheckSdk,functionsSdk,storageSdk,messagingSdk}=await loadSdk();const app=appSdk.initializeApp(firebaseConfig);const appCheck=appCheckSdk.initializeAppCheck(app,{provider:new appCheckSdk.ReCaptchaEnterpriseProvider(FIDUNIO_RECAPTCHA_ENTERPRISE_SITE_KEY),isTokenAutoRefreshEnabled:true});const auth=authSdk.getAuth(app),db=fsSdk.getFirestore(app),functions=functionsSdk.getFunctions(app,"us-central1"),storage=storageSdk.getStorage(app);services={app,appCheck,auth,db,functions,storage,authSdk,fsSdk,functionsSdk,storageSdk,messagingSdk,messaging:null};return services;}
export async function initFirebase(onUserChanged){const s=await ensureServices();s.authSdk.onAuthStateChanged(s.auth,user=>{authUser=user||null;onUserChanged?.(authUser);});return s;}
export function getFirebaseUser(){return authUser;}
export async function ensureFirebaseAuthSession(){const s=await ensureServices(),user=s.auth.currentUser;if(!user||!authUser||user.uid!==authUser.uid)throw new Error("Firebase authentication session is unavailable.");await user.getIdToken();authUser=user;return{uid:user.uid};}

async function ensureNotificationMessaging(){const s=await ensureServices();if(!(await s.messagingSdk.isSupported()))return null;if(!s.messaging)s.messaging=s.messagingSdk.getMessaging(s.app);return{s,messaging:s.messaging};}
export async function getFidunioNotificationCapability(){if(typeof Notification==="undefined")return{supported:false,permission:"unsupported"};const pair=await ensureNotificationMessaging();return{supported:!!pair,permission:Notification.permission};}
export async function getFidunioMessagingToken({vapidKey,serviceWorkerRegistration}={}){if(!authUser)throw new Error("Sign in first.");if(typeof Notification==="undefined"||Notification.permission!=="granted")throw new Error("Notification permission has not been granted.");const pair=await ensureNotificationMessaging();if(!pair)throw new Error("Notifications are not supported on this device/browser.");const key=String(vapidKey||"").trim();if(!key)throw new Error("FIDUNIO Web Push is not configured yet.");const options={vapidKey:key};if(serviceWorkerRegistration)options.serviceWorkerRegistration=serviceWorkerRegistration;return pair.s.messagingSdk.getToken(pair.messaging,options);}
export async function deleteFidunioMessagingToken(){const pair=await ensureNotificationMessaging();if(!pair)return false;return pair.s.messagingSdk.deleteToken(pair.messaging);}
function notificationDeviceId(value){const id=String(value||"").trim();if(id.length<8||id.length>128)throw new Error("Invalid notification installation ID.");return id;}
function notificationPlatform(value){const platform=String(value||"");if(!["ios-pwa","ios-browser","android-browser","desktop-browser"].includes(platform))throw new Error("Invalid notification platform.");return platform;}
export async function getCloudNotificationDevice(installationId){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const id=notificationDeviceId(installationId),snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",authUser.uid,"notificationDevices",id));return snap.exists()?{id:snap.id,...snap.data()}:null;}
export async function upsertCloudNotificationDevice({installationId,fcmToken,platform,enabled=true,showSenderName=false}={}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const id=notificationDeviceId(installationId),token=String(fcmToken||"").trim(),kind=notificationPlatform(platform);if(token.length<20||token.length>4096)throw new Error("Invalid FCM registration token.");const ref=s.fsSdk.doc(s.db,"users",authUser.uid,"notificationDevices",id),snap=await s.fsSdk.getDoc(ref),row={installationId:id,fcmToken:token,platform:kind,enabled:enabled===true,showSenderName:showSenderName===true,updatedAt:s.fsSdk.serverTimestamp(),lastSeenAt:s.fsSdk.serverTimestamp()};if(snap.exists())await s.fsSdk.updateDoc(ref,row);else await s.fsSdk.setDoc(ref,{...row,createdAt:s.fsSdk.serverTimestamp()});return{id,...row};}
export async function deleteCloudNotificationDevice(installationId){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const id=notificationDeviceId(installationId);await s.fsSdk.deleteDoc(s.fsSdk.doc(s.db,"users",authUser.uid,"notificationDevices",id));return true;}

async function callCloudFunction(name,data={}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const callable=s.functionsSdk.httpsCallable(s.functions,name);const result=await callable(data);return result.data;}
export function enrollCloudE2EERecovery(data){return callCloudFunction("enrollRecoveryV1",data);}export function startCloudE2EERecovery(){return callCloudFunction("startE2EERecoveryV1",{});}export function completeCloudE2EERecovery(data){return callCloudFunction("completeE2EERecoveryV1",data);}
export function deleteCloudDirectMessageForEveryone(conversationId,messageId){return callCloudFunction("deleteDirectMessageForEveryoneV1",{conversationId:String(conversationId||""),messageId:String(messageId||"")});}
export function deleteCloudGroupMessageForEveryone(groupId,messageId){return callCloudFunction("deleteDirectMessageForEveryoneV1",{conversationId:String(groupId||""),messageId:String(messageId||""),messageKind:"group"});}
export function deleteCloudMyMessagesForEveryone(conversationId,messageKind="direct"){return callCloudFunction("deleteMyMessagesForEveryoneV1",{conversationId:String(conversationId||""),messageKind:messageKind==="group"?"group":"direct"});}
export function deleteCloudConversationForEveryone(conversationId,conversationKind="direct"){return callCloudFunction("deleteConversationForEveryoneV1",{conversationId:String(conversationId||""),conversationKind:conversationKind==="group"?"group":"direct"});}
function normalizeInviteToken(token){return String(token||"").trim().replace(/\s+/g,"");}function bytesToUrlToken(bytes){let raw="";bytes.forEach(b=>raw+=String.fromCharCode(b));return btoa(raw).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}async function sha256Hex(text){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("");}async function inviteIdForToken(token){const clean=normalizeInviteToken(token);if(clean.length<20)throw new Error("Invitation code is incomplete.");return sha256Hex(clean);}function inviteLink(token){const url=new URL(globalThis.location?.href||"https://willyros01.github.io/hermes/");url.hash="";url.search="";url.searchParams.set("invite",token);return url.toString();}
export async function getFidunioAccessInfo(){const s=await ensureServices();if(!authUser)return{user:null,profile:null,system:null,role:null};const [profileSnap,systemSnap]=await Promise.all([s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",authUser.uid)),s.fsSdk.getDoc(s.fsSdk.doc(s.db,"system","access"))]);const profile=profileSnap.exists()?{uid:profileSnap.id,...profileSnap.data()}:null;const system=systemSnap.exists()?systemSnap.data():null;return{user:authUser,profile,system,role:profile?.systemRole||null};}
export async function claimLegacyOwner(){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const profileRef=s.fsSdk.doc(s.db,"users",authUser.uid),systemRef=s.fsSdk.doc(s.db,"system","access");const profileSnap=await s.fsSdk.getDoc(profileRef);if(!profileSnap.exists())throw new Error("This account does not have an existing FIDUNIO profile.");const systemSnap=await s.fsSdk.getDoc(systemRef);if(systemSnap.exists())throw new Error("FIDUNIO already has an Owner.");const batch=s.fsSdk.writeBatch(s.db);batch.set(systemRef,{ownerUid:authUser.uid,createdByUid:authUser.uid,createdAt:s.fsSdk.serverTimestamp(),accessModel:"invite-only-v1"});batch.update(profileRef,{systemRole:"owner"});await batch.commit();return getFidunioAccessInfo();}
export async function validateInvitation(token){const s=await ensureServices();const clean=normalizeInviteToken(token),id=await inviteIdForToken(clean),snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"invitations",id));if(!snap.exists())throw new Error("This FIDUNIO invitation is not valid.");const data=snap.data(),expires=data.expiresAt?.toDate?.()||null;assertInvitationUsable({status:data.status,expiresAt:expires,now:Date.now()});return{id,token:clean,role:data.role||"user",invitedByUid:data.invitedByUid||"",invitedByName:data.invitedByName||"FIDUNIO administrator",expiresAt:expires,status:data.status};}
export async function createFidunioInvitation(role="user",days=7){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const access=await getFidunioAccessInfo();if(!canIssueInvitation(access.role))throw new Error("Only a FIDUNIO Owner or Admin can issue invitations.");role=normalizeInvitationRole(role);const safeDays=Math.max(1,Math.min(30,Number(days)||7)),token=bytesToUrlToken(crypto.getRandomValues(new Uint8Array(24))),id=await inviteIdForToken(token),expires=new Date(Date.now()+safeDays*86400000);await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"invitations",id),{status:"pending",role,invitedByUid:authUser.uid,invitedByName:access.profile?.displayName||authUser.displayName||authUser.email||"FIDUNIO administrator",createdAt:s.fsSdk.serverTimestamp(),expiresAt:s.fsSdk.Timestamp.fromDate(expires),acceptedUid:null,acceptedAt:null,revokedAt:null});return{id,token,role,expiresAt:expires,link:inviteLink(token)};}
export async function redeemFidunioInvitation(token,email,password,displayName){const s=await ensureServices();const invite=await validateInvitation(token),name=String(displayName||"").trim(),mail=String(email||"").trim();if(!name)throw new Error("Enter your display name.");if(!mail)throw new Error("Enter your email address.");let cred=null;try{cred=await s.authSdk.createUserWithEmailAndPassword(s.auth,mail,password);await s.authSdk.updateProfile(cred.user,{displayName:name});authUser=cred.user;const inviteRef=s.fsSdk.doc(s.db,"invitations",invite.id),profileRef=s.fsSdk.doc(s.db,"users",cred.user.uid),batch=s.fsSdk.writeBatch(s.db);batch.update(inviteRef,{status:"accepted",acceptedUid:cred.user.uid,acceptedEmail:cred.user.email||mail,acceptedAt:s.fsSdk.serverTimestamp()});batch.set(profileRef,{displayName:name,email:cred.user.email||mail,systemRole:invite.role,joinedByInviteId:invite.id,invitedByUid:invite.invitedByUid,createdAt:s.fsSdk.serverTimestamp(),active:true});await batch.commit();return cred.user;}catch(err){if(cred?.user){try{await s.authSdk.deleteUser(cred.user);}catch{}authUser=null;}throw err;}}
export async function createFidunioAccount(){throw new Error("FIDUNIO account creation is invitation-only. Use a valid invitation link or code.");}export async function signInFidunio(email,password){const s=await ensureServices();const cred=await s.authSdk.signInWithEmailAndPassword(s.auth,email,password);const profileSnap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",cred.user.uid));if(!profileSnap.exists()){await s.authSdk.signOut(s.auth);authUser=null;throw new Error("This Firebase login is not enrolled in FIDUNIO. A valid invitation is required.");}authUser=cred.user;return cred.user;}export async function signOutFidunio(){const s=await ensureServices();await s.authSdk.signOut(s.auth);authUser=null;}export async function sendFidunioPasswordReset(email){const s=await ensureServices();const mail=String(email||"").trim();if(!mail)throw new Error("Enter your email address first.");await s.authSdk.sendPasswordResetEmail(s.auth,mail);}
export async function updateFidunioProfile(values={}){const s=await ensureServices(),user=s.auth.currentUser;if(!user)throw new Error("Sign in first.");const name=String(values.displayName||"").trim(),mail=String(values.email||"").trim(),phone=String(values.telephone||"").trim(),photo=String(values.photoURL||"").trim();if(!name)throw new Error("Display name is required.");if(mail&&mail!==user.email){if(!values.currentPassword)throw new Error("Enter your current password to change your email address.");const credential=s.authSdk.EmailAuthProvider.credential(user.email,values.currentPassword);await s.authSdk.reauthenticateWithCredential(user,credential);await s.authSdk.updateEmail(user,mail);}await s.authSdk.updateProfile(user,{displayName:name,photoURL:photo||null});authUser=user;await s.fsSdk.updateDoc(s.fsSdk.doc(s.db,"users",user.uid),{displayName:name,email:user.email||mail,telephone:phone,photoURL:photo,profileUpdatedAt:s.fsSdk.serverTimestamp()});return{uid:user.uid,displayName:user.displayName||name,email:user.email||mail,photoURL:user.photoURL||photo};}
export async function changeFidunioPassword(currentPassword,newPassword){const s=await ensureServices(),user=s.auth.currentUser;if(!user)throw new Error("Sign in first.");if(!currentPassword)throw new Error("Enter your current password.");if(String(newPassword||"").length<6)throw new Error("New password must be at least 6 characters.");const credential=s.authSdk.EmailAuthProvider.credential(user.email,currentPassword);await s.authSdk.reauthenticateWithCredential(user,credential);await s.authSdk.updatePassword(user,newPassword);}
export async function listFidunioUsersForAdmin(){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const snap=await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"users"));return snap.docs.map(d=>({uid:d.id,...d.data()})).sort((a,b)=>String(a.displayName||a.email||a.uid).localeCompare(String(b.displayName||b.email||b.uid)));}
export async function updateFidunioUserLifecycle(targetUid,status,expiryDays=undefined){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const uid=String(targetUid||"").trim();if(!uid)throw new Error("Target user is required.");if(!["active","suspended","deactivated"].includes(status))throw new Error("Unsupported account status.");const now=s.fsSdk.serverTimestamp(),ref=s.fsSdk.doc(s.db,"users",uid),row={status,active:status==="active",adminUpdatedAt:now,adminUpdatedByUid:authUser.uid};if(expiryDays!==undefined)row.expiresAt=expiryDays===null?null:s.fsSdk.Timestamp.fromDate(new Date(Date.now()+Number(expiryDays)*86400000));if(status==="suspended"){row.suspendedAt=now;row.suspendedByUid=authUser.uid;row.restoredAt=null;row.restoredByUid=null;}if(status==="active"){row.restoredAt=now;row.restoredByUid=authUser.uid;row.suspendedAt=null;row.suspendedByUid=null;row.deactivatedAt=null;row.deactivatedByUid=null;}if(status==="deactivated"){row.deactivatedAt=now;row.deactivatedByUid=authUser.uid;}await s.fsSdk.updateDoc(ref,row);}
export async function listPendingFidunioInvitations(){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const snap=await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"invitations"));return snap.docs.map(d=>({id:d.id,...d.data()})).filter(i=>i.status==="pending").sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));}export async function revokeFidunioInvitation(id){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const clean=String(id||"").trim();if(!clean)throw new Error("Invitation is required.");await s.fsSdk.updateDoc(s.fsSdk.doc(s.db,"invitations",clean),{status:"revoked",revokedAt:s.fsSdk.serverTimestamp()});}
function dmId(a,b){return "dm_"+[a,b].sort().join("_");}export async function startDirectConversation(peerUid){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const peerSnap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",peerUid));if(!peerSnap.exists())throw new Error("Recipient FIDUNIO ID was not found.");const peer=peerSnap.data();const meSnap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",authUser.uid));const me=meSnap.exists()?meSnap.data():{displayName:authUser.displayName||authUser.email||"User"};const id=dmId(authUser.uid,peerUid),ref=s.fsSdk.doc(s.db,"conversations",id);await s.fsSdk.setDoc(ref,{type:"direct",members:[authUser.uid,peerUid],memberNames:{[authUser.uid]:me.displayName||"User",[peerUid]:peer.displayName||"User"},updatedAt:s.fsSdk.serverTimestamp(),createdAt:s.fsSdk.serverTimestamp()},{merge:true});return{id,cloud:true,peerUid,name:peer.displayName||"FIDUNIO contact",preview:"Cloud conversation",time:""};}export async function getCloudUserProfile(uid){const s=await ensureServices();const snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",uid));return snap.exists()?{uid,...snap.data()}:null;}export async function listCloudUsers(){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const snap=await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"users"));return snap.docs.map(d=>({uid:d.id,...d.data()})).filter(x=>x.uid!==authUser.uid&&x.active!==false).sort((a,b)=>String(a.displayName||a.email||a.uid).localeCompare(String(b.displayName||b.email||b.uid)));}
export async function createCloudGroup(name,memberUids){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const cleanName=String(name||"").trim();if(!cleanName)throw new Error("Enter a group name.");const members=[...new Set([authUser.uid,...(memberUids||[]).filter(Boolean)])];if(members.length<3)throw new Error("Select at least 2 other people.");if(members.length>64)throw new Error("A group can have at most 64 members in this test phase.");const profiles={};for(const uid of members){const snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",uid));if(!snap.exists())throw new Error("One selected FIDUNIO user was not found.");profiles[uid]=snap.data();}const groupRef=s.fsSdk.doc(s.fsSdk.collection(s.db,"groups"));const batch=s.fsSdk.writeBatch(s.db);const now=s.fsSdk.serverTimestamp();batch.set(groupRef,{type:"group",name:cleanName,ownerUid:authUser.uid,memberUids:members,adminUids:[authUser.uid],createdAt:now,updatedAt:now,createdByUid:authUser.uid,historyPolicy:"fromJoin",groupVersion:1,keyEpoch:0});for(const uid of members){batch.set(s.fsSdk.doc(s.db,"groups",groupRef.id,"members",uid),{uid,displayName:profiles[uid]?.displayName||profiles[uid]?.email||"FIDUNIO user",role:uid===authUser.uid?"owner":"member",joinedAt:now,historyFrom:now,addedByUid:authUser.uid,active:true});}await batch.commit();return{id:groupRef.id,cloudGroup:true,type:"group",name:cleanName,ownerUid:authUser.uid,memberUids:members,members:members.map(uid=>({id:uid,name:profiles[uid]?.displayName||profiles[uid]?.email||"FIDUNIO user",role:uid===authUser.uid?"Owner":"Member",joinedAt:"At group creation",historyAccess:uid===authUser.uid?"all":"from_join"})),unread:0,preview:"Group created",time:""};}
export function subscribeMyGroups(uid,onRows,onError){let active=true,unsub=()=>{},snapshotRevision=0;ensureServices().then(s=>{if(!active)return;const q=s.fsSdk.query(s.fsSdk.collection(s.db,"groups"),s.fsSdk.where("memberUids","array-contains",uid));unsub=s.fsSdk.onSnapshot(q,async snap=>{const revision=++snapshotRevision;try{const rows=[];let fromCache=snap.metadata?.fromCache===true,hasPendingWrites=snap.metadata?.hasPendingWrites===true;for(const d of snap.docs){const x=d.data(),memberUids=Array.isArray(x.memberUids)?x.memberUids:[],currentMembers=new Set(memberUids);const memberSnap=await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"groups",d.id,"members"));fromCache=fromCache||memberSnap.metadata?.fromCache===true;hasPendingWrites=hasPendingWrites||memberSnap.metadata?.hasPendingWrites===true;const members=memberSnap.docs.filter(m=>currentMembers.has(m.id)).map(m=>{const y=m.data();return{id:m.id,name:y.displayName||m.id,role:y.role==="owner"?"Owner":y.role==="admin"?"Admin":"Member",joinedAt:y.joinedAt?.toDate?.().toLocaleString?.()||"Member",historyAccess:"from_join"};});rows.push({id:d.id,cloudGroup:true,type:"group",name:x.name||"FIDUNIO Group",ownerUid:x.ownerUid,memberUids,adminUids:Array.isArray(x.adminUids)?x.adminUids:[],historyPolicy:x.historyPolicy||"fromJoin",keyEpoch:Number(x.keyEpoch||0),members,unread:0,preview:"Encrypted group",time:"",updatedAtMs:x.updatedAt?.toMillis?.()||0});}if(active&&revision===snapshotRevision)onRows(rows,{fromCache,hasPendingWrites});}catch(err){if(active&&revision===snapshotRevision)onError?.(err);}},onError);}).catch(onError);return()=>{active=false;snapshotRevision++;unsub();};}

// Bounded opaque group-E2EE transport. No crypto or device identity is handled here.
export async function readCloudGroupAuthority(groupId){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"groups",groupId));if(!snap.exists())throw new Error("Group was not found.");const x=snap.data(),members=Array.isArray(x.memberUids)?x.memberUids:[];if(!members.includes(authUser.uid))throw new Error("Group is not available to this account.");return{groupId,ownerUid:x.ownerUid,memberUids:members,adminUids:Array.isArray(x.adminUids)?x.adminUids:[],keyEpoch:Number(x.keyEpoch||0)};}
export async function getCloudGroupFromServer(groupId,myUid){const s=await ensureServices();if(!authUser||authUser.uid!==myUid)throw new Error("Sign in first.");const gid=String(groupId||"").trim();if(!gid)throw new Error("Group is required.");try{const snap=await s.fsSdk.getDocFromServer(s.fsSdk.doc(s.db,"groups",gid));if(!snap.exists())return null;const x=snap.data(),members=Array.isArray(x.memberUids)?x.memberUids:[];if(!members.includes(myUid))return null;return{id:snap.id,cloudGroup:true,type:"group",name:x.name||"FIDUNIO Group",ownerUid:x.ownerUid,memberUids:members,adminUids:Array.isArray(x.adminUids)?x.adminUids:[],historyPolicy:x.historyPolicy||"fromJoin",keyEpoch:Number(x.keyEpoch||0),members:[],unread:0,preview:"Encrypted group",time:""};}catch(error){if(String(error?.code||"").includes("permission-denied"))return null;throw error;}}
export async function getCloudGroupMessageFromServer(groupId,myUid,messageId){const s=await ensureServices();if(!authUser||authUser.uid!==myUid)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),mid=String(messageId||"").trim();if(!gid||!mid)throw new Error("Group notification message identity is incomplete.");const snap=await s.fsSdk.getDocFromServer(s.fsSdk.doc(s.db,"groups",gid,"messages",mid));if(!snap.exists()){const error=new Error("Notified group message is no longer available.");error.code="notification/not-found";throw error;}return{id:snap.id,...snap.data()};}
export async function renameCloudGroup({groupId,name}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const clean=String(name||"").trim();if(!clean||clean.length>120)throw new Error("Group name must be 1 to 120 characters.");const ref=s.fsSdk.doc(s.db,"groups",String(groupId));return s.fsSdk.runTransaction(s.db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error("Group was not found.");const g=snap.data(),admins=Array.isArray(g.adminUids)?g.adminUids:[];if(!admins.includes(authUser.uid))throw new Error("Only a group administrator can rename this group.");tx.update(ref,{name:clean,updatedAt:s.fsSdk.serverTimestamp()});return{name:clean};});}
function sameUidKeys(map,uids){const a=Object.keys(map||{}).sort(),b=[...uids].sort();return a.length===b.length&&a.every((v,i)=>v===b[i]);}
export async function commitCloudGroupMembershipEpoch({groupId,operation,targetUid,expectedEpoch,newEpoch,record}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),target=String(targetUid||"").trim(),op=String(operation||"").trim();if(!gid||!target)throw new Error("Group and member are required.");let targetProfile=null;if(op==="add"){const ps=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",target));if(!ps.exists()||ps.data().active===false)throw new Error("The selected FIDUNIO account is not active.");targetProfile=ps.data();}
const groupRef=s.fsSdk.doc(s.db,"groups",gid),epochRef=s.fsSdk.doc(s.db,"groups",gid,"epochs",String(newEpoch)),memberRef=s.fsSdk.doc(s.db,"groups",gid,"members",target);return s.fsSdk.runTransaction(s.db,async tx=>{const snap=await tx.get(groupRef);if(!snap.exists())throw new Error("Group was not found.");const g=snap.data(),actor=authUser.uid,members=[...new Set(Array.isArray(g.memberUids)?g.memberUids:[])],admins=[...new Set(Array.isArray(g.adminUids)?g.adminUids:[])],isAdmin=admins.includes(actor),current=Number(g.keyEpoch||0);if(current!==Number(expectedEpoch)||Number(newEpoch)!==current+1)throw new Error("Group membership changed; reload before retrying.");if((await tx.get(epochRef)).exists())throw new Error("Group epoch already exists.");let nextMembers=[...members],nextAdmins=[...admins];
if(op==="add"){if(!isAdmin)throw new Error("Only a group administrator can add members.");if(nextMembers.includes(target))throw new Error("That account is already a group member.");if(nextMembers.length>=64)throw new Error("A group can have at most 64 members.");nextMembers.push(target);}
else if(op==="remove"){if(!isAdmin)throw new Error("Only a group administrator can remove members.");if(target===g.ownerUid)throw new Error("The group owner cannot be removed.");if(!nextMembers.includes(target))throw new Error("That account is not a group member.");nextMembers=nextMembers.filter(uid=>uid!==target);nextAdmins=nextAdmins.filter(uid=>uid!==target);}
else if(op==="leave"){if(target!==actor||!nextMembers.includes(actor))throw new Error("Only the signed-in member can leave this group.");if(actor===g.ownerUid)throw new Error("The group owner cannot leave while ownership is immutable.");nextMembers=nextMembers.filter(uid=>uid!==actor);nextAdmins=nextAdmins.filter(uid=>uid!==actor);}
else throw new Error("Unsupported group membership operation.");
if(!nextMembers.includes(g.ownerUid)||!nextAdmins.includes(g.ownerUid)||!nextAdmins.every(uid=>nextMembers.includes(uid)))throw new Error("Group owner/admin invariants would be violated.");if(record?.format!=="fidunio-group-key-v1"||record.groupId!==gid||Number(record.keyEpoch)!==Number(newEpoch)||record.createdByUid!==actor||!sameUidKeys(record.memberKeyIds,nextMembers)||!sameUidKeys(record.envelopes,nextMembers))throw new Error("New group epoch does not match post-change membership.");const now=s.fsSdk.serverTimestamp();tx.update(groupRef,{memberUids:nextMembers,adminUids:nextAdmins,keyEpoch:Number(newEpoch),updatedAt:now});tx.set(epochRef,{...record,createdAt:now});if(op==="add")tx.set(memberRef,{uid:target,displayName:targetProfile?.displayName||targetProfile?.email||"FIDUNIO user",role:"member",joinedAt:now,historyFrom:now,addedByUid:actor,active:true});else tx.delete(memberRef);return{groupId:gid,memberUids:nextMembers,adminUids:nextAdmins,keyEpoch:Number(newEpoch)};});}

export async function beginCloudGroupHistoryGrant({groupId,grant}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),grantId=String(grant?.grantId||"").trim();if(!gid||!grantId)throw new Error("Group and history grant ID are required.");const groupRef=s.fsSdk.doc(s.db,"groups",gid),grantRef=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",grantId);return s.fsSdk.runTransaction(s.db,async tx=>{const [groupSnap,existing,grantorKey,targetKey]=await Promise.all([tx.get(groupRef),tx.get(grantRef),tx.get(s.fsSdk.doc(s.db,"e2eePublicKeys",authUser.uid)),tx.get(s.fsSdk.doc(s.db,"e2eePublicKeys",String(grant.targetUid||"")))]);if(!groupSnap.exists())throw new Error("Group was not found.");const g=groupSnap.data(),admins=Array.isArray(g.adminUids)?g.adminUids:[],members=Array.isArray(g.memberUids)?g.memberUids:[];if(!admins.includes(authUser.uid))throw new Error("Only a group administrator can grant earlier history.");if(!members.includes(grant.targetUid)||grant.targetUid===authUser.uid)throw new Error("History target must be another current group member.");if(!grantorKey.exists()||grantorKey.data().keyId!==grant.grantorKeyId||!targetKey.exists()||targetKey.data().keyId!==grant.targetKeyId)throw new Error("History grant account key authority changed.");if(existing.exists()){const x=existing.data(),same=x.status==="building"&&x.grantorUid===grant.grantorUid&&x.targetUid===grant.targetUid&&x.boundaryKind===grant.boundaryKind&&Number(x.totalCopies)===Number(grant.totalCopies)&&x.firstSharedMessageId===grant.firstSharedMessageId;if(!same)throw new Error("History grant ID already exists with different authority.");return{grantId,status:x.status};}const now=s.fsSdk.serverTimestamp();tx.update(groupRef,{updatedAt:now});tx.set(grantRef,{...grant,createdAt:now,activatedAt:null});return{grantId,status:"building"};});}
export async function writeCloudGroupHistoryGrantCopies({groupId,grantId,copies}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),id=String(grantId||"").trim(),rows=Array.isArray(copies)?copies:[];if(!gid||!id||!rows.length)throw new Error("History grant copies are required.");if(rows.length>100)throw new Error("History grant copy chunk exceeds 100 records.");const groupRef=s.fsSdk.doc(s.db,"groups",gid),grantRef=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id);const [groupSnap,grantSnap]=await Promise.all([s.fsSdk.getDoc(groupRef),s.fsSdk.getDoc(grantRef)]);if(!groupSnap.exists()||!grantSnap.exists())throw new Error("History grant authority is unavailable.");const g=groupSnap.data(),grant=grantSnap.data();if(!Array.isArray(g.adminUids)||!g.adminUids.includes(authUser.uid)||grant.grantorUid!==authUser.uid||grant.status!=="building"||!Array.isArray(g.memberUids)||!g.memberUids.includes(grant.targetUid))throw new Error("History grant is no longer writable.");const batch=s.fsSdk.writeBatch(s.db);let writes=0;const now=s.fsSdk.serverTimestamp();for(const row of rows){const sourceId=String(row?.sourceMessageId||"").trim();if(!sourceId)throw new Error("History source message ID is required.");const ref=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id,"messages",sourceId),snap=await s.fsSdk.getDoc(ref);if(snap.exists())continue;batch.set(ref,{...row,createdAt:now});writes++;}if(writes){batch.update(groupRef,{updatedAt:now});await batch.commit();}return{written:writes};}
export async function activateCloudGroupHistoryGrant({groupId,grantId}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),id=String(grantId||"").trim(),groupRef=s.fsSdk.doc(s.db,"groups",gid),grantRef=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id);return s.fsSdk.runTransaction(s.db,async tx=>{const [groupSnap,grantSnap]=await Promise.all([tx.get(groupRef),tx.get(grantRef)]);if(!groupSnap.exists()||!grantSnap.exists())throw new Error("History grant authority is unavailable.");const g=groupSnap.data(),grant=grantSnap.data();if(grant.status==="active")return{grantId:id,status:"active"};if(grant.status!=="building"||grant.grantorUid!==authUser.uid||!Array.isArray(g.adminUids)||!g.adminUids.includes(authUser.uid)||!Array.isArray(g.memberUids)||!g.memberUids.includes(grant.targetUid))throw new Error("History grant can no longer be activated.");tx.update(grantRef,{status:"active",activatedAt:s.fsSdk.serverTimestamp()});return{grantId:id,status:"active"};});}
export async function readCloudGroupHistoryGrants(groupId){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim();await readCloudGroupAuthority(gid);const q=s.fsSdk.query(s.fsSdk.collection(s.db,"groups",gid,"historyGrants"),s.fsSdk.where("targetUid","==",authUser.uid),s.fsSdk.where("status","==","active"));const snap=await s.fsSdk.getDocsFromServer(q);return snap.docs.map(d=>({id:d.id,...d.data()}));}
export async function readCloudGroupHistoryGrantCopies(groupId,grantId){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),id=String(grantId||"").trim();await readCloudGroupAuthority(gid);const grantSnap=await s.fsSdk.getDocFromServer(s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id));if(!grantSnap.exists()||grantSnap.data().status!=="active"||grantSnap.data().targetUid!==authUser.uid)throw new Error("Active history grant is not available to this account.");const q=s.fsSdk.query(s.fsSdk.collection(s.db,"groups",gid,"historyGrants",id,"messages"),s.fsSdk.orderBy("sourceCreatedAt","asc"));const snap=await s.fsSdk.getDocsFromServer(q);return snap.docs.map(d=>({id:d.id,...d.data()}));}

export async function createCloudGroupEpochRecord({groupId,expectedEpoch,newEpoch,record}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const groupRef=s.fsSdk.doc(s.db,"groups",groupId),epochRef=s.fsSdk.doc(s.db,"groups",groupId,"epochs",String(newEpoch));return s.fsSdk.runTransaction(s.db,async tx=>{const groupSnap=await tx.get(groupRef);if(!groupSnap.exists())throw new Error("Group was not found.");const group=groupSnap.data(),admins=Array.isArray(group.adminUids)?group.adminUids:[];if(!admins.includes(authUser.uid))throw new Error("Only a group administrator can rotate encryption keys.");if(Number(group.keyEpoch||0)!==Number(expectedEpoch)||Number(newEpoch)!==Number(expectedEpoch)+1)throw new Error("Group epoch changed; reload before retrying.");if((await tx.get(epochRef)).exists())throw new Error("Group epoch already exists.");tx.update(groupRef,{keyEpoch:Number(newEpoch),updatedAt:s.fsSdk.serverTimestamp()});tx.set(epochRef,{...record,createdAt:s.fsSdk.serverTimestamp()});return{keyEpoch:Number(newEpoch)};});}
export async function readCloudGroupEpochRecord(groupId,keyEpoch){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const authority=await readCloudGroupAuthority(groupId);if(!authority.memberUids.includes(authUser.uid))throw new Error("Group is not available to this account.");const snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"groups",groupId,"epochs",String(keyEpoch)));return snap.exists()?{...snap.data()}:null;}
export async function sendCloudEncryptedGroupMessage({groupId,messageId,envelope,disappearAfterSeconds=null,disappearingPurgeVersion=null}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const authority=await readCloudGroupAuthority(groupId);if(Number(envelope?.keyEpoch)!==authority.keyEpoch)throw new Error("Group epoch changed; queued message must be re-encrypted.");if(Number(envelope?.e2ee)!==4||envelope?.groupFormat!=="fidunio-group-message-v1")throw new Error("Invalid encrypted group envelope.");const duration=normalizeDisappearSelection(disappearAfterSeconds),row={...envelope,senderUid:authUser.uid,state:"sent",createdAt:s.fsSdk.serverTimestamp(),receiptRevision:0};if(duration!==null)row.disappearAfterSeconds=duration;if(disappearingPurgeVersion===1&&duration!==null)row.disappearingPurgeVersion=1;await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"groups",groupId,"messages",messageId),row);return{messageId,state:"sent",keyEpoch:authority.keyEpoch};}
export function subscribeCloudGroupMessages(groupId,onRows,onError){let active=true,unsub=()=>{};readCloudGroupAuthority(groupId).then(async()=>{const s=await ensureServices();if(!active)return;const q=s.fsSdk.query(s.fsSdk.collection(s.db,"groups",groupId,"messages"),s.fsSdk.orderBy("createdAt","asc"));unsub=s.fsSdk.onSnapshot(q,snap=>{if(active)onRows?.(snap.docs.map(d=>({id:d.id,...d.data()})),{fromCache:!!snap.metadata?.fromCache,hasPendingWrites:!!snap.metadata?.hasPendingWrites});},err=>{if(active)onError?.(err);});}).catch(err=>{if(active)onError?.(err);});return()=>{active=false;unsub();};}
export async function updateCloudGroupReceipt(groupId,messageId,state){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");if(!["delivered","read"].includes(state))throw new Error("Invalid group receipt state.");await readCloudGroupAuthority(groupId);const messageRef=s.fsSdk.doc(s.db,"groups",groupId,"messages",messageId),ref=s.fsSdk.doc(s.db,"groups",groupId,"messages",messageId,"receipts",authUser.uid);return s.fsSdk.runTransaction(s.db,async tx=>{const [messageSnap,snap]=await Promise.all([tx.get(messageRef),tx.get(ref)]);if(!messageSnap.exists())throw new Error("Group message was not found.");const message=messageSnap.data(),current=snap.exists()?snap.data():null;if(current?.state==="read")return{state:"read",readAt:current.readAt||null};if(state==="delivered"&&current?.state==="delivered")return{state:"delivered"};const nextRevision=Number(message.receiptRevision||0)+1,now=s.fsSdk.serverTimestamp();tx.update(messageRef,{receiptRevision:nextRevision});if(state==="read"){if(snap.exists())tx.update(ref,{state:"read",updatedAt:now,readAt:now});else tx.set(ref,{uid:authUser.uid,state:"read",updatedAt:now,readAt:now});}else{if(snap.exists())throw new Error("Group receipt cannot regress or repeat.");tx.set(ref,{uid:authUser.uid,state:"delivered",updatedAt:now});}return{state};});}
export function subscribeCloudGroupReceipts(groupId,messageId,onRows,onError){let active=true,unsub=()=>{};readCloudGroupAuthority(groupId).then(async()=>{const s=await ensureServices();if(!active)return;unsub=s.fsSdk.onSnapshot(s.fsSdk.collection(s.db,"groups",groupId,"messages",messageId,"receipts"),snap=>{if(active)onRows?.(snap.docs.map(d=>({uid:d.id,...d.data()})));},err=>{if(active)onError?.(err);});}).catch(err=>{if(active)onError?.(err);});return()=>{active=false;unsub();};}

export async function getCloudConversation(conversationId,myUid){const s=await ensureServices();if(!authUser||authUser.uid!==myUid)throw new Error("Sign in first.");const snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"conversations",conversationId));if(!snap.exists())return null;const x=snap.data(),members=Array.isArray(x.members)?x.members:[];if(!members.includes(myUid))throw new Error("Conversation is not available to this account.");const other=members.find(m=>m!==myUid)||null;return{id:snap.id,cloud:true,type:x.type||"direct",peerUid:other,name:x.memberNames?.[other]||"FIDUNIO contact",preview:"Cloud conversation",time:""};}
export async function getCloudConversationFromServer(conversationId,myUid){const s=await ensureServices();if(!authUser||authUser.uid!==myUid)throw new Error("Sign in first.");const snap=await s.fsSdk.getDocFromServer(s.fsSdk.doc(s.db,"conversations",conversationId));if(!snap.exists())return null;const x=snap.data(),members=Array.isArray(x.members)?x.members:[];if(!members.includes(myUid))throw new Error("Conversation is not available to this account.");const other=members.find(m=>m!==myUid)||null;return{id:snap.id,cloud:true,type:x.type||"direct",peerUid:other,name:x.memberNames?.[other]||"FIDUNIO contact",preview:"Cloud conversation",time:""};}
export async function publishCloudE2EEPublicKey(uid,publicJwk){const s=await ensureServices();if(!authUser||authUser.uid!==uid)throw new Error("Cannot publish another user's encryption key.");await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"users",uid),{e2eePublicJwk:publicJwk,e2eeVersion:1,e2eeUpdatedAt:s.fsSdk.serverTimestamp()},{merge:true});}export async function publishCloudE2EEDevice(uid,device){const s=await ensureServices();if(!authUser||authUser.uid!==uid)throw new Error("Cannot publish another user's device key.");if(!device?.deviceId||!device?.publicJwk)throw new Error("Device identity is incomplete.");await s.fsSdk.setDoc(s.fsSdk.doc(s.db,"users",uid,"devices",device.deviceId),{uid,deviceId:device.deviceId,label:device.label||"FIDUNIO Web device",e2eeVersion:1,publicJwk:device.publicJwk,fingerprint:device.fingerprint||"",createdAt:device.createdAt||Date.now(),lastSeenAt:s.fsSdk.serverTimestamp(),active:true},{merge:true});}export async function getCloudUserDevices(uid){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const snap=await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"users",uid,"devices"));return snap.docs.map(d=>({id:d.id,...d.data()}));}export async function deactivateOtherCloudE2EEDevices(uid,keepDeviceId){const s=await ensureServices();if(!authUser||authUser.uid!==uid)throw new Error("Cannot clean another user's device registry.");if(!keepDeviceId)throw new Error("Current device identity is required.");const snap=await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"users",uid,"devices"));const batch=s.fsSdk.writeBatch(s.db);let changed=0;for(const d of snap.docs){if(d.id===keepDeviceId)continue;const row=d.data();if(row.active===false)continue;batch.set(d.ref,{active:false,revokedAt:s.fsSdk.serverTimestamp(),revokedReason:"test-baseline-cleanup"},{merge:true});changed++;}if(changed)await batch.commit();return{deactivated:changed,keptDeviceId:keepDeviceId};}
export async function getCloudE2EEDiagnosticSnapshot(){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const q=s.fsSdk.query(s.fsSdk.collection(s.db,"conversations"),s.fsSdk.where("members","array-contains",authUser.uid));const convSnap=await s.fsSdk.getDocs(q);const conversations=[];for(const d of convSnap.docs){const x=d.data(),members=Array.isArray(x.members)?x.members:[],other=members.find(uid=>uid!==authUser.uid)||null,msgQ=s.fsSdk.query(s.fsSdk.collection(s.db,"conversations",d.id,"messages"),s.fsSdk.orderBy("createdAt","asc"));const msgSnap=await s.fsSdk.getDocs(msgQ);const messages=msgSnap.docs.map(m=>{const r=m.data(),envelopes=r.envelopes&&typeof r.envelopes==="object"?Object.keys(r.envelopes):[];return{id:m.id,e2ee:Number(r.e2ee||0),senderUid:r.senderUid||"",senderDeviceId:r.senderDeviceId||"",senderDevicePublicJwk:r.senderDevicePublicJwk||null,envelopeDeviceIds:envelopes,recipientDeviceIds:Array.isArray(r.recipientDeviceIds)?r.recipientDeviceIds:[],state:r.state||"sent",timeLabel:r.timeLabel||""};});conversations.push({id:d.id,peerUid:other,name:x.memberNames?.[other]||"FIDUNIO contact",messages});}return{uid:authUser.uid,email:authUser.email||"",conversations};}
export async function sendCloudMessage(conversationId,message){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const ref=s.fsSdk.doc(s.db,"conversations",conversationId,"messages",message.id);const row={senderUid:authUser.uid,senderName:authUser.displayName||authUser.email||"User",timeLabel:message.timeLabel,state:message.state||"sent",createdAt:s.fsSdk.serverTimestamp()};const disappearAfterSeconds=normalizeDisappearSelection(message.disappearAfterSeconds);if(disappearAfterSeconds!==null)row.disappearAfterSeconds=disappearAfterSeconds;if(message.disappearingPurgeVersion===1&&disappearAfterSeconds!==null)row.disappearingPurgeVersion=1;if(message.senderDeviceId)row.senderDeviceId=message.senderDeviceId;if(message.senderDevicePublicJwk)row.senderDevicePublicJwk=message.senderDevicePublicJwk;if(message.e2ee){row.e2ee=message.e2ee;row.ciphertext=message.ciphertext||"";row.iv=message.iv||"";row.text="";if(message.kdfVersion)row.kdfVersion=message.kdfVersion;if(message.senderKeyId)row.senderKeyId=message.senderKeyId;if(message.recipientKeyId)row.recipientKeyId=message.recipientKeyId;if(message.envelopes&&typeof message.envelopes==="object")row.envelopes=message.envelopes;if(message.recipientDeviceIds)row.recipientDeviceIds=message.recipientDeviceIds;}else row.text=message.text||"";await s.fsSdk.setDoc(ref,row);await s.fsSdk.updateDoc(s.fsSdk.doc(s.db,"conversations",conversationId),{updatedAt:s.fsSdk.serverTimestamp()});}
export async function updateCloudMessageState(conversationId,messageId,state){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");if(!["delivered","read"].includes(state))throw new Error("Invalid direct receipt state.");const ref=s.fsSdk.doc(s.db,"conversations",conversationId,"messages",messageId);return s.fsSdk.runTransaction(s.db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error("Message was not found.");const current=snap.data();if(current.senderUid===authUser.uid)throw new Error("Sender cannot write recipient receipt authority.");if(current.state==="read")return{state:"read",readAt:current.readAt||null};if(state==="delivered"){if(current.state==="delivered")return{state:"delivered"};if(current.state!=="sent")throw new Error("Direct receipt cannot regress.");tx.update(ref,{state:"delivered"});return{state:"delivered"};}if(!["sent","delivered"].includes(current.state))throw new Error("Direct receipt cannot advance from current state.");tx.update(ref,{state:"read",readAt:s.fsSdk.serverTimestamp()});return{state:"read"};});}
export async function markCloudConversationRead(conversationId){const s=await ensureServices();if(!authUser)return;const q=s.fsSdk.query(s.fsSdk.collection(s.db,"conversations",conversationId,"messages"),s.fsSdk.orderBy("createdAt","asc"));const snap=await s.fsSdk.getDocsFromServer(q);const pending=snap.docs.filter(d=>{const x=d.data();return x.senderUid!==authUser.uid&&(x.state||"sent")!=="read";});await Promise.all(pending.map(d=>updateCloudMessageState(conversationId,d.id,"read")));}
export function subscribeMyConversations(uid,onRows,onError){let active=true,unsub=()=>{};ensureServices().then(s=>{if(!active)return;const q=s.fsSdk.query(s.fsSdk.collection(s.db,"conversations"),s.fsSdk.where("members","array-contains",uid));unsub=s.fsSdk.onSnapshot(q,snap=>onRows(snap.docs.map(d=>{const x=d.data(),other=(x.members||[]).find(m=>m!==uid);return{id:d.id,cloud:true,type:"direct",peerUid:other,name:x.memberNames?.[other]||"FIDUNIO contact",preview:"Cloud conversation",time:"",updatedAtMs:x.updatedAt?.toMillis?.()||0};}),{fromCache:!!snap.metadata?.fromCache,hasPendingWrites:!!snap.metadata?.hasPendingWrites}),onError);}).catch(onError);return()=>{active=false;unsub();};}
export function subscribeConversationMessages(conversationId,myUid,onRows,onError){
  const key=String(conversationId),token=Symbol(key);
  let stream=messageStreams.get(key);
  if(stream){
    if(stream.closeTimer){clearTimeout(stream.closeTimer);stream.closeTimer=null;}
    // Re-entry only transfers callback ownership. The existing live listener is
    // already authoritative and must not be raced by a duplicate getDocs read.
    stream.token=token;stream.onRows=onRows;stream.onError=onError;stream.owner.setCallbacks(onRows,onError);
  }else{
    stream={token,onRows,onError,owner:createDirectMessageDeliveryOwner({deliver:onRows,onError}),unsub:()=>{},closeTimer:null};
    messageStreams.set(key,stream);
    ensureServices().then(s=>{
      if(messageStreams.get(key)!==stream)return;
      const q=s.fsSdk.query(s.fsSdk.collection(s.db,"conversations",conversationId,"messages"),s.fsSdk.orderBy("createdAt","asc"));
      stream.unsub=s.fsSdk.onSnapshot(q,{includeMetadataChanges:true},snap=>{
        if(messageStreams.get(key)!==stream)return;
        const rows=snap.docs.map(d=>({id:d.id,...d.data()}));
        stream.owner.offerSnapshot(rows,{fromCache:!!snap.metadata?.fromCache,hasPendingWrites:!!snap.metadata?.hasPendingWrites});
      },err=>{if(messageStreams.get(key)===stream)stream.onError?.(err);});
    }).catch(err=>{if(messageStreams.get(key)===stream)stream.onError?.(err);});
  }
  return()=>{const current=messageStreams.get(key);if(current!==stream||current.token!==token)return;current.closeTimer=setTimeout(()=>{const latest=messageStreams.get(key);if(latest!==stream||latest.token!==token)return;latest.unsub();latest.owner.close();messageStreams.delete(key);},250);};
}
export async function prioritizeConversationMessage(conversationId,myUid,messageId){
  const s=await ensureServices();
  if(!authUser||authUser.uid!==myUid)throw new Error("Sign in first.");
  const key=String(conversationId||""),id=String(messageId||"");
  if(!key||!id)throw new Error("Notification message identity is incomplete.");
  const stream=messageStreams.get(key);
  if(!stream)throw new Error("Direct-message delivery owner is not active.");
  const snap=await s.fsSdk.getDocFromServer(s.fsSdk.doc(s.db,"conversations",key,"messages",id));
  if(!snap.exists())throw new Error("Notified message is not available yet.");
  const current=messageStreams.get(key);
  if(current!==stream)throw new Error("Direct-message delivery owner changed during notification recovery.");
  return stream.owner.offerPriority(id,[{id:snap.id,...snap.data()}],{fromCache:false,hasPendingWrites:false,partial:true,priorityMessageId:id});
}
export function subscribeUserDisplayNames(uids,onNames,onError){let active=true;const stops=[];const names=new Map();const wanted=[...new Set((uids||[]).map(x=>String(x||"").trim()).filter(Boolean))];const emit=()=>{if(active)onNames?.(Object.fromEntries(names));};ensureServices().then(s=>{if(!active)return;if(!authUser)throw new Error("Sign in first.");if(!wanted.length){emit();return;}for(const uid of wanted){const stop=s.fsSdk.onSnapshot(s.fsSdk.doc(s.db,"users",uid),snap=>{if(!active)return;if(snap.exists()){const name=String(snap.data()?.displayName||snap.data()?.email||"").trim();if(name)names.set(uid,name);else names.delete(uid);}else names.delete(uid);emit();},err=>{if(active)onError?.(err);});stops.push(stop);}}).catch(err=>{if(active)onError?.(err);});return()=>{active=false;for(const stop of stops.splice(0))try{stop();}catch{}names.clear();};}

// BEGIN ACCOUNT E2EE V1 CENTRAL FIREBASE API
export async function readCloudAccountE2EEIdentity(uid){const s=await ensureServices();if(!authUser||authUser.uid!==uid)throw new Error("Authenticated account does not match E2EE identity owner.");const snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"users",uid,"e2ee","identity"));return snap.exists()?{...snap.data()}:null;}
export async function createCloudAccountE2EEIdentity(uid,privateIdentity,publicIdentity){const s=await ensureServices();if(!authUser||authUser.uid!==uid)throw new Error("Authenticated account does not match E2EE identity owner.");if(!privateIdentity||!publicIdentity)throw new Error("Account E2EE identity material is incomplete.");const privateRef=s.fsSdk.doc(s.db,"users",uid,"e2ee","identity"),publicRef=s.fsSdk.doc(s.db,"e2eePublicKeys",uid);return s.fsSdk.runTransaction(s.db,async tx=>{const privateSnap=await tx.get(privateRef),publicSnap=await tx.get(publicRef);if(privateSnap.exists()||publicSnap.exists())throw new Error("Durable E2EE identity already exists or is partially established; automatic replacement is forbidden.");const now=s.fsSdk.serverTimestamp();tx.set(privateRef,{...privateIdentity,createdAt:now,updatedAt:now});tx.set(publicRef,{...publicIdentity,createdAt:now,updatedAt:now});return{revision:1};});}
export async function updateCloudAccountE2EENormalWrapper(uid,keyId,expectedRevision,normalWrapper){const s=await ensureServices();if(!authUser||authUser.uid!==uid)throw new Error("Authenticated account does not match E2EE identity owner.");const ref=s.fsSdk.doc(s.db,"users",uid,"e2ee","identity");return s.fsSdk.runTransaction(s.db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error("Durable E2EE identity is missing.");const current=snap.data();if(current.keyId!==keyId)throw new Error("E2EE identity keyId changed; update aborted.");if(current.revision!==expectedRevision)throw new Error("E2EE identity revision changed; reload before retrying.");tx.update(ref,{normalWrapper,revision:expectedRevision+1,updatedAt:s.fsSdk.serverTimestamp()});return{revision:expectedRevision+1};});}
export async function getCloudAccountE2EEPublicKey(uid){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const snap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"e2eePublicKeys",uid));return snap.exists()?{uid:snap.id,...snap.data()}:null;}
// END ACCOUNT E2EE V1 CENTRAL FIREBASE API

// Restart/reconnect anti-resurrection probes. These functions deliberately use
// Firestore server reads rather than cache reads; they expose only current source
// message IDs to the app controller and do not mutate Firebase state.
export async function readCloudMessageIdsFromServer(conversationId,myUid){const s=await ensureServices();if(!authUser||authUser.uid!==myUid)throw new Error("Sign in first.");const cid=String(conversationId||"").trim();if(!cid)throw new Error("Conversation is required.");const conv=await s.fsSdk.getDocFromServer(s.fsSdk.doc(s.db,"conversations",cid));if(!conv.exists())throw new Error("Conversation is not available to this account.");const members=Array.isArray(conv.data().members)?conv.data().members:[];if(!members.includes(myUid))throw new Error("Conversation is not available to this account.");const snap=await s.fsSdk.getDocsFromServer(s.fsSdk.collection(s.db,"conversations",cid,"messages"));return snap.docs.map(d=>d.id);}
export async function readCloudGroupMessageIdsFromServer(groupId){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim();if(!gid)throw new Error("Group is required.");const group=await s.fsSdk.getDocFromServer(s.fsSdk.doc(s.db,"groups",gid));if(!group.exists())throw new Error("Group is not available to this account.");const members=Array.isArray(group.data().memberUids)?group.data().memberUids:[];if(!members.includes(authUser.uid))throw new Error("Group is not available to this account.");const snap=await s.fsSdk.getDocsFromServer(s.fsSdk.collection(s.db,"groups",gid,"messages"));return snap.docs.map(d=>d.id);}

export async function uploadEncryptedAttachment({paths,manifest,chunks}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");if(!paths?.manifest||!Array.isArray(paths.chunks)||paths.chunks.length!==chunks?.length)throw new Error("Invalid attachment upload plan.");const enc=new TextEncoder(),manifestRef=s.storageSdk.ref(s.storage,paths.manifest),chunkRefs=paths.chunks.map(path=>s.storageSdk.ref(s.storage,path));await s.storageSdk.uploadBytes(manifestRef,enc.encode(JSON.stringify(manifest)),{contentType:"application/json",customMetadata:{fidunioFormat:"attachment-v1"}});for(let i=0;i<chunks.length;i++)await s.storageSdk.uploadBytes(chunkRefs[i],enc.encode(JSON.stringify(chunks[i])),{contentType:"application/octet-stream",customMetadata:{fidunioFormat:"attachment-v1-ciphertext"}});await Promise.all([s.storageSdk.getMetadata(manifestRef),...chunkRefs.map(ref=>s.storageSdk.getMetadata(ref))]);return true;}

export async function downloadEncryptedAttachment(paths){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");if(!paths?.manifest||!Array.isArray(paths.chunks)||!paths.chunks.length)throw new Error("Invalid attachment download plan.");const read=async(path,label)=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const ref=s.storageSdk.ref(s.storage,path),url=await Promise.race([s.storageSdk.getDownloadURL(ref),new Promise((_,reject)=>setTimeout(()=>reject(Object.assign(new Error("URL lookup timed out"),{code:"storage/url-timeout"})),10000))]),response=await fetch(url,{cache:"no-store",signal:controller.signal});if(!response.ok)throw Object.assign(new Error(`HTTP ${response.status}`),{code:`storage/http-${response.status}`});const buffer=await response.arrayBuffer();if(buffer.byteLength>1048576)throw Object.assign(new Error("stored object exceeds limit"),{code:"storage/object-too-large"});try{return JSON.parse(new TextDecoder().decode(buffer));}catch{throw Object.assign(new Error("invalid stored data"),{code:"attachment/invalid-json"});}}catch(err){const code=err?.name==="AbortError"?"storage/fetch-timeout":String(err?.code||"storage/unknown");throw new Error(`${label} download failed (${code}): ${err?.message||"unknown error"}`,{cause:err});}finally{clearTimeout(timer);}};const manifest=await read(paths.manifest,"Manifest"),chunks=new Array(paths.chunks.length),workers=Math.min(6,paths.chunks.length);let next=0;await Promise.all(Array.from({length:workers},async()=>{while(next<paths.chunks.length){const index=next++;chunks[index]=await read(paths.chunks[index],`Chunk ${index+1}`);}}));return{manifest,chunks};}
