import {readFileSync} from 'node:fs';import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';import {doc,getDoc,setDoc,updateDoc,deleteDoc,serverTimestamp} from 'firebase/firestore';
const rules=readFileSync(new URL('./firestore.rules',import.meta.url),'utf8'),env=await initializeTestEnvironment({projectId:'demo-fidunio-notification-rules',firestore:{rules}}),A='user-a',B='user-b',dbA=env.authenticatedContext(A).firestore(),dbB=env.authenticatedContext(B).firestore(),dbN=env.unauthenticatedContext().firestore();let bad=0;async function t(n,f){try{await f();console.log('PASS',n)}catch(e){bad++;console.error('FAIL',n,e.message)}}
await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,'users',A),{displayName:'A',email:'a@example.test',systemRole:'user',active:true,status:'active'});await setDoc(doc(db,'users',B),{displayName:'B',email:'b@example.test',systemRole:'user',active:true,status:'active'});});
const ID='install-12345678',refA=doc(dbA,'users',A,'notificationDevices',ID);const valid=()=>({installationId:ID,fcmToken:'x'.repeat(80),platform:'ios-pwa',enabled:true,showSenderName:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()});
await t('owner creates own notification installation',()=>assertSucceeds(setDoc(refA,valid())));await t('owner creates native iOS notification installation',()=>assertSucceeds(setDoc(doc(dbA,'users',A,'notificationDevices','install-native12'),{...valid(),installationId:'install-native12',platform:'ios-native'})));await t('owner reads own notification installation',()=>assertSucceeds(getDoc(refA)));await t('other UID cannot read notification installation',()=>assertFails(getDoc(doc(dbB,'users',A,'notificationDevices',ID))));await t('anonymous cannot read notification installation',()=>assertFails(getDoc(doc(dbN,'users',A,'notificationDevices',ID))));await t('other UID cannot write notification installation',()=>assertFails(setDoc(doc(dbB,'users',A,'notificationDevices','install-87654321'),{...valid(),installationId:'install-87654321'})));await t('unexpected field denied',()=>assertFails(setDoc(doc(dbA,'users',A,'notificationDevices','install-extra123'),{...valid(),installationId:'install-extra123',messagePreview:'secret'})));await t('invalid token denied',()=>assertFails(setDoc(doc(dbA,'users',A,'notificationDevices','install-short123'),{...valid(),installationId:'install-short123',fcmToken:'short'})));await t('invalid platform denied',()=>assertFails(setDoc(doc(dbA,'users',A,'notificationDevices','install-platform'),{...valid(),installationId:'install-platform',platform:'unknown'})));await t('owner enables sender-name presentation',()=>assertSucceeds(updateDoc(refA,{showSenderName:true,updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()})));await t('non-boolean sender-name preference denied',()=>assertFails(updateDoc(refA,{showSenderName:'yes',updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()})));await t('owner rotates own token',()=>assertSucceeds(updateDoc(refA,{fcmToken:'y'.repeat(90),platform:'ios-pwa',enabled:true,showSenderName:true,updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()})));await t('owner cannot change installationId',()=>assertFails(updateDoc(refA,{installationId:'install-other999',updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()})));await t('other UID cannot delete',()=>assertFails(deleteDoc(doc(dbB,'users',A,'notificationDevices',ID))));await env.withSecurityRulesDisabled(async c=>{await setDoc(doc(c.firestore(),'users',A,'notificationDevices','lease-12345678'),{installationId:'lease-12345678',fcmToken:'z'.repeat(80),platform:'ios-pwa',enabled:true,showSenderName:false,createdAt:new Date(),updatedAt:new Date(),generation:2,lastSeenMs:123,leaseId:'lease-example',leaseUntilMs:456,ownerUid:A});});
const leaseRef=doc(dbA,'users',A,'notificationDevices','lease-12345678');
await t('lease-shaped record permits sender-name only update',()=>assertSucceeds(updateDoc(leaseRef,{showSenderName:true,updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()})));
await t('lease-shaped record rejects token change without full validation',()=>assertFails(updateDoc(leaseRef,{fcmToken:'w'.repeat(80),updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()})));
await t('lease-shaped record rejects lease ownership change',()=>assertFails(updateDoc(leaseRef,{ownerUid:B,showSenderName:false,updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()})));
await t('other user cannot update lease-shaped sender-name',()=>assertFails(updateDoc(doc(dbB,'users',A,'notificationDevices','lease-12345678'),{showSenderName:false,updatedAt:serverTimestamp(),lastSeenAt:serverTimestamp()})));
await t('owner deletes own installation',()=>assertSucceeds(deleteDoc(refA)));await env.cleanup();if(bad)process.exitCode=1;
