import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
const app=readFileSync("app.js","utf8");
const css=readFileSync("styles.css","utf8");
assert.ok(app.includes('const groupSender=groupSenderDisplayName(m,c)'),"group sender identity owner must remain unchanged");
assert.ok(app.includes('function messageDisplayTime(m)'),"group sender time must have one display-time resolver");
assert.ok(app.includes('const explicit=String(m?.time||"").trim()'),"existing explicit message time remains first choice");
assert.ok(app.includes('messageCalendarDate(m?.createdAt)'),"server-projected historical rows must fall back to createdAt");
assert.ok(app.includes('hour:"numeric",minute:"2-digit"'),"createdAt fallback must format a human message time");
assert.ok(app.includes('<span class="sender-name">${esc(groupSender)}</span><span class="sender-time">${esc(displayTime)}</span>'),"group creator name must show resolved message time beside it");
assert.ok(app.includes('function renderConversationMessages(msgs,c)'),"date separators must remain intact");
assert.ok(css.includes('.sender-label .sender-time'),"sender-line time styling must remain intact");
console.log("Group sender-time gate passed");
