/* FIDUNIO invitation creation and invitation management. */
import { createFidunioInvitation } from "./firebase.js";
const SDK_VERSION="12.18.0";let apiPromise=null;
function esc(s=""){return String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function prettyRole(role){return role==="admin"?"Admin":"User";}
function closeInviteModal(){document.querySelector("#fidunioInviteModal")?.remove();}
function guideUrl(){return new URL("quick-start.html",location.href).href;}
function inviteSubject(){return "You're invited to join FIDUNIO";}
function inviteMessage(invite){const inviter=invite.invitedByName||"A FIDUNIO administrator";return `You're invited to FIDUNIO — Private Messaging\n\n${inviter} has invited you to join FIDUNIO, an invitation-only private messaging app for one-to-one and group conversations.\n\nYour role: ${prettyRole(invite.role)}\nInvitation expires: ${invite.expiresAt.toLocaleString()}\n\nJOIN FIDUNIO\n${invite.link}\n\nThis invitation is personal and can be used only once. After your account is created, the invitation becomes invalid. Please do not forward the invitation link.\n\nQUICK START GUIDE\n${guideUrl()}\n\nThe guide explains account setup, privacy and security basics, messaging, device identity, and PIN/biometric unlocking.\n\nFIDUNIO • Private Messaging`;}
function emailInvitation(invite){location.href=`mailto:?subject=${encodeURIComponent(inviteSubject())}&body=${encodeURIComponent(inviteMessage(invite))}`;}
async function api(){if(apiPromise)return apiPromise;apiPromise=Promise.all([import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${SDK_VERSION}/firebase-firestore.js`)]).then(([appSdk,authSdk,fsSdk])=>{const app=appSdk.getApp();return{auth:authSdk.getAuth(app),db:fsSdk.getFirestore(app),fsSdk};});return apiPromise;}
async function pendingInvites(){const s=await api(),snap=await s.fsSdk.getDocs(s.fsSdk.collection(s.db,"invitations"));return snap.docs.map(d=>({id:d.id,...d.data()})).filter(i=>i.status==="pending").sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));}
async function revokeInvite(id){const s=await api();await s.fsSdk.updateDoc(s.fsSdk.doc(s.db,"invitations",id),{status:"revoked",revokedAt:s.fsSdk.serverTimestamp()});}
function dateText(ts){const d=ts?.toDate?.();return d?d.toLocaleString():"Unknown";}
async function refreshPending(admin){let box=admin.querySelector("#pendingInviteList");if(!box)return;box.innerHTML='<p class="small-note">Loading invitations…</p>';try{const rows=await pendingInvites();box.innerHTML=rows.length?rows.map(i=>`<div class="admin-invite-row"><div><strong>${esc(prettyRole(i.role))} invitation</strong><span>${esc(i.invitedByName||"Administrator")} • Expires ${esc(dateText(i.expiresAt))}</span></div><button class="row-action invitationRevokeBtn" type="button" data-id="${esc(i.id)}">Revoke</button></div>`).join(""):'<p class="small-note">No pending invitations.</p>';box.querySelectorAll(".invitationRevokeBtn").forEach(btn=>btn.onclick=async e=>{e.preventDefault();e.stopPropagation();btn.disabled=true;btn.textContent="Revoking…";try{await revokeInvite(btn.dataset.id);await refreshPending(admin);}catch(err){btn.disabled=false;btn.textContent="Revoke";alert(err?.message||String(err));}});}catch(err){box.innerHTML=`<p class="warning-note">${esc(err?.message||String(err))}</p>`;}}
function renderInviteResult(admin,invite){const result=admin.querySelector("#inviteResult");if(!result)return;result.innerHTML=`<div class="permission-box" style="margin-top:14px"><strong>Single-use ${esc(prettyRole(invite.role))} invitation</strong><div class="uid-box" style="margin-top:8px;word-break:break-all">${esc(invite.link)}</div><p class="small-note" style="margin:10px 0 0">Expires ${esc(invite.expiresAt.toLocaleString())}. The shared message includes FIDUNIO information and the Quick Start Guide.</p><div class="auth-actions" style="margin-top:10px"><button class="secondary" id="copyInviteBtn">Copy Invitation</button><button class="secondary" id="emailInviteBtn">Email Invitation</button>${navigator.share?'<button class="secondary" id="shareInviteBtn">Share…</button>':""}</div><a class="secondary" href="${esc(guideUrl())}" target="_blank" rel="noopener" style="display:flex;text-decoration:none;margin-top:10px;align-items:center;justify-content:center">View Quick Start Guide</a></div>`;result.querySelector("#copyInviteBtn").onclick=async e=>{const text=inviteMessage(invite);try{await navigator.clipboard.writeText(text);e.currentTarget.textContent="Copied";}catch{prompt("Copy FIDUNIO invitation:",text);}};result.querySelector("#emailInviteBtn").onclick=e=>{e.preventDefault();e.stopPropagation();emailInvitation(invite);};const share=result.querySelector("#shareInviteBtn");if(share)share.onclick=e=>{e.preventDefault();e.stopPropagation();navigator.share({title:inviteSubject(),text:inviteMessage(invite)}).catch(()=>{});};refreshPending(admin);}
function openInviteModal(admin){closeInviteModal();const host=document.createElement("div");host.id="fidunioInviteModal";host.className="modal-backdrop";host.innerHTML=`<div class="modal" style="max-width:640px"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><h2 style="margin:0">Create Invitation</h2><button class="text-btn" id="inviteModalX" aria-label="Close" style="font-size:28px;line-height:1">×</button></div><p class="small-note">Choose the new user's role and how long the invitation should remain valid.</p><label class="form-label" for="modalInviteRole">New user's role</label><select class="text-input" id="modalInviteRole"><option value="user">User</option><option value="admin">Admin</option></select><label class="form-label" for="modalInviteDays">Expires</label><select class="text-input" id="modalInviteDays"><option value="1">1 day</option><option value="7" selected>7 days</option><option value="30">30 days</option></select><div class="permission-box" style="margin-top:14px"><p class="small-note" style="margin:0">ⓘ The recipient gets the Join link plus a public Quick Start Guide link.</p></div><div class="modal-actions"><button class="modal-cancel" id="inviteModalCancel">Cancel</button><button class="modal-confirm" id="inviteModalCreate">Create Invitation</button></div><div id="inviteModalNote"></div></div>`;document.body.appendChild(host);host.onclick=e=>{if(e.target===host)closeInviteModal();};host.querySelector("#inviteModalX").onclick=closeInviteModal;host.querySelector("#inviteModalCancel").onclick=closeInviteModal;host.querySelector("#inviteModalCreate").onclick=async()=>{const btn=host.querySelector("#inviteModalCreate"),note=host.querySelector("#inviteModalNote");btn.disabled=true;btn.textContent="Creating…";try{const invite=await createFidunioInvitation(host.querySelector("#modalInviteRole").value,Number(host.querySelector("#modalInviteDays").value));renderInviteResult(admin,invite);closeInviteModal();}catch(err){note.innerHTML=`<p class="warning-note">${esc(err?.message||String(err))}</p>`;btn.disabled=false;btn.textContent="Create Invitation";}};}
function polishInvitationCard(){const admin=document.querySelector("#fidunioInvitationAdmin");if(!admin)return;let pending=admin.querySelector("#pendingInviteList");if(!pending){pending=document.createElement("div");pending.id="pendingInviteList";pending.style.marginTop="14px";admin.appendChild(pending);refreshPending(admin);}const btn=admin.querySelector("#createInviteBtn");if(!btn)return;const role=admin.querySelector("#inviteRole"),days=admin.querySelector("#inviteDays"),roleLabel=role?.previousElementSibling,daysLabel=days?.previousElementSibling;if(role)role.style.display="none";if(days)days.style.display="none";if(roleLabel?.classList?.contains("form-label"))roleLabel.style.display="none";if(daysLabel?.classList?.contains("form-label"))daysLabel.style.display="none";btn.onclick=e=>{e.preventDefault();e.stopPropagation();openInviteModal(admin);};}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;polishInvitationCard();});}const observer=new MutationObserver(schedule);observer.observe(document.documentElement,{subtree:true,childList:true});polishInvitationCard();
