/* FIDUNIO invitation creation modal. Keep creation simple; enrich the actual shared message. */
import { createFidunioInvitation } from "./firebase.js";
function esc(s=""){return String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function prettyRole(role){return role==="admin"?"Admin":"User";}
function closeInviteModal(){document.querySelector("#fidunioInviteModal")?.remove();}
function guideUrl(){return new URL("quick-start.html",location.href).href;}
function inviteSubject(){return "You're invited to join FIDUNIO";}
function inviteMessage(invite){const inviter=invite.invitedByName||"A FIDUNIO administrator";return `You're invited to join FIDUNIO\n\n${inviter} has invited you to FIDUNIO — Private Messaging, an invitation-only app for private one-to-one and group conversations.\n\nYour role: ${prettyRole(invite.role)}\nInvitation expires: ${invite.expiresAt.toLocaleString()}\n\nJOIN FIDUNIO\n${invite.link}\n\nThis invitation is personal and single-use. After your account is created, the invitation becomes invalid. Please do not forward the Join link.\n\nQUICK START GUIDE\n${guideUrl()}\n\nYou can open the Quick Start Guide before joining. It explains account setup, privacy and security basics, messaging, device identity, and PIN/biometric unlocking.\n\nFIDUNIO • Private Messaging`;}
function emailInvitation(invite){const subject=encodeURIComponent(inviteSubject()),body=encodeURIComponent(inviteMessage(invite));location.href=`mailto:?subject=${subject}&body=${body}`;}
function renderInviteResult(admin,invite){const result=admin.querySelector("#inviteResult");if(!result)return;result.innerHTML=`<div class="permission-box" style="margin-top:14px"><strong>Single-use ${esc(prettyRole(invite.role))} invitation</strong><div class="uid-box" style="margin-top:8px;word-break:break-all">${esc(invite.link)}</div><p class="small-note" style="margin:10px 0 0">Expires ${esc(invite.expiresAt.toLocaleString())}. The shared message includes FIDUNIO information and the Quick Start Guide.</p><div class="auth-actions" style="margin-top:10px"><button class="secondary" id="copyInviteBtn">Copy Invitation</button><button class="secondary" id="emailInviteBtn">Email Invitation</button>${navigator.share?'<button class="secondary" id="shareInviteBtn">Share…</button>':""}</div><a class="secondary" href="${esc(guideUrl())}" target="_blank" rel="noopener" style="display:flex;text-decoration:none;margin-top:10px;align-items:center;justify-content:center">View Quick Start Guide</a></div>`;const copy=result.querySelector("#copyInviteBtn");copy.onclick=async e=>{e.preventDefault();e.stopPropagation();const text=inviteMessage(invite);try{await navigator.clipboard.writeText(text);e.currentTarget.textContent="Copied";}catch{prompt("Copy FIDUNIO invitation:",text);}};result.querySelector("#emailInviteBtn").onclick=e=>{e.preventDefault();e.stopPropagation();emailInvitation(invite);};const share=result.querySelector("#shareInviteBtn");if(share)share.onclick=e=>{e.preventDefault();e.stopPropagation();navigator.share({title:inviteSubject(),text:inviteMessage(invite)}).catch(()=>{});};}
function openInviteModal(admin){document.querySelector("#fidunioAdminModal")?.remove();document.querySelector("#fidunioInviteModal")?.remove();const host=document.createElement("div");host.id="fidunioInviteModal";host.className="modal-backdrop";host.innerHTML=`<div class="modal" style="max-width:640px"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><h2 style="margin:0">Create Invitation</h2><button class="text-btn" id="inviteModalX" aria-label="Close" style="font-size:28px;line-height:1">×</button></div><p class="small-note">Choose the new user's role and how long the invitation should remain valid.</p><label class="form-label" for="modalInviteRole">New user's role</label><select class="text-input" id="modalInviteRole"><option value="user">User</option><option value="admin">Admin</option></select><label class="form-label" for="modalInviteDays">Expires</label><select class="text-input" id="modalInviteDays"><option value="1">1 day</option><option value="7" selected>7 days</option><option value="30">30 days</option></select><div class="permission-box" style="margin-top:14px"><p class="small-note" style="margin:0">ⓘ The recipient will receive a FIDUNIO introduction, the single-use Join link, expiration details, and a Quick Start Guide link they can read before joining.</p></div><div class="modal-actions"><button class="modal-cancel" id="inviteModalCancel">Cancel</button><button class="modal-confirm" id="inviteModalCreate">Create Invitation</button></div><div id="inviteModalNote"></div></div>`;document.body.appendChild(host);host.addEventListener("click",e=>{e.stopPropagation();if(e.target===host)closeInviteModal();});host.querySelector("#inviteModalX").onclick=e=>{e.preventDefault();e.stopPropagation();closeInviteModal();};host.querySelector("#inviteModalCancel").onclick=e=>{e.preventDefault();e.stopPropagation();closeInviteModal();};host.querySelector("#inviteModalCreate").onclick=async e=>{e.preventDefault();e.stopPropagation();const btn=host.querySelector("#inviteModalCreate"),note=host.querySelector("#inviteModalNote");btn.disabled=true;btn.textContent="Creating…";try{const role=host.querySelector("#modalInviteRole").value,days=Number(host.querySelector("#modalInviteDays").value),invite=await createFidunioInvitation(role,days);renderInviteResult(admin,invite);btn.textContent="Created";/* Keep the modal in place until this tap/click is fully finished. This avoids iPad Safari sending the release through to controls underneath. */setTimeout(()=>closeInviteModal(),300);}catch(err){note.innerHTML=`<p class="warning-note">${esc(err?.message||String(err))}</p>`;btn.disabled=false;btn.textContent="Create Invitation";}};}
function polishInvitationCard(){const admin=document.querySelector("#fidunioInvitationAdmin");if(!admin)return;const btn=admin.querySelector("#createInviteBtn");if(!btn||btn.dataset.fidunioModalized==="1")return;btn.dataset.fidunioModalized="1";const role=admin.querySelector("#inviteRole"),days=admin.querySelector("#inviteDays"),roleLabel=role?.closest("label")||role?.previousElementSibling,daysLabel=days?.closest("label")||days?.previousElementSibling;if(role)role.style.display="none";if(days)days.style.display="none";if(roleLabel?.classList?.contains("form-label"))roleLabel.style.display="none";if(daysLabel?.classList?.contains("form-label"))daysLabel.style.display="none";btn.onclick=e=>{e.preventDefault();e.stopPropagation();openInviteModal(admin);};}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;polishInvitationCard();});}const observer=new MutationObserver(schedule);observer.observe(document.documentElement,{subtree:true,childList:true});polishInvitationCard();
