import fs from "node:fs";
import assert from "node:assert/strict";
const auth=fs.readFileSync("auth-ui-clean.js","utf8");
const settings=fs.readFileSync("settings-lifecycle.js","utf8");
const policy=fs.readFileSync("legal-policy.js","utf8");
const client=fs.readFileSync("legal-acceptance-client.js","utf8");
const functions=fs.readFileSync("functions/index.mjs","utf8");
const allow=fs.readFileSync("build/www-files.txt","utf8");
assert.match(policy,/termsVersion:"2026-10-04-v1"/);
assert.match(policy,/privacyVersion:"2026-10-04-v1"/);
assert.match(policy,/not an emergency service/i);
assert.match(auth,/ensureLegalAcceptance/);
assert.match(auth,/Accept and Continue/);
assert.match(auth,/Terms declined/);
assert.match(auth,/startAppAfterLegalAcceptance/);
assert.match(auth,/legalAcceptCheck/);
assert.match(settings,/Legal & Support/);
assert.match(settings,/Privacy Policy/);
assert.match(settings,/Help & Contact Support/);
assert.match(client,/getLegalAcceptanceV1/);
assert.match(client,/acceptLegalPolicyV1/);
assert.match(functions,/export const getLegalAcceptanceV1/);
assert.match(functions,/export const acceptLegalPolicyV1/);
assert.match(allow,/legal-policy\.js/);
assert.match(allow,/legal-acceptance-client\.js/);
console.log("PASS: first-use legal gate and Settings links are wired before shared app startup");
