from pathlib import Path

def replace_once(path, old, new):
    p=Path(path); s=p.read_text()
    if new in s: return
    if old not in s: raise SystemExit(f'anchor missing in {path}')
    p.write_text(s.replace(old,new,1))

p=Path('firestore.rules'); s=p.read_text()
anchor='    function validGroupMessage(groupId,d){return d.keys().hasAll(["e2ee","groupFormat","keyEpoch","senderUid","senderKeyId","ciphertext","iv","state","createdAt"]) && d.keys().hasOnly(["e2ee","groupFormat","keyEpoch","senderUid","senderKeyId","ciphertext","iv","state","createdAt","timeLabel"]) && d.e2ee==4 && d.groupFormat=="fidunio-group-message-v1" && d.keyEpoch==groupDoc(groupId).data.keyEpoch && d.senderUid==request.auth.uid && d.senderKeyId==accountPublicKey(request.auth.uid).data.keyId && d.ciphertext is string && d.ciphertext.size()>=22 && d.ciphertext.size()<=40000 && d.ciphertext.matches(\'^[A-Za-z0-9_-]+$\') && d.iv is string && d.iv.size()==16 && d.iv.matches(\'^[A-Za-z0-9_-]+$\') && d.state=="sent" && d.createdAt==request.time && (!("timeLabel" in d)||(d.timeLabel is string&&d.timeLabel.size()<=80));}\n'
helpers='''    function validGroupMessage(groupId,d){return d.keys().hasAll(["e2ee","groupFormat","keyEpoch","senderUid","senderKeyId","ciphertext","iv","state","createdAt"]) && d.keys().hasOnly(["e2ee","groupFormat","keyEpoch","senderUid","senderKeyId","ciphertext","iv","state","createdAt","timeLabel"]) && d.e2ee==4 && d.groupFormat=="fidunio-group-message-v1" && d.keyEpoch==groupDoc(groupId).data.keyEpoch && d.senderUid==request.auth.uid && d.senderKeyId==accountPublicKey(request.auth.uid).data.keyId && d.ciphertext is string && d.ciphertext.size()>=22 && d.ciphertext.size()<=40000 && d.ciphertext.matches('^[A-Za-z0-9_-]+$') && d.iv is string && d.iv.size()==16 && d.iv.matches('^[A-Za-z0-9_-]+$') && d.state=="sent" && d.createdAt==request.time && (!("timeLabel" in d)||(d.timeLabel is string&&d.timeLabel.size()<=80));}
    function historyGrantPath(groupId,grantId){return /databases/$(database)/documents/groups/$(groupId)/historyGrants/$(grantId);}
    function historyGrant(groupId,grantId){return get(historyGrantPath(groupId,grantId));}
    function historyGrantAfter(groupId,grantId){return getAfter(historyGrantPath(groupId,grantId));}
    function groupMessagePath(groupId,messageId){return /databases/$(database)/documents/groups/$(groupId)/messages/$(messageId);}
    function groupMessage(groupId,messageId){return get(groupMessagePath(groupId,messageId));}
    function validHistoryBoundary(groupId,d){return (d.boundaryKind=="beginning"&&d.boundaryAt==null)||(d.boundaryKind=="timestamp"&&d.boundaryAt is timestamp&&d.firstSharedAt>=d.boundaryAt);}
    function validHistoryGrantCreate(groupId,grantId,d){return d.keys().hasAll(["format","version","groupId","grantId","grantorUid","grantorKeyId","targetUid","targetKeyId","boundaryKind","boundaryAt","firstSharedMessageId","firstSharedAt","totalCopies","status","createdAt","activatedAt"])&&d.keys().hasOnly(["format","version","groupId","grantId","grantorUid","grantorKeyId","targetUid","targetKeyId","boundaryKind","boundaryAt","firstSharedMessageId","firstSharedAt","totalCopies","status","createdAt","activatedAt"])&&d.format=="fidunio-group-history-grant-v1"&&d.version==1&&d.groupId==groupId&&d.grantId==grantId&&d.grantorUid==request.auth.uid&&d.grantorKeyId==accountPublicKey(request.auth.uid).data.keyId&&d.targetUid is string&&d.targetUid!=request.auth.uid&&d.targetUid in groupDoc(groupId).data.memberUids&&exists(/databases/$(database)/documents/e2eePublicKeys/$(d.targetUid))&&d.targetKeyId==accountPublicKey(d.targetUid).data.keyId&&d.boundaryKind in ["beginning","timestamp"]&&d.firstSharedMessageId is string&&d.firstSharedMessageId.size()>0&&d.firstSharedMessageId.size()<=180&&exists(groupMessagePath(groupId,d.firstSharedMessageId))&&groupMessage(groupId,d.firstSharedMessageId).data.e2ee==4&&d.firstSharedAt==groupMessage(groupId,d.firstSharedMessageId).data.createdAt&&validHistoryBoundary(groupId,d)&&d.totalCopies is int&&d.totalCopies>0&&d.status=="building"&&d.createdAt==request.time&&d.activatedAt==null;}
    function validHistoryGrantActivate(groupId,d,old){return d.diff(old).affectedKeys().hasOnly(["status","activatedAt"])&&old.status=="building"&&d.status=="active"&&d.activatedAt==request.time&&d.targetUid in groupDoc(groupId).data.memberUids&&d.targetKeyId==accountPublicKey(d.targetUid).data.keyId;}
    function validHistoryGrantEnvelope(e,g){return e is map&&e.keys().hasAll(["format","version","grantorKeyId","targetKeyId","ciphertext","iv"])&&e.keys().hasOnly(["format","version","grantorKeyId","targetKeyId","ciphertext","iv"])&&e.format=="fidunio-group-history-grant-v1"&&e.version==1&&e.grantorKeyId==g.grantorKeyId&&e.targetKeyId==g.targetKeyId&&e.ciphertext is string&&e.ciphertext.size()>=22&&e.ciphertext.size()<=40000&&e.ciphertext.matches('^[A-Za-z0-9_-]+$')&&e.iv is string&&e.iv.size()==16&&e.iv.matches('^[A-Za-z0-9_-]+$');}
    function validHistoryGrantCopy(groupId,grantId,messageId,d){let g=historyGrantAfter(groupId,grantId).data;return d.keys().hasAll(["format","version","groupId","grantId","sourceMessageId","sourceCreatedAt","grantorUid","grantorKeyId","targetUid","targetKeyId","envelope","createdAt"])&&d.keys().hasOnly(["format","version","groupId","grantId","sourceMessageId","sourceCreatedAt","grantorUid","grantorKeyId","targetUid","targetKeyId","envelope","createdAt"])&&g.status=="building"&&g.grantorUid==request.auth.uid&&g.targetUid in groupDoc(groupId).data.memberUids&&d.format=="fidunio-group-history-grant-copy-v1"&&d.version==1&&d.groupId==groupId&&d.grantId==grantId&&d.sourceMessageId==messageId&&d.grantorUid==g.grantorUid&&d.grantorKeyId==g.grantorKeyId&&d.targetUid==g.targetUid&&d.targetKeyId==g.targetKeyId&&exists(groupMessagePath(groupId,messageId))&&groupMessage(groupId,messageId).data.e2ee==4&&d.sourceCreatedAt==groupMessage(groupId,messageId).data.createdAt&&((g.boundaryKind=="beginning")||(g.boundaryKind=="timestamp"&&d.sourceCreatedAt>=g.boundaryAt))&&validHistoryGrantEnvelope(d.envelope,g)&&d.createdAt==request.time;}
'''
if 'function validHistoryGrantCreate' not in s:
    if anchor not in s: raise SystemExit('rules helper anchor missing')
    s=s.replace(anchor,helpers,1)
match_anchor='      match /epochs/{epochId}{allow read: if isGroupMember(groupId);allow create: if (isGroupAdmin(groupId)||selfLeaveAfter(groupId))&&request.resource.data.keyEpoch==int(epochId)&&request.resource.data.keyEpoch==groupDoc(groupId).data.keyEpoch+1&&validGroupEpoch(groupId,request.resource.data);allow update,delete: if false;}\n      match /messages/{messageId}'
match_insert='''      match /epochs/{epochId}{allow read: if isGroupMember(groupId);allow create: if (isGroupAdmin(groupId)||selfLeaveAfter(groupId))&&request.resource.data.keyEpoch==int(epochId)&&request.resource.data.keyEpoch==groupDoc(groupId).data.keyEpoch+1&&validGroupEpoch(groupId,request.resource.data);allow update,delete: if false;}
      match /historyGrants/{grantId}{
        allow get,list: if isGroupMember(groupId)&&(isGroupAdmin(groupId)||(resource.data.targetUid==request.auth.uid&&resource.data.status=="active"));
        allow create: if isGroupAdmin(groupId)&&validHistoryGrantCreate(groupId,grantId,request.resource.data);
        allow update: if isGroupAdmin(groupId)&&resource.data.grantorUid==request.auth.uid&&validHistoryGrantActivate(groupId,request.resource.data,resource.data);
        allow delete: if false;
        match /messages/{messageId}{allow get,list: if isGroupMember(groupId)&&(isGroupAdmin(groupId)||(historyGrant(groupId,grantId).data.targetUid==request.auth.uid&&historyGrant(groupId,grantId).data.status=="active"));allow create: if isGroupAdmin(groupId)&&validHistoryGrantCopy(groupId,grantId,messageId,request.resource.data);allow update,delete: if false;}
      }
      match /messages/{messageId}'''
if 'match /historyGrants/{grantId}' not in s:
    if match_anchor not in s: raise SystemExit('rules match anchor missing')
    s=s.replace(match_anchor,match_insert,1)
p.write_text(s)

p=Path('firebase.js'); s=p.read_text(); firebase_anchor='export async function createCloudGroupEpochRecord({groupId,expectedEpoch,newEpoch,record})'
firebase_insert='''export async function beginCloudGroupHistoryGrant({groupId,grant}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),grantId=String(grant?.grantId||"").trim();if(!gid||!grantId)throw new Error("Group and history grant ID are required.");const groupRef=s.fsSdk.doc(s.db,"groups",gid),grantRef=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",grantId);return s.fsSdk.runTransaction(s.db,async tx=>{const [groupSnap,existing,grantorKey,targetKey]=await Promise.all([tx.get(groupRef),tx.get(grantRef),tx.get(s.fsSdk.doc(s.db,"e2eePublicKeys",authUser.uid)),tx.get(s.fsSdk.doc(s.db,"e2eePublicKeys",String(grant.targetUid||"")))]);if(!groupSnap.exists())throw new Error("Group was not found.");const g=groupSnap.data(),admins=Array.isArray(g.adminUids)?g.adminUids:[],members=Array.isArray(g.memberUids)?g.memberUids:[];if(!admins.includes(authUser.uid))throw new Error("Only a group administrator can grant earlier history.");if(!members.includes(grant.targetUid)||grant.targetUid===authUser.uid)throw new Error("History target must be another current group member.");if(!grantorKey.exists()||grantorKey.data().keyId!==grant.grantorKeyId||!targetKey.exists()||targetKey.data().keyId!==grant.targetKeyId)throw new Error("History grant account key authority changed.");if(existing.exists()){const x=existing.data(),same=x.status==="building"&&x.grantorUid===grant.grantorUid&&x.targetUid===grant.targetUid&&x.boundaryKind===grant.boundaryKind&&Number(x.totalCopies)===Number(grant.totalCopies)&&x.firstSharedMessageId===grant.firstSharedMessageId;if(!same)throw new Error("History grant ID already exists with different authority.");return{grantId,status:x.status};}tx.set(grantRef,{...grant,createdAt:s.fsSdk.serverTimestamp(),activatedAt:null});return{grantId,status:"building"};});}
export async function writeCloudGroupHistoryGrantCopies({groupId,grantId,copies}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),id=String(grantId||"").trim(),rows=Array.isArray(copies)?copies:[];if(!gid||!id||!rows.length)throw new Error("History grant copies are required.");if(rows.length>100)throw new Error("History grant copy chunk exceeds 100 records.");const [groupSnap,grantSnap]=await Promise.all([s.fsSdk.getDoc(s.fsSdk.doc(s.db,"groups",gid)),s.fsSdk.getDoc(s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id))]);if(!groupSnap.exists()||!grantSnap.exists())throw new Error("History grant authority is unavailable.");const g=groupSnap.data(),grant=grantSnap.data();if(!Array.isArray(g.adminUids)||!g.adminUids.includes(authUser.uid)||grant.grantorUid!==authUser.uid||grant.status!=="building"||!Array.isArray(g.memberUids)||!g.memberUids.includes(grant.targetUid))throw new Error("History grant is no longer writable.");const batch=s.fsSdk.writeBatch(s.db);let writes=0;for(const row of rows){const sourceId=String(row?.sourceMessageId||"").trim();if(!sourceId)throw new Error("History source message ID is required.");const ref=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id,"messages",sourceId),snap=await s.fsSdk.getDoc(ref);if(snap.exists())continue;batch.set(ref,{...row,createdAt:s.fsSdk.serverTimestamp()});writes++;}if(writes)await batch.commit();return{written:writes};}
export async function activateCloudGroupHistoryGrant({groupId,grantId}){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),id=String(grantId||"").trim(),groupRef=s.fsSdk.doc(s.db,"groups",gid),grantRef=s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id);return s.fsSdk.runTransaction(s.db,async tx=>{const [groupSnap,grantSnap]=await Promise.all([tx.get(groupRef),tx.get(grantRef)]);if(!groupSnap.exists()||!grantSnap.exists())throw new Error("History grant authority is unavailable.");const g=groupSnap.data(),grant=grantSnap.data();if(grant.status==="active")return{grantId:id,status:"active"};if(grant.status!=="building"||grant.grantorUid!==authUser.uid||!Array.isArray(g.adminUids)||!g.adminUids.includes(authUser.uid)||!Array.isArray(g.memberUids)||!g.memberUids.includes(grant.targetUid))throw new Error("History grant can no longer be activated.");tx.update(grantRef,{status:"active",activatedAt:s.fsSdk.serverTimestamp()});return{grantId:id,status:"active"};});}
export async function readCloudGroupHistoryGrants(groupId){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim();await readCloudGroupAuthority(gid);const q=s.fsSdk.query(s.fsSdk.collection(s.db,"groups",gid,"historyGrants"),s.fsSdk.where("targetUid","==",authUser.uid),s.fsSdk.where("status","==","active"));const snap=await s.fsSdk.getDocs(q);return snap.docs.map(d=>({id:d.id,...d.data()}));}
export async function readCloudGroupHistoryGrantCopies(groupId,grantId){const s=await ensureServices();if(!authUser)throw new Error("Sign in first.");const gid=String(groupId||"").trim(),id=String(grantId||"").trim();await readCloudGroupAuthority(gid);const grantSnap=await s.fsSdk.getDoc(s.fsSdk.doc(s.db,"groups",gid,"historyGrants",id));if(!grantSnap.exists()||grantSnap.data().status!=="active"||grantSnap.data().targetUid!==authUser.uid)throw new Error("Active history grant is not available to this account.");const q=s.fsSdk.query(s.fsSdk.collection(s.db,"groups",gid,"historyGrants",id,"messages"),s.fsSdk.orderBy("sourceCreatedAt","asc"));const snap=await s.fsSdk.getDocs(q);return snap.docs.map(d=>({id:d.id,...d.data()}));}

'''
if 'export async function beginCloudGroupHistoryGrant' not in s:
    if firebase_anchor not in s: raise SystemExit('firebase anchor missing')
    s=s.replace(firebase_anchor,firebase_insert+firebase_anchor,1)
p.write_text(s)

p=Path('e2ee-account-group-firebase-adapter.js'); s=p.read_text()
s=s.replace('  commitCloudGroupMembershipEpoch\n} from "./firebase.js";','  commitCloudGroupMembershipEpoch,\n  beginCloudGroupHistoryGrant,\n  writeCloudGroupHistoryGrantCopies,\n  activateCloudGroupHistoryGrant,\n  readCloudGroupHistoryGrants,\n  readCloudGroupHistoryGrantCopies\n} from "./firebase.js";')
s=s.replace('    commitGroupMembershipEpoch: commitCloudGroupMembershipEpoch\n','    commitGroupMembershipEpoch: commitCloudGroupMembershipEpoch,\n    beginGroupHistoryGrant: beginCloudGroupHistoryGrant,\n    writeGroupHistoryGrantCopies: writeCloudGroupHistoryGrantCopies,\n    activateGroupHistoryGrant: activateCloudGroupHistoryGrant,\n    readGroupHistoryGrants: readCloudGroupHistoryGrants,\n    readGroupHistoryGrantCopies: readCloudGroupHistoryGrantCopies\n')
p.write_text(s)

p=Path('e2ee-account-group-runtime.js'); s=p.read_text()
s=s.replace('import {createGroupEpoch,unwrapGroupEpoch,encryptAccountGroupMessage,decryptAccountGroupMessage} from "./e2ee-account-group-crypto.js";','import {createGroupEpoch,unwrapGroupEpoch,encryptAccountGroupMessage,decryptAccountGroupMessage} from "./e2ee-account-group-crypto.js";\nimport {encryptGroupHistoryGrantMessage,decryptGroupHistoryGrantMessage} from "./e2ee-account-group-history-crypto.js";')
runtime_anchor='  async function send({groupId,messageId,text:body})'
runtime_insert='''  function asDate(v,name){const d=v instanceof Date?v:v?.toDate?.()||new Date(v);if(!(d instanceof Date)||Number.isNaN(d.getTime()))throw new Error(`${name} is invalid.`);return d;}
  function historyBoundary(v){const kind=String(v?.kind||"").trim();if(kind==="beginning")return{kind,at:null};if(kind==="timestamp")return{kind,at:asDate(v?.at,"History boundary")};throw new Error("History boundary must be beginning or timestamp.");}
  async function createHistoryGrant({groupId,grantId,targetUid,boundary,sourceRows}){return serial(async()=>{["beginGroupHistoryGrant","writeGroupHistoryGrantCopies","activateGroupHistoryGrant"].forEach(n=>need(transport,n));const g=generation,id=identity(),gid=text(groupId,"Group ID"),grant=text(grantId,"Grant ID"),target=text(targetUid,"History target UID"),a=await authority(gid);if(!a.adminUids?.includes(id.uid))throw new Error("Only a group administrator can grant earlier history.");if(target===id.uid||!a.memberUids.includes(target))throw new Error("History target must be another current group member.");const b=historyBoundary(boundary),targetKey=await transport.getAccountPublicKey(target);if(!targetKey?.keyId||!targetKey?.publicJwk)throw new Error("History target account E2EE key is unavailable.");const rows=(Array.isArray(sourceRows)?sourceRows:[]).map(row=>({row,id:text(row?.id,"Source message ID"),createdAt:asDate(row?.createdAt,"Source message time")})).filter(x=>b.kind==="beginning"||x.createdAt.getTime()>=b.at.getTime()).sort((x,y)=>x.createdAt-y.createdAt||x.id.localeCompare(y.id));if(!rows.length)throw new Error("No retained group messages are eligible for this history grant.");const copies=[];for(const item of rows){if(g!==generation)throw new Error("Group operation invalidated.");const plain=await decrypt({groupId:gid,messageId:item.id,row:item.row});const envelope=await encryptGroupHistoryGrantMessage({text:plain,groupId:gid,grantId:grant,sourceMessageId:item.id,grantorUid:id.uid,grantorKeyId:id.keyId,grantorPrivateKey:id.privateKey,targetUid:target,targetKeyId:targetKey.keyId,targetPublicJwk:targetKey.publicJwk});copies.push({format:"fidunio-group-history-grant-copy-v1",version:1,groupId:gid,grantId:grant,sourceMessageId:item.id,sourceCreatedAt:item.createdAt,grantorUid:id.uid,grantorKeyId:id.keyId,targetUid:target,targetKeyId:targetKey.keyId,envelope});}const first=copies[0],grantRow={format:"fidunio-group-history-grant-v1",version:1,groupId:gid,grantId:grant,grantorUid:id.uid,grantorKeyId:id.keyId,targetUid:target,targetKeyId:targetKey.keyId,boundaryKind:b.kind,boundaryAt:b.at,firstSharedMessageId:first.sourceMessageId,firstSharedAt:first.sourceCreatedAt,totalCopies:copies.length,status:"building"};await transport.beginGroupHistoryGrant({groupId:gid,grant:grantRow});for(let i=0;i<copies.length;i+=100)await transport.writeGroupHistoryGrantCopies({groupId:gid,grantId:grant,copies:copies.slice(i,i+100)});if(g!==generation)throw new Error("Group operation invalidated.");await transport.activateGroupHistoryGrant({groupId:gid,grantId:grant});return{grantId:grant,targetUid:target,boundaryKind:b.kind,boundaryAt:b.at,totalCopies:copies.length,firstSharedMessageId:first.sourceMessageId,firstSharedAt:first.sourceCreatedAt};});}
  async function decryptHistoryGrantCopy({groupId,grant,copy}){const id=identity(),gid=text(groupId,"Group ID");if(!grant||grant.status!=="active"||grant.targetUid!==id.uid)throw new Error("Active history grant does not belong to this account.");if(copy?.grantId!==grant.grantId||copy?.targetUid!==id.uid||copy?.grantorUid!==grant.grantorUid)throw new Error("History grant copy authority does not match its grant.");const grantor=await transport.getAccountPublicKey(grant.grantorUid);if(!grantor?.publicJwk||grantor.keyId!==grant.grantorKeyId)throw new Error("History grantor account key is unavailable or changed.");return decryptGroupHistoryGrantMessage({envelope:copy.envelope,groupId:gid,grantId:grant.grantId,sourceMessageId:copy.sourceMessageId,grantorUid:grant.grantorUid,grantorKeyId:grant.grantorKeyId,targetUid:id.uid,targetKeyId:id.keyId,targetPrivateKey:id.privateKey,grantorPublicJwk:grantor.publicJwk});}
  async function loadHistoryGrantMessages(groupId){["readGroupHistoryGrants","readGroupHistoryGrantCopies"].forEach(n=>need(transport,n));const id=identity(),gid=text(groupId,"Group ID"),a=await authority(gid);if(!a.memberUids.includes(id.uid))throw new Error("Account is not an active group member.");const grants=await transport.readGroupHistoryGrants(gid),byMessage=new Map();for(const grant of grants||[]){if(grant?.status!=="active"||grant?.targetUid!==id.uid)continue;const copies=await transport.readGroupHistoryGrantCopies(gid,grant.grantId);for(const copy of copies||[]){const body=await decryptHistoryGrantCopy({groupId:gid,grant,copy});const when=asDate(copy.sourceCreatedAt,"History source message time");if(!byMessage.has(copy.sourceMessageId))byMessage.set(copy.sourceMessageId,{id:copy.sourceMessageId,text:body,createdAt:when,historyGrantId:grant.grantId,granted:true});}}return [...byMessage.values()].sort((x,y)=>x.createdAt-y.createdAt||x.id.localeCompare(y.id));}
'''
if 'async function createHistoryGrant' not in s:
    if runtime_anchor not in s: raise SystemExit('runtime anchor missing')
    s=s.replace(runtime_anchor,runtime_insert+runtime_anchor,1)
s=s.replace('return Object.freeze({ensureEpoch,rotateEpoch,renameGroup,changeMembership,send,decrypt,revalidateQueued,resetForSignOut:invalidate});','return Object.freeze({ensureEpoch,rotateEpoch,renameGroup,changeMembership,createHistoryGrant,loadHistoryGrantMessages,decryptHistoryGrantCopy,send,decrypt,revalidateQueued,resetForSignOut:invalidate});')
p.write_text(s)

p=Path('e2ee-account-group-service.js'); s=p.read_text(); marker='export function leaveAccountGroup(groupId){const id=getAccountE2EERuntimeIdentity();if(!id?.uid)throw new Error("Account E2EE identity must be unlocked before leaving a group.");return runtime.changeMembership({groupId,operation:"leave",targetUid:id.uid});}\n'; add=marker+'export function createAccountGroupHistoryGrant(args){return runtime.createHistoryGrant(args);}\nexport function loadAccountGroupGrantedHistory(groupId){return runtime.loadHistoryGrantMessages(groupId);}\n'
if 'createAccountGroupHistoryGrant' not in s:
    if marker not in s: raise SystemExit('service anchor missing')
    s=s.replace(marker,add,1)
p.write_text(s)

p=Path('e2ee-account-group-runtime.test.mjs'); s=p.read_text()
s=s.replace('let authority={memberUids:[A.uid,B.uid],adminUids:[A.uid],keyEpoch:0},epochs=new Map(),sent=null;','let authority={memberUids:[A.uid,B.uid],adminUids:[A.uid],keyEpoch:0},epochs=new Map(),sent=null,historyGrant=null,historyCopies=[];')
s=s.replace('readGroupEpochRecord:async(_g,e)=>epochs.get(e)||null,sendEncryptedGroupMessage:async row=>{sent=row;}};','readGroupEpochRecord:async(_g,e)=>epochs.get(e)||null,sendEncryptedGroupMessage:async row=>{sent=row;},beginGroupHistoryGrant:async({grant})=>{historyGrant={...grant,status:"building"};},writeGroupHistoryGrantCopies:async({copies})=>{historyCopies.push(...copies);return{written:copies.length};},activateGroupHistoryGrant:async()=>{historyGrant={...historyGrant,status:"active"};return{status:"active"};},readGroupHistoryGrants:async()=>historyGrant?[historyGrant]:[],readGroupHistoryGrantCopies:async()=>historyCopies};')
old='await ra.changeMembership({groupId:"g1",operation:"add",targetUid:C.uid});ok(authority.memberUids.includes(C.uid)&&authority.keyEpoch===3&&epochs.get(3).envelopes.C,"atomic add includes new member only in new epoch");await ra.changeMembership({groupId:"g1",operation:"remove",targetUid:B.uid});ok(!authority.memberUids.includes(B.uid)&&authority.keyEpoch===4&&!epochs.get(4).envelopes.B,"atomic remove excludes removed member from new epoch");console.log("10/10 group runtime assertions passed.");'
new='''await ra.changeMembership({groupId:"g1",operation:"add",targetUid:C.uid});ok(authority.memberUids.includes(C.uid)&&authority.keyEpoch===3&&epochs.get(3).envelopes.C,"atomic add includes new member only in new epoch");const sourceTime=new Date("2026-09-06T12:00:00Z"),grant=await ra.createHistoryGrant({groupId:"g1",grantId:"grant-001",targetUid:C.uid,boundary:{kind:"beginning"},sourceRows:[{id:"m1",createdAt:sourceTime,...sent.envelope,senderUid:A.uid}]});ok(grant.totalCopies===1&&historyGrant?.status==="active"&&historyCopies.length===1,"admin creates active message-granular history grant");const rc=createAccountGroupE2EERuntime({identityProvider:()=>C,transport}),granted=await rc.loadHistoryGrantMessages("g1");ok(granted.length===1&&granted[0].id==="m1"&&granted[0].text==="hello group","target decrypts granted historical message");let boundaryBlocked=false;try{await ra.createHistoryGrant({groupId:"g1",grantId:"grant-002",targetUid:C.uid,boundary:{kind:"timestamp",at:new Date(sourceTime.getTime()+1000)},sourceRows:[{id:"m1",createdAt:sourceTime,...sent.envelope,senderUid:A.uid}]});}catch{boundaryBlocked=true;}ok(boundaryBlocked,"date boundary excludes earlier source message");await ra.changeMembership({groupId:"g1",operation:"remove",targetUid:B.uid});ok(!authority.memberUids.includes(B.uid)&&authority.keyEpoch===4&&!epochs.get(4).envelopes.B,"atomic remove excludes removed member from new epoch");console.log("13/13 group runtime assertions passed.");'''
if old not in s: raise SystemExit('runtime test anchor missing')
s=s.replace(old,new,1); p.write_text(s)

p=Path('firestore-group-e2ee-v1.rules.test.mjs'); s=p.read_text(); helper_anchor='function msg(extra={}){return{e2ee:4,groupFormat:"fidunio-group-message-v1",keyEpoch:1,senderUid:A,senderKeyId:keyA,ciphertext:"AAAAAAAAAAAAAAAAAAAAAA",iv:"AAAAAAAAAAAAAAAA",state:"sent",createdAt:serverTimestamp(),...extra};}\n'
helper_add=helper_anchor+'''function grant(id="hg1",extra={}){return{format:"fidunio-group-history-grant-v1",version:1,groupId:"g1",grantId:id,grantorUid:A,grantorKeyId:keyA,targetUid:B,targetKeyId:keyB,boundaryKind:"beginning",boundaryAt:null,firstSharedMessageId:"m1",firstSharedAt:new Date("2026-09-06T12:00:00Z"),totalCopies:1,status:"building",createdAt:serverTimestamp(),activatedAt:null,...extra};}
function grantCopy(id="hg1",extra={}){return{format:"fidunio-group-history-grant-copy-v1",version:1,groupId:"g1",grantId:id,sourceMessageId:"m1",sourceCreatedAt:new Date("2026-09-06T12:00:00Z"),grantorUid:A,grantorKeyId:keyA,targetUid:B,targetKeyId:keyB,envelope:{format:"fidunio-group-history-grant-v1",version:1,grantorKeyId:keyA,targetKeyId:keyB,ciphertext:"AAAAAAAAAAAAAAAAAAAAAA",iv:"AAAAAAAAAAAAAAAA"},createdAt:serverTimestamp(),...extra};}
'''
if 'function grant(id="hg1"' not in s:
    if helper_anchor not in s: raise SystemExit('rules test helper anchor missing')
    s=s.replace(helper_anchor,helper_add,1)
s=s.replace('await test("08 valid encrypted group message succeeds",()=>assertSucceeds(setDoc(doc(dbA,"groups","g1","messages","m1"),msg())));','await test("08 valid encrypted group message succeeds",()=>assertSucceeds(setDoc(doc(dbA,"groups","g1","messages","m1"),msg({createdAt:new Date("2026-09-06T12:00:00Z")}))));')
end_anchor='const failed=results.filter(([,ok])=>!ok);console.log(`\\n${results.length-failed.length}/${results.length} group E2EE assertions passed.`);await env.cleanup();if(failed.length)process.exitCode=1;'
extra_tests='''await test("19 non-admin cannot create history grant",()=>assertFails(setDoc(doc(dbB,"groups","g1","historyGrants","hg0"),{...grant("hg0"),grantorUid:B,grantorKeyId:keyB,targetUid:A,targetKeyId:keyA})));
await test("20 admin cannot grant history to outsider",()=>assertFails(setDoc(doc(dbA,"groups","g1","historyGrants","hg-out"),grant("hg-out",{targetUid:OUT,targetKeyId:"missing"}))));
await test("21 timestamp grant cannot start before requested boundary",()=>assertFails(setDoc(doc(dbA,"groups","g1","historyGrants","hg-late"),grant("hg-late",{boundaryKind:"timestamp",boundaryAt:new Date("2026-09-06T12:01:00Z")}))));
await test("22 admin creates building beginning grant",()=>assertSucceeds(setDoc(doc(dbA,"groups","g1","historyGrants","hg1"),grant())));
await test("23 target cannot read building grant",()=>assertFails(getDoc(doc(dbB,"groups","g1","historyGrants","hg1"))));
await test("24 admin writes bounded history copy while building",()=>assertSucceeds(setDoc(doc(dbA,"groups","g1","historyGrants","hg1","messages","m1"),grantCopy())));
await test("25 target cannot read copy before activation",()=>assertFails(getDoc(doc(dbB,"groups","g1","historyGrants","hg1","messages","m1"))));
await test("26 grantor activates completed grant metadata",async()=>{const before=await getDoc(doc(dbA,"groups","g1","historyGrants","hg1"));return assertSucceeds(setDoc(doc(dbA,"groups","g1","historyGrants","hg1"),{...before.data(),status:"active",activatedAt:serverTimestamp()}));});
await test("27 target reads active grant",()=>assertSucceeds(getDoc(doc(dbB,"groups","g1","historyGrants","hg1"))));
await test("28 target reads active granted message copy",()=>assertSucceeds(getDoc(doc(dbB,"groups","g1","historyGrants","hg1","messages","m1"))));
await test("29 outsider cannot read active history grant",()=>assertFails(getDoc(doc(dbO,"groups","g1","historyGrants","hg1"))));

'''+end_anchor
if '29 outsider cannot read active history grant' not in s:
    if end_anchor not in s: raise SystemExit('rules test end anchor missing')
    s=s.replace(end_anchor,extra_tests,1)
p.write_text(s)

Path('version.js').write_text('''/* FIDUNIO single authoritative release version. Update this file for each new release. */\nglobalThis.FIDUNIO_RELEASE = Object.freeze({\n  version: "0.9.6.7"\n});\n''')
p=Path('README.md'); s=p.read_text().replace('Current checkpoint version: **0.9.6.6**','Current checkpoint version: **0.9.6.7**')
entry='''\n\n## FIDUNIO 0.9.6.7 — bounded group-history persistence foundation\n\nRelease transition: **0.9.6.6 -> 0.9.6.7**.\n\n- Added exact Firestore schema/rules for explicit group-history grant metadata and message-granular encrypted copies under `groups/{groupId}/historyGrants/{grantId}`.\n- Only a current group administrator can create/activate a grant; the target must be another current active group member with the authoritative durable account key.\n- A grant begins in `building` state. The target cannot read grant metadata or copies until the grantor explicitly activates it; this prevents partial chunked history from becoming visible during construction.\n- Source-message timestamps are rule-bound to retained group messages, and timestamp grants reject copies earlier than the selected lower boundary. `Beginning of conversation` remains supported without disclosing historical epoch keys.\n- `firebase.js` remains the sole Firebase owner and now transports opaque grant metadata/copy records in bounded chunks.\n- `e2ee-account-group-runtime.js` serializes grant construction, decrypts only source messages the admin can already read, re-encrypts them message-by-message through `e2ee-account-group-history-crypto.js`, and provides target-side grant decryption.\n- Runtime and Firestore emulator coverage were expanded for creation, boundary enforcement, activation visibility, outsider denial, and target decrypt.\n- Group Info UI remains deliberately disabled for earlier-history sharing until date-selection UI, conversation merge/display, disappearing-content purge/anti-resurrection linkage, and final real-app validation are complete.\n- Repository rules changed in this release but **live Firebase rules were not deployed**. Live Firebase remains untouched pending the controlled Firebase handoff.\n- Overall first-rebuild estimate remains approximately 65% until the full history-sharing user path and purge linkage are integrated.\n'''
if '## FIDUNIO 0.9.6.7 — bounded group-history persistence foundation' not in s: s=s.rstrip()+entry+'\n'
p.write_text(s)

p=Path('ACCOUNT-E2EE-GROUP-MESSAGE-FORMAT.md'); s=p.read_text(); section='''\n\n### Firestore history-grant persistence schema — 0.9.6.7\n\nGrant metadata lives at `groups/{groupId}/historyGrants/{grantId}` and uses exact fields: `format,version,groupId,grantId,grantorUid,grantorKeyId,targetUid,targetKeyId,boundaryKind,boundaryAt,firstSharedMessageId,firstSharedAt,totalCopies,status,createdAt,activatedAt`. `format` is `fidunio-group-history-grant-v1`; `version` is `1`; `boundaryKind` is `beginning` or `timestamp`; `status` is `building` or `active`. A timestamp boundary requires `firstSharedAt >= boundaryAt`; Beginning uses `boundaryAt:null`. The first shared message must still exist and its authoritative Firestore `createdAt` must equal `firstSharedAt`.\n\nEncrypted per-message copies live at `groups/{groupId}/historyGrants/{grantId}/messages/{sourceMessageId}`. Each exact copy records `format:"fidunio-group-history-grant-copy-v1",version,groupId,grantId,sourceMessageId,sourceCreatedAt,grantorUid,grantorKeyId,targetUid,targetKeyId,envelope,createdAt`. `envelope` is the exact message-granular crypto envelope already defined above. Rules bind the copy to the retained source message and enforce the selected lower boundary.\n\nConstruction is two-phase so Beginning of conversation can scale across multiple Firestore batches without exposing partial history: create `building` metadata, write bounded copy chunks, then activate. The target can read neither building metadata nor building copies. Activation rechecks that the grantor is still a current admin and the target is still a current member. Under-sharing caused by an interrupted build is not a confidentiality failure; over-sharing before the boundary is denied by rules and cryptographic context.\n\n0.9.6.7 does not yet enable the Group Info control. Grant-copy physical purge, local decrypted-copy purge/anti-resurrection, UI date selection and conversation projection are still mandatory before this feature is DONE.\n'''
if '### Firestore history-grant persistence schema — 0.9.6.7' not in s: s+=section
p.write_text(s)

for path,title,body in [
 ('FIRESTORE-GROUP-E2EE-V1-RULES.md','## Group history-grant rules — 0.9.6.7','''- `historyGrants/{grantId}` is a separate explicit authority path; it never changes `historyPolicy: fromJoin` and never exposes old epoch keys.\n- Create requires current group admin, current target membership, target != grantor, and exact authoritative account keyIds.\n- The first shared message and every copy are bound to an existing retained `e2ee:4` source message and its authoritative `createdAt`.\n- Timestamp boundaries reject any source copy earlier than `boundaryAt`; Beginning of conversation uses `boundaryAt:null`.\n- Grants are created as `building`; targets cannot read metadata/copies until the grantor activates the grant. Activation rechecks admin and target membership.\n- Other members/outsiders cannot read target grants. Current admins may inspect ciphertext metadata for administration but cannot decrypt a target envelope without that target private identity.\n- Update/delete remain closed except the single `building -> active` activation transition. Purge deletion authority is intentionally deferred to the disappearing-content owner rather than opened prematurely.\n- These repository rules are NOT automatically deployed to live Firebase.'''),
 ('FIRESTORE-E2EE-V1-EMULATOR-TESTS.md','## Group history-grant emulator extension — 0.9.6.7','''`firestore-group-e2ee-v1.rules.test.mjs` now includes explicit history-grant assertions: non-admin create denied, outsider target denied, timestamp boundary underflow denied, building grant create allowed for admin, target reads denied while building, bounded copy write allowed, pre-activation copy read denied, activation allowed, target active grant/copy reads allowed, and outsider reads denied. The normal Rebuild Baseline Security Gate remains the repository validation authority.'''),
 ('RUNTIME-AUTHORITY-MAP.md','## Group history-grant runtime path — 0.9.6.7','''`e2ee-account-group-history-crypto.js` owns only message-granular grant cryptography. `e2ee-account-group-runtime.js` is the serialized group orchestration owner for grant selection/construction/decryption. `e2ee-account-group-firebase-adapter.js` is a thin naming adapter. `firebase.js` remains the sole Firebase SDK/service owner for grant persistence/read transport. `app.js`, the service worker and UI modules do not own grant cryptography or Firestore writes. The Group Info UI is still disabled until projection/purge integration is complete.'''),
 ('architecture-ownership.txt','GROUP HISTORY GRANTS — 0.9.6.7','''- Resource: explicit earlier-history grant metadata and message-granular encrypted copies.\n- Crypto owner: e2ee-account-group-history-crypto.js.\n- Serialized operation owner: e2ee-account-group-runtime.js.\n- Firebase transport owner: firebase.js through the thin group Firebase adapter.\n- Firestore paths: groups/{groupId}/historyGrants/{grantId} and nested messages/{sourceMessageId}.\n- Write path: Group runtime -> Firebase adapter -> firebase.js -> Firestore. No app.js/service-worker direct writes.\n- UI remains non-authoritative and not yet enabled.\n- Purge/delete ownership remains reserved for the disappearing-content implementation; do not casually open client delete rules.'''),
 ('group-data-model.txt','GROUP HISTORY GRANT DATA MODEL — 0.9.6.7','''Grant metadata: groups/{groupId}/historyGrants/{grantId}. Per-message encrypted copies: groups/{groupId}/historyGrants/{grantId}/messages/{sourceMessageId}. Grants are built invisibly in status=building and become readable to the target only after status=active. Timestamp lower boundaries are enforced against authoritative source-message createdAt; Beginning of conversation uses the earliest still-retained eligible source. Copies contain target-specific account-E2EE history envelopes and never old group epoch keys or device IDs.''')]:
    p=Path(path); x=p.read_text(); block='\n\n'+title+'\n'+body.strip()+'\n'
    if title not in x: p.write_text(x.rstrip()+block)

p=Path('FIDUNIO-BUILD-CHECKLIST.md'); s=p.read_text(); log='- 2026-09-06 — 0.9.6.7 group earlier-history persistence foundation materialized: exact grant/copy Firestore schema and rules, building->active target-visibility boundary, current-admin/current-member/keyId authorization, message/timestamp boundary binding, central Firebase chunked persistence/read APIs, serialized runtime create/decrypt path, and expanded emulator/runtime tests. Group Info history control remains IN PROGRESS pending UI/projection and disappearing-content purge/anti-resurrection integration. Live Firebase was not touched. Overall estimate remains approximately 65%.'
if log not in s: s=s.rstrip()+'\n'+log+'\n'
p.write_text(s)

p=Path('hermes-memory.txt'); s=p.read_text(); block='''\n\n2026-09-06 — GROUP HISTORY PERSISTENCE FOUNDATION / 0.9.6.7\n- Confirmed prior cleaned-branch Rebuild Baseline Security Gate run `34046696823` green before starting this slice.\n- Implemented exact repository Firestore schema/rules for explicit earlier-history grant metadata plus per-source-message encrypted copies. Default `fromJoin` remains unchanged.\n- Grant construction is two-phase (`building` -> `active`) so large Beginning-of-conversation grants can be written in chunks without exposing partial history. Target reads are denied until activation.\n- Rules require current admin grantor, another current member as target, authoritative durable account keyIds, retained e2ee:4 source messages, source timestamp equality and lower-bound enforcement.\n- `firebase.js` remains sole Firebase owner and now provides begin/write-chunks/activate/read APIs for opaque grant records.\n- `e2ee-account-group-runtime.js` serializes grant creation, decrypts only already-authorized source messages, re-encrypts each through the isolated history crypto owner, and decrypts active grants for the target account.\n- Runtime and Firestore group E2EE tests were expanded.\n- Version advanced 0.9.6.6 -> 0.9.6.7 and README updated in the same release boundary per the release-ledger rule.\n- This is not the completed UI feature: Group Info date selection, granted-history conversation projection, disappearing-content physical purge of grant copies/local plaintext and anti-resurrection remain required.\n- Repository rules now contain history-grant policy but LIVE Firebase rules were NOT deployed; do not deploy until the controlled Firebase handoff.\n- htest was not touched. App Check enforcement remains OFF. FCM remains deferred to 1.1.\n- Overall first complete rebuild estimate remains approximately 65%.\n'''
if '2026-09-06 — GROUP HISTORY PERSISTENCE FOUNDATION / 0.9.6.7' not in s: s+=block
p.write_text(s)
