import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
const read=name=>readFileSync(name,"utf8");
const diagnostics=read("notification-diagnostics.js"),worker=read("service-worker.js"),bootstrap=read("bootstrap.js"),auth=read("auth-ui-clean.js"),app=read("app.js"),settings=read("settings-lifecycle.js"),page=read("notification-diagnostics-page.js"),html=read("notification-diagnostics.html"),workflow=read(".github/workflows/rebuild-baseline-security.yml");
assert.match(diagnostics,/fidunio-notification-diagnostics-v1/);
assert.match(diagnostics,/let writeTail=Promise\.resolve\(\)/);
assert.match(diagnostics,/pin\|password\|privatekey\|recoverykey\|recoverysecret\|accesstoken\|refreshtoken\|fcmtoken/);
for(const marker of ["install","activate","background-message","notification-click","open-window-request","open-window-result","open-window-error"])assert.ok(worker.includes(`\"${marker}\"`),`missing worker marker ${marker}`);
for(const marker of ["module-start","service-worker-registration","before-auth-gate","after-auth-gate"])assert.ok(bootstrap.includes(`\"${marker}\"`),`missing bootstrap marker ${marker}`);
for(const marker of ["pin-submit","pin-success","pin-error","start-app-enter","start-app-complete"])assert.ok(auth.includes(`\"${marker}\"`),`missing auth marker ${marker}`);
for(const marker of ["route-apply-enter","route-apply-blocked","route-conversation-local-lookup","route-conversation-remote-lookup","route-state-selected","route-apply-success","route-apply-error","message-subscription-request","message-snapshot-start","message-projection-planned","message-history-cached","message-state-persisted","read-receipt-start","read-receipt-complete","message-snapshot-complete","render","visibilitychange","pageshow","service-worker-message"])assert.ok(app.includes(`\"${marker}\"`),`missing app marker ${marker}`);
assert.match(settings,/Open Notification Diagnostics/);assert.match(html,/Copy Full Report/);assert.match(page,/JSON\.stringify\(payload,null,2\)/);assert.match(workflow,/notification-one-shot-diagnostics\.test\.mjs/);
assert.doesNotMatch(worker,/client\.postMessage/);
console.log("One-shot cross-context notification diagnostic coverage gate passed");
