import assert from "node:assert/strict";
import fs from "node:fs";
import {FIDUNIO_PLATFORM,detectFidunioPlatform,isNativeIOSRuntime,shouldUseWebServiceWorker,shouldUseWebPush,shouldUseWebAppCheck} from "./platform-runtime.js";
const webCap={isNativePlatform:()=>false,getPlatform:()=>"web"};
const iosCap={isNativePlatform:()=>true,getPlatform:()=>"ios"};
assert.equal(detectFidunioPlatform({capacitor:webCap,protocol:"https:"}),FIDUNIO_PLATFORM.WEB);
assert.equal(detectFidunioPlatform({capacitor:iosCap,protocol:"capacitor:"}),FIDUNIO_PLATFORM.IOS_NATIVE);
assert.equal(detectFidunioPlatform({capacitor:undefined,protocol:"capacitor:"}),FIDUNIO_PLATFORM.IOS_NATIVE,"protocol fallback protects early Capacitor startup");
assert.equal(isNativeIOSRuntime({capacitor:iosCap,protocol:"capacitor:"}),true);
assert.equal(shouldUseWebServiceWorker({capacitor:iosCap,protocol:"capacitor:"}),false);
assert.equal(shouldUseWebPush({capacitor:iosCap,protocol:"capacitor:"}),false);
assert.equal(shouldUseWebAppCheck({capacitor:iosCap,protocol:"capacitor:"}),false);
assert.equal(shouldUseWebServiceWorker({capacitor:webCap,protocol:"https:"}),true);
assert.equal(shouldUseWebPush({capacitor:webCap,protocol:"https:"}),true);
assert.equal(shouldUseWebAppCheck({capacitor:webCap,protocol:"https:"}),true);

const bootstrap=fs.readFileSync("bootstrap.js","utf8");
const app=fs.readFileSync("app.js","utf8");
const firebase=fs.readFileSync("firebase.js","utf8");
const settings=fs.readFileSync("settings-lifecycle.js","utf8");
const install=fs.readFileSync("install-guidance.js","utf8");
const localSecurity=fs.readFileSync("local-security.js","utf8");
const payload=fs.readFileSync("build/www-files.txt","utf8");
assert.match(bootstrap,/shouldUseWebServiceWorker\(\)/);
assert.match(app,/shouldUseWebServiceWorker\(\).*"serviceWorker" in navigator/s);
assert.match(firebase,/shouldUseWebAppCheck\(\)\?appCheckSdk\.initializeAppCheck/);
assert.match(settings,/if\(isNativeIOSRuntime\(\)\).*Native notification setup pending/s);
assert.match(install,/nativeApp=isNativeIOSRuntime\(\)/);
assert.match(localSecurity,/platformAuthenticatorAvailable\(\)\{if\(isNativeIOSRuntime\(\)\)return false/);
assert.match(app,/security\.hasBiometric&&!isNativeIOSRuntime\(\)/);
assert.match(payload,/^platform-runtime\.js$/m);
console.log("PASS: bounded web/Capacitor iOS runtime selection and integration guards");
