from pathlib import Path
import json


def replace(path, old, new, count=1):
    p=Path(path); s=p.read_text()
    if old not in s:
        raise SystemExit(f"anchor missing: {path}: {old[:120]!r}")
    p.write_text(s.replace(old,new,count))

# Activate the existing disappearing selection for future attachments.
p=Path('disappearing-compose-policy.js'); s=p.read_text()
old='''export const DISAPPEARING_PURGE_VERSION=1;\nfunction isAttachmentPayload(text){\n  if(typeof text!=="string"||!text.trimStart().startsWith("{"))return false;\n  try{return JSON.parse(text)?.fidunioAttachment===1;}catch{return false;}\n}\nexport function disappearingPurgeVersionForOutgoing({text,value}={}){\n  const duration=resolveComposeDisappearSelection(value);\n  return duration!=null&&!isAttachmentPayload(text)?DISAPPEARING_PURGE_VERSION:null;\n}\nexport function stampOutgoingDisappearSelection(message,value){\n  const duration=resolveComposeDisappearSelection(value);\n  // Activation 0.9.9.12 is text-only. Attachment Storage deletion is a\n  // separate server trace resource and must not be implied by this timer.\n  if(duration==null||isAttachmentPayload(message?.text))return {...message};\n  return {...message,disappearAfterSeconds:duration,disappearingPurgeVersion:DISAPPEARING_PURGE_VERSION};\n}\n'''
new='''export const DISAPPEARING_PURGE_VERSION=1;\nexport function disappearingPurgeVersionForOutgoing({value}={}){\n  const duration=resolveComposeDisappearSelection(value);\n  return duration!=null?DISAPPEARING_PURGE_VERSION:null;\n}\nexport function stampOutgoingDisappearSelection(message,value){\n  const duration=resolveComposeDisappearSelection(value);\n  if(duration==null)return {...message};\n  // 0.9.9.19 extends the already-accepted disappearing selection to future\n  // attachments. The server purge repository remains the sole Firestore/Storage\n  // physical-delete owner.\n  return {...message,disappearAfterSeconds:duration,disappearingPurgeVersion:DISAPPEARING_PURGE_VERSION};\n}\n'''
if old not in s: raise SystemExit('compose exclusion anchor missing')
p.write_text(s.replace(old,new,1))

# Extend the one server purge repository with injected Admin Storage capability.
p=Path('disappearing-purge-firestore-admin-adapter.mjs'); s=p.read_text()
s=s.replace('export function createDisappearingPurgeFirestoreAdminRepository({db}={}){\n  if(!db||typeof db.doc!=="function"||typeof db.runTransaction!=="function")throw new Error("Admin Firestore database is required.");',
'''export function createDisappearingPurgeFirestoreAdminRepository({db,bucket=null,requireStorage=false}={}){\n  if(!db||typeof db.doc!=="function"||typeof db.runTransaction!=="function")throw new Error("Admin Firestore database is required.");\n  if(requireStorage&&(!bucket||typeof bucket.deleteFiles!=="function"))throw new Error("Admin Storage bucket is required for activated disappearing attachments.");''',1)
anchor='''  const directConversationRef=id=>db.doc(`conversations/${id}`),directMessageRef=(cid,mid)=>db.doc(`conversations/${cid}/messages/${mid}`),groupRef=id=>db.doc(`groups/${id}`),groupMessageRef=(gid,mid)=>db.doc(`groups/${gid}/messages/${mid}`),groupEpochRef=(gid,epoch)=>db.doc(`groups/${gid}/epochs/${epoch}`),groupReceiptsRef=(gid,mid)=>db.doc(`groups/${gid}/messages/${mid}`).collection("receipts"),groupHistoryGrantsRef=gid=>db.doc(`groups/${gid}`).collection("historyGrants");\n'''
insert=anchor+'''  function attachmentPrefix(senderUid,conversationId,messageId){return `attachments/${text(senderUid,"Sender UID")}/${text(conversationId,"Conversation ID")}/${text(messageId,"Message ID")}/`;}\n  async function deleteAttachmentStorageTraces({senderUid,conversationId,messageId}){if(!bucket)return null;const prefix=attachmentPrefix(senderUid,conversationId,messageId);await bucket.deleteFiles({prefix,force:true});return prefix;}\n'''
if anchor not in s: raise SystemExit('adapter ref anchor missing')
s=s.replace(anchor,insert,1)
old_direct='''  async function commitDirectPurge({conversationId,messageId,expectedBasis}){const cid=text(conversationId,"Conversation ID"),mid=text(messageId,"Message ID"),expected=String(expectedBasis??"");if(!expected)throw fail("INVALID_INPUT","Expected purge basis is required.");const cRef=directConversationRef(cid),mRef=directMessageRef(cid,mid);return db.runTransaction(async tx=>{const [cSnap,mSnap]=await Promise.all([tx.get(cRef),tx.get(mRef)]);if(!mSnap?.exists)return{purged:true,alreadyAbsent:true,traceCount:0};if(!cSnap?.exists)throw fail("PURGE_SOURCE_INVALID","Direct conversation authority disappeared before purge.");sameBasis(directBasis(cSnap,mSnap),expected);directRecipient(cSnap.data(),mSnap.data());tx.delete(mRef);return{purged:true,alreadyAbsent:false,traceCount:1};});}\n'''
new_direct='''  async function commitDirectPurge({conversationId,messageId,expectedBasis}){const cid=text(conversationId,"Conversation ID"),mid=text(messageId,"Message ID"),expected=String(expectedBasis??"");if(!expected)throw fail("INVALID_INPUT","Expected purge basis is required.");const cRef=directConversationRef(cid),mRef=directMessageRef(cid,mid),current=await readDirectPurgeState({conversationId:cid,messageId:mid});if(!current)return{purged:true,alreadyAbsent:true,traceCount:0,storagePurged:false};sameBasis(current.basis,expected);const storagePrefix=await deleteAttachmentStorageTraces({senderUid:current.message.senderUid,conversationId:cid,messageId:mid});const committed=await db.runTransaction(async tx=>{const [cSnap,mSnap]=await Promise.all([tx.get(cRef),tx.get(mRef)]);if(!mSnap?.exists)return{purged:true,alreadyAbsent:true,traceCount:0};if(!cSnap?.exists)throw fail("PURGE_SOURCE_INVALID","Direct conversation authority disappeared before purge.");sameBasis(directBasis(cSnap,mSnap),expected);directRecipient(cSnap.data(),mSnap.data());tx.delete(mRef);return{purged:true,alreadyAbsent:false,traceCount:1};});return{...committed,storagePurged:storagePrefix!==null,storagePrefix};}\n'''
if old_direct not in s: raise SystemExit('direct commit anchor missing')
s=s.replace(old_direct,new_direct,1)
old_group='''  async function commitGroupPurge({groupId,messageId,expectedBasis}){\n    const gid=text(groupId,"Group ID"),mid=text(messageId,"Message ID"),expected=String(expectedBasis??"");if(!expected)throw fail("INVALID_INPUT","Expected purge basis is required.");const gRef=groupRef(gid),mRef=groupMessageRef(gid,mid),rRef=groupReceiptsRef(gid,mid);\n    return db.runTransaction(async tx=>{\n'''
new_group='''  async function commitGroupPurge({groupId,messageId,expectedBasis}){\n    const gid=text(groupId,"Group ID"),mid=text(messageId,"Message ID"),expected=String(expectedBasis??"");if(!expected)throw fail("INVALID_INPUT","Expected purge basis is required.");const gRef=groupRef(gid),mRef=groupMessageRef(gid,mid),rRef=groupReceiptsRef(gid,mid),current=await readGroupPurgeState({groupId:gid,messageId:mid});if(!current)return{purged:true,alreadyAbsent:true,traceCount:0,storagePurged:false};sameBasis(current.basis,expected);const preflightWrites=(current.receipts?.length||0)+(current.grantTracePlan?.copiesToDelete?.length||0)+(current.grantTracePlan?.grantsToDelete?.length||0)+(current.grantTracePlan?.grantsToUpdate?.length||0)+1;if(preflightWrites>MAX_GROUP_PURGE_TRANSACTION_WRITES)throw fail("PURGE_TRACE_TOO_LARGE",`Group purge requires ${preflightWrites} writes; maximum is ${MAX_GROUP_PURGE_TRANSACTION_WRITES}.`);const storagePrefix=await deleteAttachmentStorageTraces({senderUid:current.message.senderUid,conversationId:gid,messageId:mid});\n    const committed=await db.runTransaction(async tx=>{\n'''
if old_group not in s: raise SystemExit('group commit header anchor missing')
s=s.replace(old_group,new_group,1)
old_end='''      tx.delete(mRef);traceCount++;return{purged:true,alreadyAbsent:false,traceCount};\n    });\n  }\n'''
new_end='''      tx.delete(mRef);traceCount++;return{purged:true,alreadyAbsent:false,traceCount};\n    });\n    return{...committed,storagePurged:storagePrefix!==null,storagePrefix};\n  }\n'''
if old_end not in s: raise SystemExit('group commit footer anchor missing')
s=s.replace(old_end,new_end,1)
s=s.replace('clientDeleteRulesRequired:false,groupPhysicalDeleteReady:true,', 'attachmentStoragePrefix:"attachments/{senderUid}/{conversationId}/{messageId}/",attachmentStorageDeleteReady:true,storageBeforeSource:true,clientDeleteRulesRequired:false,groupPhysicalDeleteReady:true,',1)
p.write_text(s)
Path('functions/disappearing/disappearing-purge-firestore-admin-adapter.mjs').write_text(s)

# Inject the already-owned Admin Storage bucket into the scheduled purge repository.
p=Path('functions/index.mjs'); s=p.read_text()
old='''const db = getFirestore();\nconst { identityRepo, sessionRepo } = createRecoveryFirestoreAdminRepositories({ db });\nconst {messageRepo,attachmentRepo}=createMessageDeleteAdminRepositories({db,bucket:getStorage().bucket(ATTACHMENT_BUCKET)});\nconst disappearingPurgeRepository=createDisappearingPurgeFirestoreAdminRepository({db});\n'''
new='''const db = getFirestore();\nconst attachmentBucket=getStorage().bucket(ATTACHMENT_BUCKET);\nconst { identityRepo, sessionRepo } = createRecoveryFirestoreAdminRepositories({ db });\nconst {messageRepo,attachmentRepo}=createMessageDeleteAdminRepositories({db,bucket:attachmentBucket});\nconst disappearingPurgeRepository=createDisappearingPurgeFirestoreAdminRepository({db,bucket:attachmentBucket,requireStorage:true});\n'''
if old not in s: raise SystemExit('functions bucket wiring anchor missing')
p.write_text(s.replace(old,new,1))

# Local purge owner releases attachment runtime/object URLs after authoritative absence.
p=Path('app.js'); s=p.read_text()
old='''    for(const id of plan.outboxDeleteIds)outbox.delete(id);\n    await txDone(tx);\n    await persistState();\n    return{purgedMessageIds:ids,outboxDeleted:plan.outboxDeleteIds.length,historyUpdated:historyWrites.length};\n'''
new='''    for(const id of plan.outboxDeleteIds)outbox.delete(id);\n    await txDone(tx);\n    let attachmentUrlsReleased=0;\n    const targetIds=new Set(ids);\n    for(const [key,runtime] of [...attachmentRuntime.entries()]){\n      const messageId=String(key).slice(String(key).lastIndexOf(":")+1);\n      if(!targetIds.has(messageId))continue;\n      if(runtime?.result?.url){releaseAttachmentResult(runtime.result);attachmentUrlsReleased++;}\n      attachmentRuntime.delete(key);\n    }\n    await persistState();\n    return{purgedMessageIds:ids,outboxDeleted:plan.outboxDeleteIds.length,historyUpdated:historyWrites.length,attachmentUrlsReleased};\n'''
if old not in s: raise SystemExit('local purge anchor missing')
s=s.replace(old,new,1).replace('Disappearing text:','Disappearing:')
p.write_text(s)

# Version/cache bump.
replace('version.js','version: "0.9.9.18"','version: "0.9.9.19"')
replace('service-worker.js','SHELL_REVISION="0.9.9.18-direct-date-createdat"','SHELL_REVISION="0.9.9.19-disappearing-attachments"')
for f in ['outbox-reconciliation-boundary.test.mjs','direct-message-basic-path.test.mjs']:
    p=Path(f); t=p.read_text()
    if '0.9.9.18-direct-date-createdat' in t: t=t.replace('0.9.9.18-direct-date-createdat','0.9.9.19-disappearing-attachments')
    elif '0\\.9\\.9\\.18-direct-date-createdat' in t: t=t.replace('0\\.9\\.9\\.18-direct-date-createdat','0\\.9\\.9\\.19-disappearing-attachments')
    else: raise SystemExit(f'cache anchor missing: {f}')
    p.write_text(t)

# Existing compose/activation tests now require attachments to participate.
p=Path('disappearing-compose-policy.test.mjs'); t=p.read_text().replace("'Disappearing text:'","'Disappearing:'")
extra="""const attachment=stampOutgoingDisappearSelection({id:'att',text:JSON.stringify({fidunioAttachment:1,attachmentId:'a'})},300);\nif(attachment.disappearAfterSeconds!==300||attachment.disappearingPurgeVersion!==1)throw new Error('attachment selection is not stamped by the sole disappearing compose owner');\n"""
if 'attachment selection is not stamped' not in t: t=t.replace("const app=fs.readFileSync('./app.js','utf8');",extra+"const app=fs.readFileSync('./app.js','utf8');")
p.write_text(t)

p=Path('disappearing-activation.test.mjs'); t=p.read_text()
t=t.replace("assert.equal(disappearingPurgeVersionForOutgoing({text:attachment,value:300}),null);\nassert.equal(stampOutgoingDisappearSelection({text:attachment},300).disappearAfterSeconds,undefined);","assert.equal(disappearingPurgeVersionForOutgoing({text:attachment,value:300}),1);\nassert.equal(stampOutgoingDisappearSelection({text:attachment},300).disappearAfterSeconds,300);\nassert.equal(stampOutgoingDisappearSelection({text:attachment},300).disappearingPurgeVersion,1);")
t=t.replace("deploy=readFileSync('p.txt','utf8')","deploy=readFileSync('att.txt','utf8')")
t=t.replace("assert.match(app,/Disappearing text:/)","assert.match(app,/Disappearing:/)")
t=t.replace("console.log('Disappearing-message activation gate passed');","assert.match(fn,/createDisappearingPurgeFirestoreAdminRepository\\(\\{db,bucket:attachmentBucket,requireStorage:true\\}\\)/);\nassert.match(deploy,/roles\\/storage\\.objectAdmin/);\nconsole.log('Disappearing text + attachment activation gate passed');")
p.write_text(t)

# Permanent attachment activation wiring gate.
Path('disappearing-attachment-activation.test.mjs').write_text('''import assert from "node:assert/strict";\nimport {readFileSync} from "node:fs";\nimport {disappearingPurgeVersionForOutgoing,stampOutgoingDisappearSelection} from "./disappearing-compose-policy.js";\nconst descriptor=JSON.stringify({fidunioAttachment:1,attachmentId:"a1",kind:"photo"});\nconst stamped=stampOutgoingDisappearSelection({id:"m1",text:descriptor},300);\nassert.equal(stamped.disappearAfterSeconds,300);\nassert.equal(stamped.disappearingPurgeVersion,1);\nassert.equal(disappearingPurgeVersionForOutgoing({text:descriptor,value:300}),1);\nconst app=readFileSync("app.js","utf8"),adapter=readFileSync("disappearing-purge-firestore-admin-adapter.mjs","utf8"),fn=readFileSync("functions/index.mjs","utf8"),handoff=readFileSync("att.txt","utf8"),sw=readFileSync("service-worker.js","utf8");\nassert.match(app,/Disappearing:/);\nassert.match(app,/releaseAttachmentResult\\(runtime\\.result\\)/);\nassert.match(app,/attachmentRuntime\\.delete\\(key\\)/);\nassert.match(adapter,/sameBasis\\(current\\.basis,expected\\).*deleteAttachmentStorageTraces/s);\nassert.match(adapter,/bucket\\.deleteFiles\\(\\{prefix,force:true\\}\\)/);\nassert.match(adapter,/storageBeforeSource:true/);\nassert.match(fn,/const attachmentBucket=getStorage\\(\\)\\.bucket\\(ATTACHMENT_BUCKET\\)/);\nassert.match(fn,/createDisappearingPurgeFirestoreAdminRepository\\(\\{db,bucket:attachmentBucket,requireStorage:true\\}\\)/);\nassert.match(handoff,/roles\\/storage\\.objectAdmin/);\nassert.match(handoff,/functions:recovery:purgeDisappearingMessagesV1/);\nassert.match(sw,/SHELL_REVISION="0\\.9\\.9\\.19-disappearing-attachments"/);\nconsole.log("Disappearing attachment activation wiring gate passed");\n''')

# Add test script and baseline step.
p=Path('package.json'); data=json.loads(p.read_text()); data['scripts']['test:disappearing-attachment-activation']='node disappearing-attachment-activation.test.mjs'; p.write_text(json.dumps(data,separators=(',',':'))+'\n')
p=Path('.github/workflows/rebuild-baseline-security.yml'); t=p.read_text(); anchor='      - {name: Disappearing text activation, run: npm run test:disappearing-activation}\n'
if 'Disappearing attachment activation, run:' not in t:
    if anchor not in t: raise SystemExit('baseline activation anchor missing')
    t=t.replace(anchor,anchor+'      - {name: Disappearing attachment activation, run: npm run test:disappearing-attachment-activation}\n',1)
p.write_text(t)

# Durable project records.
prefixes={
'CURRENT-REBUILD.md':'''### DISAPPEARING ATTACHMENTS — 0.9.9.19 REPOSITORY CANDIDATE\n\nItem 2 is wired through the existing disappearing-message authority. Future photos/files/audio/video selected while `Disappearing` is enabled receive the same immutable `disappearAfterSeconds` + `disappearingPurgeVersion: 1` metadata as text. The existing scheduled executor remains the one purge coordinator. Its single server repository now receives the already-owned Admin Storage bucket, revalidates the source basis before physical mutation, deletes deterministic encrypted Storage prefix `attachments/{senderUid}/{conversationId}/{messageId}/`, then revalidates again and executes the existing Firestore receipt/grant/source commit with source last. The UID-scoped local purge owner also releases attachment object URLs/runtime entries after authoritative source absence. No client Storage-delete authority, tombstone, second scheduler, or second Firebase owner is introduced. Live activation requires the controlled `att.txt` handoff plus device acceptance.\n\n### DATE/TIME DEVICE ACCEPTANCE — 0.9.9.18\n\nUser confirmed group sender name/time, group date separators, and one-to-one/direct date separators are working. These presentation items are closed.\n\n''',
'hermes-memory.txt':'''DISAPPEARING ATTACHMENTS CANDIDATE (0.9.9.19): Extend the existing disappearing selection to future photos/files/audio/video using the same immutable duration + purge version. The existing serialized server purge executor remains sole coordinator; its one repository now also receives the existing Admin Storage bucket and deletes deterministic ciphertext prefix `attachments/{senderUid}/{conversationId}/{messageId}/` before final source deletion, with authoritative basis revalidation before Storage mutation and again before Firestore source deletion. Local UID-scoped purge releases attachment object URLs/runtime entries. No browser Storage delete, tombstone, second scheduler, or second Firebase owner. Live backend handoff `att.txt` is required before device testing. EVERY release bumps visible version + service-worker shell revision.\n\nDATE/TIME DEVICE ACCEPTANCE (0.9.9.18): User confirmed group date, group sender name/time, and direct one-to-one date separator are displaying correctly. Close those presentation items.\n\n''',
'README.md':'''## 0.9.9.19 disappearing-attachment candidate\n\nDisappearing selection now covers future encrypted attachments as well as text. Server deletion stays behind the existing serialized purge executor/repository: deterministic Storage ciphertext prefix first, Firestore source last after revalidation. Client delete permissions are unchanged. Live Storage IAM + Function redeployment and real-device acceptance are still required.\n\n''',
'BUG-LIST.md':'''## Disappearing attachments — 0.9.9.19\n\n**Status: REPOSITORY CANDIDATE / LIVE BACKEND HANDOFF REQUIRED.** Photos, files, audio and video now carry disappearing activation metadata and have server Storage-prefix + local object-URL cleanup wiring. Do not mark closed until `att.txt` live deployment succeeds and direct/group attachment expiry, unread protection, reopen, and multi-device absence are device-proven.\n\n''',
'DEVICE-ACCEPTANCE-BUGS.md':'''## Disappearing attachments — 0.9.9.19\n\n**Status: NOT YET DEVICE-TESTABLE until live backend handoff succeeds.** After deployment, test a fresh direct photo and a fresh group attachment with 5 minutes: recipients can open before expiry; expiry begins from the accepted Read authority; after expiry the message and encrypted attachment disappear from all devices; close/reopen must not restore them; unread attachments must remain beyond the duration until authoritative Read.\n\n## Date/time presentation — 0.9.9.18\n\n**Status: DEVICE ACCEPTED.** Group date, sender name/time, and direct date separator are working.\n\n''',
'FIDUNIO-BUILD-CHECKLIST.md':'''- [ ] **Disappearing attachments — 0.9.9.19 candidate:** same selection metadata for future attachments; one server purge repository deletes deterministic Storage ciphertext prefix before source, local object URLs converge, no client delete/tombstone; live `att.txt` deployment + direct/group/unread/reopen/multi-device acceptance pending.\n- [x] **Date/time presentation — 0.9.9.18:** group sender name/time + group/direct date separators device accepted.\n'''
}
for f,x in prefixes.items():
    p=Path(f); p.write_text(x+p.read_text())

p=Path('DISAPPEARING-PURGE-AUTHORITY.md'); t=p.read_text(); add='''### Attachment Storage extension — 0.9.9.19 repository candidate\n\nThe single server purge repository is extended to Firebase Storage rather than introducing a second purge owner. For an eligible source it derives the deterministic encrypted-object prefix from server-visible authority (`senderUid`, conversation/group ID, message ID), revalidates the complete existing Firestore basis before the first physical mutation, deletes that Storage prefix with Admin Storage, then revalidates the same basis again before executing the existing Firestore trace/source commit. The source Firestore message remains the final source trace deleted. Text sources safely exercise an empty prefix; attachment sources remove manifest/chunks without server decryption of the E2EE descriptor. The live repository instantiation requires an injected Admin Storage bucket. The UID-scoped local-purge owner releases matching attachment object URLs/runtime records only after authoritative source absence. There is still no browser Storage delete authority, expired marker, tombstone, second scheduler, or second Firebase owner. Live activation requires explicit IAM/deployment handoff and device acceptance.\n\n'''
if '### Attachment Storage extension — 0.9.9.19' not in t: p.write_text(add+t)

print('0.9.9.19 disappearing attachment repository edits prepared')
