import fs from "node:fs";
import assert from "node:assert/strict";
const firebase=fs.readFileSync("firebase.js","utf8");
const settings=fs.readFileSync("settings-lifecycle.js","utf8");
const rules=fs.readFileSync("firestore.rules","utf8");
for(const name of ["listFidunioBlockedUsers","blockFidunioUser","unblockFidunioUser"])assert.match(firebase,new RegExp(name));
assert.match(settings,/Blocked Users/);
assert.match(settings,/Block User/);
assert.match(settings,/Unblock/);
assert.match(rules,/match \/blocks\/\{blockedUid\}/);
assert.match(rules,/directPairUnblocked/);
assert.match(rules,/directCreatePairUnblocked/);
console.log("PASS: user blocking is wired through Settings, central Firebase owner, and Firestore authority");
